### ISSUE TITLE
Ordering of taxonomy results

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1045]
Is there a way to specify the order of taxonomy results, i.e. when a category is used.

I have a `contenttype` with `sort: title ASC`. This works as expected when I visit the `contenttype`'s listing page with records shown from `# - Z`.

However if I then select a `taxonomy` category the correct records are returned but only in the order that they were added to the system (newest first). I believe it should inherit from the `contenttype` unless specified otherwise.

Or have I missed something?

``` yaml
#contenttype for shops
shops:
    name: Shopping
    singular_name: Shop
    fields:
        title:
            type: text
    taxonomy: [ shops ]
    record_template: record.twig
    listing_template: listing.twig
    listing_records: 18
    sort: title ASC
    recordsperpage: 18
```

``` yaml
# categories for shops
shops:
    name: Shop Categories
    slug: shops
    behaves_like: categories
    multiple: true
    options: [ amusements, antiques & markets, ... ]
    listing_template: listing.twig
```
