### ISSUE TITLE
Removing relationships doesn't work

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1089]
I just downloaded a clean version of Bolt 1.5.5 to confirm this issue. I connected it to a MySQL DB, created a user, then added the following content types:

``` yaml
businesses: 
    name: Businesses
    slug: businesses
    singular_name: Business
    singular_slug: business
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title

events:
    name: Events
    slug: events
    singular_name: Event
    singular_slug: event
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
    relations:
        businesses:
            multiple: true
            label: Select business(es) to which this event applies, if any
            order: -datepublish
```

I then added three businesses. I then added an event and related it to two of the businesses and saved it. I then removed one of the related businesses and that worked fine (leaving one). I then went to remove the final remaining business, however it does not get removed.

I think the `multiple: true` option under relations may be playing a part in this. If I switch to `false` I can then select `(none)` from the drop-down to remove the related business. With multiple though it just keeps coming back.

The same thing also happens with taxonomies when using `multiple: true`.
