### ISSUE TITLE
Problems uploading image

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#1114]
Bolt Version: 1.6
this happens when trying to upload an image from a field type: (contenttypes.yml)

``` yml
    fields:
[...]
        image:
            type: image
[...]
```

It's going on a localhost LAMP on Ubuntu Precise type before the 1.5.3 version of Bolt also had this problem, but I can not say that this incident happened updated.

screenshot:
![file](https://cloud.githubusercontent.com/assets/6233822/2697277/6a2aafc6-c3ec-11e3-9703-57be00a31f90.png)
