### ISSUE TITLE
[Q] Routing: contenttype overrides (pages)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#1121]
I'm using the route from the example for contenttype overrides.
I place the following route on top to make pages link to the first url segment 
e.g. /about instead of /page/about

```
pagebinding:
    path:           /{slug}
    defaults:       { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'page' }
    contenttype:    pages
```

However, now i cannot access the entries listings.
e.g. `/entry/foobar` does work, but `/entries` show whoops (or 404) 

As work-around i inserted another route to frontend:listing, but somehow that seems a bit redundant, or is that intended?

```
newsentries:
  path: /entries
  defaults: { _controller: 'Bolt\Controllers\Frontend::listing', 'contenttypeslug': 'entries' }

pagebinding:
  path: /{slug}
  defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'page' }
  contenttype: pages
```
