### ISSUE TITLE
Related content needs to honour contenttype order.

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1138]
If you have a content type like this:

``` yaml
artists:
    name: Artists
    slug: artists
    singular_slug: arists
    fields:
        title:
            type: text
            class: large
            required: true
        description:
            type: html
            class: large
            required: true
        image:
            type: image
            required: true
    relations:
        events:
            multiple: true
            label: Select event to which this artist is related
            order: title
    searchable: false
    sort: title ASC
```

When you're on the event(s) record and call:

``` twig
{% set relatedoffers = record.related('artists') %}
```

The records come back in the order that they were assigned to the event (oldest first). It would be good if they could be ordered according to their content type.
