### ISSUE TITLE
Permissions don't appear to be working.

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1146]
I've set a user in my system to be an `admin` user.

In my `permissions.yml` config I have the following:

``` yaml
global:
    ...
    useraction: [ admin, developer ] # enable/disable/delete
    useredit: [ admin, developer ] # user settings
    users: [ admin, developer ] # view user overview
    ...
```

Yet the option to see users is not listed in the dashboard under settings.
