### ISSUE TITLE
On Menu bar gereated by menu()

### ISSUE THREAD

**Issue by taylorren** [bolt/bolt#1201]
My menu.yml looks like this:

```
main:
  - label: Home
    title: G4P.cc首页
    path: homepage
    class: first
  - label: Events
    path: events/
 - label: Galleries
    path: galleries
  - label: Resouces
    path: resources
    class: last
```

And I generate the menu bar using:

```
menu('main', 'nav.html.twig');
```

And the nav.html.twig contains:

```
    <ul class="nav navbar-nav">
            {% for item in menu %}
        <li class="{% if item|current %}active {% endif %}nav-item"><a href="{{item.link}}">{{item.label}}</a></li>
                {% endfor %}
    </ul>
```

It works fine for top level items, i.e., for "localhost/events" page, which contains the menu bar, the "Events" got highlighted. 

For "localhost/event/some-slug", however, the "Events" did not get highlighted. 

Previously, before using "menu()" function, I used a sort of:
1. In events record template, "set active=2";
2. In nav.html.twig, I manually determine the highlight item by "if active ==1", "if active =2"...
3. However, "active" can't be passed into "menu()" call. 

Any neat solutions on this? I can revert to my previous solution, anyway but want to see if any other suggestions/hints.
