### ISSUE TITLE
'View' Permission Not Obeyed in Front End

### ISSUE THREAD

**Issue by luxlogica** [bolt/bolt#1263]
I am not sure whether what I want to do is achievable with Bolt at the moment, but in trying to get where I want, it seems I came across a problem.

I wanted to setup a record with pages akin to an 'Account' page - that is: each user in the system has their own page, and a logged in user should be able to view only their own page. Admin users should be able to view everyone's. 

I setup a 'Memberships' contenttype, and gave it the following permissions:

```
contenttypes:
    memberships:
        view: [owner, admin]
        edit: [admin]
        create: [admin]
```

Other contenttype  permission settings are:

```
contenttype-all:
    edit: [ developer, admin, chief-editor ]
    create: [ developer, admin, chief-editor ]
    publish: [ developer, admin, chief-editor ]
    depublish: [ developer, admin, chief-editor ]
    delete: [ developer, admin ]
    change-ownership: [ developer, admin ]

contenttype-default:
    edit: [ editor ]
    create: [ editor ]
    change-ownership: [ owner ]
    view: [ anonymous ]
```

Using these settings, in the **front end** any user can still see everyone else's 'membership' page - that is, if I have 3 users, 'Peter', 'Paul' and 'Mary', logged in as any of these users I can directly access the membership pages of the others in the front end.

```
http://test.site/membership/peter -- accessible by all 3
http://test.site/membership/paul -- accessible by all 3
http://test.site/membership/mary -- accessible by all 3
```

Bolt's default record template even conveniently puts in a navigation bar, so the users can navigate to each other's records simply by accessing their own...

I thought this may be happening because of the 'view' permissions in 'contenttype-default' being set to 'anonymous' (it shouldn't, because the view permissions set in the contenttype itself should be overriding it), but just in case, I commented that line out, to test it:

```
    #view: [ anonymous ]
```

Even then, all users can still see and navigate to each other's 'membership' page in the front end. 

Am I doing something obviously wrong? Is this intended behaviour - or a bug?
