### ISSUE TITLE
Hierarchical content (was "Any sub-page solutions yet?")

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#1295]
The previous time I worked with Bolt you couldn't nest pages easily. This became a bit problematic when setting up the routes, canonical url, and sitemap.xml, requiring quite a bit of manual tinkering. Perhaps I implemented it wrongly, I'm not sure.

I wondered if anyone had found a decent method of implementing sub-pages in Bolt and whether they would be able to share how they've implemented it with me. My main concern is that if I build a website for a user, and they later choose they want to add an additional page under a section, then they won't be able to without messing around with the routes configuration.

Some example child page paths I would like to have:
- /about
- /about/members
- /about/standards
- /why-us
- /why-us/example-one
- /why-us/example-two

/why-us is actually more of a listing page so that ones not too bad. The problem is more when you have pages that need nesting under other pages. I could create 'about' as a content type but that seems a bit illogical.

Anyway, your thoughts would be greatly appreciated.

**Comment by Pinpickle** [comment]
Chiming in about the 'why' part of the question. I think a big part of it is an intuitive way to organise the order of pages as well as grouping them. Yes this can be done with grouping taxonomies but they're a bit cumbersome to create if you're wanting to create a system that is versatile for any editor to use.

**Comment by diggersworld** [comment]
On my last project using Bolt I took the approach of creating a page content type for each section of the site. I found this actually made it nicer for the end-user (content editor) to use as it broke the pages into sections on the back-end too.

So I had a `pages` content type for standalone pages, i.e. no children.

Then for `about` and it's sub pages I had a `about-pages` content type and created all the children and the index itself under that content type. So based on my original post I had three records `index`, `members`, `standards`. I probably made a minor addition to the routing so that `/members` retrieved `/members/index`. The others worked out the box.

Then for the menu I just used a .yml file to configure the list order. However you could do it dynamically to a point if you add an `order` field on your contenttype (assuming date or title order is insufficient).

**Comment by activestylus** [comment]
Was any progress made on this feature? Also, the docs leave a bit to be desired in the Routing section re: requirements. I also thought it was strange/inconsistent to have the host parameter outside the scope of requirements

**Comment by activestylus** [comment]
Just to toss my 2 cents as to the necessity of this feature here is a real world case:

Fashion company. Wants listing of seasonal collections which contain products. These products have very generic names like "brown tweed jacket" and would appear in various collections. Under current URL scheme this is impossible, unless you tag another feld with the slug (can it be done with the ID field??). The ideal scenario would be something like how Rails handles unique slugs. It simply makes them scopable to their parent resources, giving the user nice URLS like:

```
/spring-2016/blue-suede-shoes
```
Attempts to load `/blue-suede-shoes` will result in 404, unless additional routes are specified, and alternate slug composition for unique IDs

**Comment by LucasPekel87** [comment]
I hope this feature will be picked up, We were looking for a cms to use for the new websites of our company and bolt looked promissing. But when we noticed this feature was missing, that's a deal-braker for us. Hope it's gonna be implemented in a the future.

**Comment by SahAssar** [comment]
@LucasPekel87 Well it seems the main obstacle for this is that we don't know how it should be done. I have a couple of cases where this would have been useful, but it isn't really easy to do this kind of thing and make it work for (mostly) everyone. I haven't heard of anyone here being against this, but doing it requires finding a good solution to it. If you know of a way to implement this in a generalized while useful way I'm sure people will listen to you :)

**Comment by SahAssar** [comment]
@LucasPekel87 Also, the reason that we keep this issue open is that we hope to solve it someday ;)

**Comment by use** [comment]
Couldn't this problem be 100% solved by enabling slugs to contain the / character?

We can already organize content into hierarchy using the menus system, and the flexible relationship system.  So I think the URLs are the only hangup right?

**Comment by SahAssar** [comment]
@use Well, that would only solve it for a single usecase on the frontend, I would hope a solution for this would be more general and more integrated into the backend... If you just want slashes in your slugs you can either have a look at [How to Allow a "/" Character in a Route Parameter](http://symfony.com/doc/current/cookbook/routing/slash_in_parameter.html) or #1886 in which using taxonomies as the additional route parameter was discussed (and @bobdenotter posted a routing example for it).

**Comment by SahAssar** [comment]
We just had a client that wanted hierarchical paths, so I looked into it. Basically all that I needed to do was to use the internationalslugs extension to allow '/' in slugs generated by bolt and to edit my routing to have a laxer requirement for the slug parameter:
```
contentlink:
    path: '/{contenttypeslug}/{slug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::record'
    requirements:
        slug: ".+"
        contenttypeslug: 'Bolt\Controllers\Routing::getAnyContentTypeRequirement'
```
Hopefully this will be useful to those that only want this feature for the "pretty paths".

**Comment by flrvt** [comment]
This is how I’m dealing with ‘subpages’ in Bolt 3 now:

Different contenttypes for each ‘subcategory’. The pages directly under the root are normal pages. These parents then have a listing template set that will list the appropriate contenttype. This actually resembles the way @diggersworld did it in his comment above.

I had to do it this way because I was tied to a very specific hierarchal URL structure with pretty links. Also, this way bob’s SEO extension can be used on the listing pages as well to provide optimized metadata.

Let me show how that looks like with soms code snippets:

In contenttypes.yml I am using repeated yaml nodes to put a 'parent' and 'child' contenttype together. But this alone will do nothing for hierarchy.
```yaml
#
# Parent pages at the root level
pages:
    name: Pages
    singular_name: Page
    fields:
        <<: *default_fields
        <<: *default_seo_fields
    <<: *default_attributes
    record_template: page_default.twig


#
# Subpages: /feest-types/*
feest-types:
    name: Feest types
    singular_name: feest type
    slug: feest-types
    singular_slug: feest-types
    fields:
        <<: *default_fields
        <<: *default_seo_fields
        <<: *default_teaser_fields
    <<: *default_attributes
    icon_many: "fa:caret-right"
    icon_one: "fa:file-o"
    record_template: page_default.twig
    listing_template: listing.twig
```

In my `routing.yml` there is nothing really special except for the default 'pagebinding' route (which is normally commented out).
```yaml
pagebinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: pages
    contenttype: pages
```

The "clever" part is that I put a templateselect in the `pages` contenttype which also allows the selection of listing templates. My listing template then fetches the 'children' of that parent page like this:
```twig
{# Fetch the child records but check if we are not overwriting an existing array of records #}
{% if records|length < 1 %}
  {% setcontent records = record.slug %}
{% endif %}
```
This does look a bit funny in my eyes but have not found a way to make the code more logical.

So in order to create hierarchy, I need to:
- create a contenttype for the subpages
- create a parent page with the same slug as the newly created contenttype

This renders pretty links where `/feest-types` is the parent and the children are located in `/feest-types/*`

This works but does feel a bit hacky. I also feel there could be a better solution than this.
