### ISSUE TITLE
Getting wrong links in menu with index.php

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1358]
At the moment I use index.html for a "On Construction" message. So I link to my startpage with `http://example.com/index.php` instead of just `http://example.com/` or `/`.

There's also a

```
pagebinding:
  path: /{slug}.html
  defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'page' }
  contenttype: pages
```

entry in the routing table to allow `about.html` and other links like that.

When I start from `http://example.com/about.html` everything is fine and the generated links in the menu are ok. As soon as I hit the startpage link `http://example.com/index.php` links generated look like `http://example.com/index.php/about.html`. Btw, the homepage binding is used rendering that startpage.

So am I wrong here or bolt?
