### ISSUE TITLE
Related records not pulling from .related() call

### ISSUE THREAD

**Issue by whoacowboy** [bolt/bolt#1366]
I have been unable to pull related records from a record. I related the work to a parent record, and I was able to see that.

When I added child records the related() call only saw the parent relation.

I removed all relations except for the main record and its children (work->slides) and no records have been pulled. I noticed that the database was not updating the bolt_relations when I added or removed a relation.

Any guidance would be appreciated.

Here is what I am using and some relevant code. Let me know if you need any more information.

bolt_latest.zip downloaded July 3, 2014 (couldn't find version number).
using a sqlite db.
## template.twig

``` twig
{% setcontent works = "works" orderby 'position' %}

{% for work in works %}

<h1>work</h1>
{{ print(work) }}

<h1>work.related()</h1>
{{ print(work.related()) }}

<h1>work.related('slides')</h1>
{{ print(work.related('slides')) }}

{% endfor %}
```
## output

![output](https://cloud.githubusercontent.com/assets/8116953/3542458/64bd5e4e-0857-11e4-85fd-e6fd07d06c8e.png)
## database

![base](https://cloud.githubusercontent.com/assets/8116953/3542488/c4a8ebd4-0857-11e4-929c-1c8f47a14e78.png)
## contenttypes.yml

``` YAML
works:
  name: Works
  singular_name: Work
  fields:
    title:
      type: text
      class: large
    position:
      type: integer
      ...
  default_status: publish
  sort: position DESC
  relations:
    slides:
      multiple: true
      label: Slides
      order: position

slides:
  name: Slides
  singular_name: Slide
  fields: 
    title:
      type: text
      class: large
    ...
    position:
      type: integer
  relations:
    works:
      multiple: false
      label: Select a work
      order: title
```
