### ISSUE TITLE
Slug prefix 'none-' being added on save of Kitchensink contenttype

### ISSUE THREAD

**Issue by GwendolenLynch** [bolt/bolt#1483]
In the kitchensink contenttype slug is defined:

``` yaml
slug:
    type: slug
    uses: [ selectfield, title ]
```

But if selectfield is empty the slug becomes prefixed with 'none-'.  Probably should be handled more gracefully.
