### ISSUE TITLE
Unable to define value-label select options for a select-field in content type

### ISSUE THREAD

**Issue by jeroenmarinus** [bolt/bolt#1803]
I have following content type definition, but both the value and the label of the select options are the same and are what's supposed to be the label.
I'm using Bolt 1.6.9.

```
call-to-actions:
    name: Call to actions
    singular_name: Call to action
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        block:
            type: select
            values: { '1': 'Left', '2': 'Middle', '3': 'Right'}
```
