### ISSUE TITLE
checkbox still on

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#1820]
Hi I have an issue with checkbox (on current bolt2 dev install) – it is still checked.
It has beeen set up in contenttypes.yml:

```
blog:
        …
        featured:
             type: checkbox
             label: check-it
```

When not checked amd save the blog post it toggles on, after reopen the blog post in admin, the checkbox is checked… No way to save the entry with unchecked checkbox.

I have just tryied on fresh install from git and even in Showcase contenttype, whne saved, it toggles on automaticly, so I asume it is bug.
