### ISSUE TITLE
Add 'config.yml' from theme to template cascading. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#1869]
Bolt uses its own template cascading to determine which template to use for displaying content. 

It should also be possible to define the templates to use in the config.yml for the theme. This way a theme developer can set the default templates. 

When it comes to specificity, this should come between "defined in contenttype" and "Defined in global config.yml" 

in the config.yml in the theme it should recognize these: 

``` yml
maintenance_template: maintenance_default.twig
homepage_template: index.twig
record_template: record.twig
listing_template: listing.twig
search_results_template: listing.twig
```
