### ISSUE TITLE
Date field is not saved

### ISSUE THREAD

**Issue by richardhinkamp** [bolt/bolt#205]
I have a content type with these fields:

``` yaml
datetest:
    name: Datetests
    singular_name: Datetest
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        date:
            type: date
        other:
            type: date
    sort: date DESC
    recordsperpage: 10
```

When saving an item, the "date" and "other" fields are NULL in the databases instead of the selected date. Using latest master.
