### ISSUE TITLE
Certain translation values cause submenu merging

### ISSUE THREAD

**Issue by michaeljayt** [bolt/bolt#2062]
In any locale (let's say even en_GB), if you replace the k/v pairs in messages.en_GB.yml with the following value (like with Chinese characters):

``` yml
"File Management": "文件管理"
"Extras": "附加"
"Configuration": "配置"
```

you will get the merged submenus for File Management/Extras/Configuration, i.e. the submenu of File Management/Extras/Configuration are all the same, with the same subitems.

Any ideas about this strange behavior?
