### ISSUE TITLE
Ckeditor options need some enhancement

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#2083]
If you try to set options like this
```
options:
    ckeditor:
        toolbar:
            paragraph: ['NumberedList', 'BulletedList']
```
it doesn't work because toolbar uses a name/items format:
```
config.toolbar = [
                { name: 'basicstyles', items: ['NumberedList', 'BulletedList', 'Indent', 'Outdent'] },
                …
```
We should add a special treatment for ``toolbar`` in the overide settings part to get that working.

Pinging @GDmac could this be a job for you?
