### ISSUE TITLE
'Relations' broken after goofing around with it

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#209]
I was goofing around with the contenttypes for a new site. I was adding relations to certain contenttypes, saving contenttypes.yml and then altering it again. After that 'relations' seems broken.
(Let me know if someone wants to have a look at it)

Update: I found the problem. You can't use "label" in relations like this:

```
relations:
    discs:
        multiple: true
        order: title
        label: Choose a disc
```

(Bolt 1.0.0)
