### ISSUE TITLE
Custom contenttype doesn't properly show name.. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2200]
Contenttype: 

```
pompidoms:
    name: Pompidoms
    singular_name: Pompidom
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title
        teaser:
            type: html
```

See screenshots: 

![screen shot 2014-11-18 at 09 54 40](https://cloud.githubusercontent.com/assets/1833361/5084625/2addb958-6f09-11e4-8477-39645a3ad211.png)

![screen shot 2014-11-18 at 09 57 45](https://cloud.githubusercontent.com/assets/1833361/5084655/72f22652-6f09-11e4-91fa-4dc7c982f952.png)

![screen shot 2014-11-18 at 09 58 11](https://cloud.githubusercontent.com/assets/1833361/5084658/75eb71a6-6f09-11e4-8231-942804bb44bf.png)
