### ISSUE TITLE
slug with date

### ISSUE THREAD

**Issue by blockmurder** [bolt/bolt#2207]
I know there has been a fix for issues #2125 which sets the date to, for example 2014-07-17-**_000000**_
As I use the date in my slug, it looks a bit nasty (e.g. /entrie/testentry-2014-11-02-000000)!
Is there something one could do to get rid of these appended zeros?

configuration of contenttypes:

```
        slug:
            type: slug
            uses: [ title, date ]
```

...

```
        date:
            type: date
            label: "Datum"
            required: true
            default: "first day of next month"
```
