### ISSUE TITLE
Problem with categorybinding route

### ISSUE THREAD

**Issue by crzzano** [bolt/bolt#2209]
My binding on `routing.yml`

``` yaml
categorybinding:
  path: /{categories}/{slug}
  defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'blog', 'categories': 'none' }
  requirements:
    categories: [ 'Bolt\Controllers\Routing::getTaxonomyRequirement', ['categories', 'none'] ]
  contenttype: blog
```

Creates the following error for every ocurence of {{record.link}} when looping through records:

```
**** Error ONLY appears when the DEBUG BAR is NOT showing. ****
<br />
<b>Strict Standards</b>:  Only variables should be passed by reference in <b>[mypath]/src/Content.php</b> on line <b>811</b><br />
<br />
<b>Strict Standards</b>:  Only variables should be passed by reference in <b>[mypath]/src/Content.php</b> on line <b>811</b><br />
```

PHP Version 5.4.34
(Server allows PHP scripts to change error reporting)
