### ISSUE TITLE
Change Ownership permission doesn't work correctly..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2274]
The default permissions say: 

```
contenttype-all:
    edit: [ developer, admin, chief-editor ]
    create: [ developer, admin, chief-editor ]
    publish: [ developer, admin, chief-editor ]
    depublish: [ developer, admin, chief-editor ]
    delete: [ developer, admin ]
    change-ownership: [ developer, admin ]
```

But, only 'root' is allowed to change ownership of a record. `developer` and `admin` should be able too, but they aren't.
