### ISSUE TITLE
Import Weebly content

### ISSUE THREAD

**Issue by HorlogeSkynet** [bolt/bolt#2302]
Hi everybody !

I'm here for some information about the import of content from Weebly, to Bolt.
I've got a little personnal site hosted there, and I'd like to know if it's possible to migrate it.

Fyi, Weebly generates RSS feeds for each page, and I have also an archive with all the content in .html format, with the images and CSS style beside...

Is there an extension to import directly ?

Thx for your answer & help

**Comment by bobdenotter** [comment]
Ok, the extension is here: https://github.com/bobdenotter/rsscrawler

It is still pretty barebones, though.. I did use your weebly account to test the import, so if you don't know how the extension works, just add a contenttype like this:

```
feeditems:
    name: Feeditems
    singular_name: Feeditem
    description: "Crawled feed items. Do not change manually."
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        itemid:
            type: text
            variant: inline
        content:
            type: html
        raw:
            type: textarea
        source:
            type: text
            variant: inline
        author:
            type: text
            variant: inline
        image:
            type: text
            variant: inline
        sitetitle:
            type: text
            variant: inline
        sitesource:
            type: text
            variant: inline
    taxonomy: [ tags ]
```

And use phpmyadmin, or something to import your .sql file: https://www.dropbox.com/s/pjfa0vhj3po7y0u/bolt_2015-03-29.sql?dl=0 

I'm sure you or Corentin can tweak it to how you want it. If you get stuck, let me know! :-)
