### ISSUE TITLE
How to filter setcontent by relations?

### ISSUE THREAD

**Issue by rkmax** [bolt/bolt#2419]
Having the follow contenttypes.yml

```yaml
books:
  name: books
  singular_name: book
  fields:
    name: ...

pages:
  name: pages
  singular_name: page
  relations:
    books:
      multiple: false
 fields:
    number: ...
    text: ...
    hasPictures: ...
```

i want filter like

```
{% setcontent pages = 'pages' where {'hasPictures': true, 'book.id' : 1} %}
```
