### ISSUE TITLE
multiple relations to the same contenttype

### ISSUE THREAD

**Issue by jmschelcher** [bolt/bolt#2534]
Hi,

I need to link a content type to another content type but twice. In oder words, I need to make two relations to the same content type.

Example:
- imagine a contenttype "persons"
- imagine another contenttype "discussion_groups"

"discussion_groups" has to be linked twice to "persons":
- one relation to designate a discussion group "chief" (unique)
- one relation to designate its "members" (multiple)

I think this is not yet possible because the relation is names based on the contenttype identifier.
Something like that should be cool:
```yml
persons:
    name: Persons
    singular_name: Person
    fields:
        [..]

discussion_groups:
    name: Discussion Groups
    singular_name: Discussion Group
    fields:
        [...]
    relations:
        chief:
            contenttype: persons
            multiple: false
            label: Select a chief
        members:
            contenttype: persons
            multiple: true
            label: Select members
```

Is something like that planned ?
Many thanks !

Jean-Michel

**Comment by bobdenotter** [comment]
Hi @jmschelcher, 

This has been brought up occasionally. Originally we designed the relations to be non-directional, but it turns out to be limiting in some cases. Like the one you describe. 

It's on my list of things to fix, someteime in the near future.. My changes would allow you to have uni-directional relationships, as well as being able to do multiple relationships between two contenttypes.

**Comment by jmschelcher** [comment]
Mmmh after watching the code and DB, it will probably need some DB changes.
I understood that the bolt_relations describes all many2many relations (fields: id, from_contenttype, from_id, to_contenttype, to_id).
It would need another field that could be called "relation_name"...

**Comment by jmschelcher** [comment]
ok fine, if I can help, don't hesitate :-)

**Comment by bobdenotter** [comment]
@jmschelcher Sure! I'll see if i can outline what needs to be done in the upcoming days, and we could split the actual work. :-)

**Comment by spicyroland** [comment]
What about one to one relations? For example something like this:
```
category:
    name: Categories
    singular_name: Category
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
    relations:
        category:
          multiple: false
          order: id
          label: Select a parent id
    recordsperpage: 50
    default_status: publish
```
Couldn't get this working neither...
