### ISSUE TITLE
Route by ID is throwing error

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2727]
Route in `routing.yml`

``` yaml
eventslink:
  path: /calendar/{id}/
  defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'event' }
  contenttype: events
```

Navigate to /calendar/5/ (generated by `record.link`)

And then error:

![image](https://cloud.githubusercontent.com/assets/3238878/6073289/2ac3ad64-ae11-11e4-90e5-7678147ad0cf.png)

```
Whoops\Exception\ErrorException thrown with message "get_class() expects parameter 1 to be object, string given"

Stacktrace:
#10 Whoops\Exception\ErrorException in /Users/christian/Code/web/harbourside-website/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:121
#9 Whoops\Run:handleError in <#unknown>:0
#8 get_class in /Users/christian/Code/web/harbourside-website/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:121
#7 Symfony\Component\HttpKernel\Controller\ControllerResolver:doGetArguments in /Users/christian/Code/web/harbourside-website/vendor/silex/silex/src/Silex/ControllerResolver.php:50
#6 Silex\ControllerResolver:doGetArguments in /Users/christian/Code/web/harbourside-website/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:105
#5 Symfony\Component\HttpKernel\Controller\ControllerResolver:getArguments in /Users/christian/Code/web/harbourside-website/vendor/silex/silex/src/Silex/ServiceControllerResolver.php:58
#4 Silex\ServiceControllerResolver:getArguments in /Users/christian/Code/web/harbourside-website/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:142
#3 Symfony\Component\HttpKernel\HttpKernel:handleRaw in /Users/christian/Code/web/harbourside-website/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:66
#2 Symfony\Component\HttpKernel\HttpKernel:handle in /Users/christian/Code/web/harbourside-website/vendor/silex/silex/src/Silex/Application.php:543
#1 Silex\Application:handle in /Users/christian/Code/web/harbourside-website/vendor/silex/silex/src/Silex/Application.php:520
#0 Silex\Application:run in /Users/christian/Code/web/harbourside-website/index.php:16
```

**Comment by GawainLynch** [comment]
On master by chance?

**Comment by Pinpickle** [comment]
Nah, 2.0.5

**Comment by bobdenotter** [comment]
Will you be creating the links by yourself, eventually? If so, you can easily work around this by using `slug` instead of `id`

```
eventslink:
  path: /calendar/{slug}/
  defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'page' }
  contenttype: pages
```
