### ISSUE TITLE
upload: does not work with mp3 files

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2760]
I try to upload a file called music.mp3, but I returns an error banned file type, although this is explicitly allowed in config.yml and in the field contenttypes.yml even the warning says that mp3 is allowed. Using the file manager it is the same but without any error warning.

Can anyone reproduce the error?

config.yml
```yml
# The following is the default list of file-types that can be uploaded through the 'files' screen.
 accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]
```

contenttypes.yml
```yml
        song:
            type: file
            label: Canción
            extensions: [ mp3, ogg ]
```

![files](https://cloud.githubusercontent.com/assets/6233822/6097203/cf6ff3a4-af92-11e4-87e7-5572746a86eb.png)

I had no problem with images (jpg, png, svg, etc).
