### ISSUE TITLE
[Regression] Using 'allowtwig: true' in a HTML field not working in master

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2789]
```yaml
        body:
            type: html
            height: 300px
            allowtwig: true
```

Related to #2401
Introduced in #2592
