### ISSUE TITLE
Creating records in the frontend

### ISSUE THREAD

**Issue by jeff-h** [bolt/bolt#2839]
I'm hoping someone can provide me some guidance on how to set up Bolt to allow anonymous visitors to create records of a specific content type from the front end.

I've configured the "Showcases" content type as follows:

```yml
contenttypes:
    showcases:
        create: [ everyone ]
        frontend: [ everyone ]
```

but I'm unsure what to do next. I think I need to create a user-defined route, but what `controller` to use?
