### ISSUE TITLE
Email sending fails silently with SMTP

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2863]
Hi there,

There's an issue with those comments:
https://github.com/bolt/bolt/blob/master/src/Application.php#L328
https://github.com/bolt/bolt/blob/master/app/config/config.yml.dist#L232

If you don't fill the SMTP parameters, emails won't be sent.
The Silex `SwiftmailerServiceProvider` uses SMTP by default (see https://github.com/silexphp/Silex-Providers/blob/master/SwiftmailerServiceProvider.php#L51), and does fall back to the PHP `mail` function that is provided by the `Swift_MailTransport` class: 
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/MailTransport.php

I submitted a pull request that fixes this.

Let me know if you want me to change something in this PR.

**Comment by GDmac** [comment]
RFC (Request for comment)
- Bumped into this too some time ago. However, instead of fallback,  
  I'ld prefer an explicit setting. Like, mailhandling: smtp | php

```yml
mailoptions:
   mailhandler: php
#  host: localhost
#  port: 25
#  username: username
#  password: password
#  encryption: null
#  auth_mode: null
```
