### ISSUE TITLE
Taxonomy Overview Template

### ISSUE THREAD

**Issue by callmenick** [bolt/bolt#2865]
Looking for a way to have an "overview" style template for a taxonomy. For example, current taxonomy set up:

```
# Categories

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: false
    listing_template: category.twig
    options: [ tutorials, snippets, articles, resources, projects ]
```

I have a contenttype of `post` also:

```
posts:
    name: Posts
    singular_name: Post
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: textarea
        body:
            type: html
            height: 360px
        image:
            type: image
            group: media
    searchable: true
    taxonomy: [ categories ]
    record_template: post.twig
    listing_template: posts.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
```

Looking for a way to access the url `category/tutorials` with certain information:

1. Be able to output the taxonomy name
2. Is it possible to add extra fields to the taxonomy, like "description", and access it?

Thanks!
