### ISSUE TITLE
Front-end AJAX calls return 404 after upgrade

### ISSUE THREAD

**Issue by tentoseven** [bolt/bolt#2874]
I've just updated Bolt from 2.0.2 to the latest build (2.0.6).

My AJAX calls no longer work, they return a 404. _I can access the same route directly in the browser without any issue_. Using jQuery I've tried $.load, $.ajax and $.get, but they all return the same error along with a 404 response:

```json
{"error":{"type":"Symfony\\Component\\HttpKernel\\Exception\\HttpException",
"message":"No template for 'client2' defined. Tried to use 'mysite-2015-bootstrap\/casestudy.twig'.",
"file":"\/Users\/xxx\/Current\/mysite2015\/vendor\/silex\/silex\/src\/Silex\/Application.php","line":378}}
<meta name="generator" content="Bolt">
<link rel="canonical" href="http://local.mysite.com/case-study/client2">
```

These are the headers before upgrading:

    .	Remote Address:127.0.0.1:80
	.	Request URL:http://local.mysite.com/case-study/client2
	.	Request Method:GET
	.	Status Code:200 OK
	Request Headers
	.	Accept:text/html, */*; q=0.01
	.	Accept-Encoding:gzip, deflate, sdch
	.	Accept-Language:en-US,en;q=0.8
	.	Connection:keep-alive
	.	Cookie:bolt_session=05fcde776c8ab01037df349d5d5998ce;bolt_authtoken=6987351d401f31d519af2e5c2f09ba56
	.	Host:local.solartek.com
	.	Referer:http://local.mysite.com/window-film/heat-reduction-window-film
	.	User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
	.	X-Requested-With:XMLHttpRequest
	Response Headers
	.	Cache-Control:no-cache
	.	Connection:Keep-Alive
	.	Content-Length:2629
	.	Content-Type:text/html; charset=UTF-8
	.	Date:Sat, 21 Feb 2015 08:21:19 GMT
	.	Frame-Options:SAMEORIGIN
	.	Keep-Alive:timeout=5, max=93
	.	Server:Apache/2.4.9 (Unix) PHP/5.5.14
	.	X-Debug-Token:732f71
	.	X-Frame-Options:SAMEORIGIN
	.	X-Powered-By:PHP/5.5.14

And these are the headers after upgrading:

	.	Remote Address:127.0.0.1:80
	.	Request URL:http://local.mysite.com/case-study/client2
	.	Request Method:GET
	.	Status Code:404 Not Found
	Request Headers
	.	Accept:*/*
	.	Accept-Encoding:gzip, deflate, sdch
	.	Accept-Language:en-US,en;q=0.8
	.	Connection:keep-alive
	.	Cookie:bolt_session=05fcde776c8ab01037df349d5d5998ce;bolt_authtoken=6987351d401f31d519af2e5c2f09ba56
	.	Host:local.solartek.com
	.	Referer:http://local.mysite.com/window-film/heat-reduction-window-film
	.	User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
	.	X-Requested-With:XMLHttpRequest
	Response Headers
	.	Cache-Control:no-cache
	.	Connection:Keep-Alive
	.	Content-Length:394
	.	Content-Type:text/html; charset=UTF-8
	.	Date:Sat, 21 Feb 2015 08:22:38 GMT
	.	Frame-Options:SAMEORIGIN
	.	Keep-Alive:timeout=5, max=94
	.	Server:Apache/2.4.9 (Unix) PHP/5.5.14
	.	X-Debug-Token:5f6561
	.	X-Frame-Options:SAMEORIGIN
	.	X-Powered-By:PHP/5.5.14

**Comment by bobdenotter** [comment]
That's weird. I'll see if i can reproduce it.

**Comment by psren** [comment]
I can reproduct it.

The JS used to test it is
```js
$.get('/kategorie/myslug', function(data) {console.log(data)}); 
```

And this is my contenttype
```yaml
categories:
    name: Kategorien
    singular_name: Kategorie
    fields:
        title:
            type: text
            class: large
            group: content
        headline:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
    record_template: category.twig
```

A more detailes description to the problem is in this gist:
https://gist.github.com/psren/64e00bc6b79b7a5ebe7d
