### ISSUE TITLE
"Last Modified" doesn't display correct title.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2895]
See screenshot.

![screenshot_2015-02-22_14_53_08](https://cloud.githubusercontent.com/assets/1833361/6318751/dac5a828-baa2-11e4-9806-00d16c99697b.png)

The field is even named "title" in the contenttype:

```YML
paginas:
    name: Paginas
    singular_name: Pagina
    fields:
        title:
            type: text
            class: large
            required: true
            label: Titel
```
