### ISSUE TITLE
Field name end with a '.' (dot) causes Twig syntax error

### ISSUE THREAD

**Issue by Leon0824** [bolt/bolt#2934]
In case of a field whose name is end with a '.' (dot), It causes Twig syntax error while accessing the field in templates. Maybe add a filter?

**contenttypes.yml:**
```YAML
fields:
    model-no.:
        label: Model No.
        type: text
        class: narrow
        variant: inline
```

**index.twig:**
```Twig
{{ record.model-no. }}
```

**Comment by bobdenotter** [comment]
Well, `{{ record.model-no. }}` is incorrect twig, there's not much we can do about that. 

My assumption is that bolt _does_ filter that already and it's normalized in the DB as `model-no`, without the '.' and with an underscore instead of a hyphen. This should work:  `{{ record.model_no }}`.

But, to prevent possible confusion or future breakage, I'd advise to fix the contenttype:

```YML
fields:
    model-no.:
        label: Model No.
        type: text
        class: narrow
        variant: inline
```
