### ISSUE TITLE
Allow secondary sorting in "grouping" taxonomy.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2989]
If you have a grouping taxonomy, all records ar sorting to be in the correct group. However, there's no sorting _inside_ the group, which gets messy if you have more than a few: 

![screenshot 2015-03-01 20 16 44](https://cloud.githubusercontent.com/assets/1833361/6432400/6e37ab76-c050-11e4-8a16-3482c5a6fa3d.png)

I propose an extra value, to allow sorting within a group.Something like: 

```yml
chapters:
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    options: { main: "The main chapter", meta: "Meta Chapter", other: "The other stuff" }
    # has_sortorder: true
   sort: title
```

Note: If `has_sortorder` is true, the option for sorting will be ignored.
