### ISSUE TITLE
Using a 'select'-field with values from another contenttype, sorting is ignored.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2991]
See screenshot. It's always alphabetically. 

![screenshot 2015-03-01 20 30 00](https://cloud.githubusercontent.com/assets/1833361/6432426/c2a2410c-c051-11e4-94ba-7bf1ea45139f.png)

I propose a new optional field, to allow sorting on a field of choice: 

```YML
        selectpage:
            type: select
            values: pages/id,title
            label: "Select a page"
            sort: -datepublish
            class: wide
```
