### ISSUE TITLE
Feature: Ability to choose which fields are visible/editable on which templates

### ISSUE THREAD

**Issue by dwolf555** [bolt/bolt#3033]
Useful for `pages` content type. Often creating a few pages for a site you'll have fields that are relevant to only certain templates. Some fields may not even display, depending on the template. I'd like to be able to choose which fields are visible based on template. This will prevent confusion to an end user who is editing content.

**Proposed solution in contenttypes.yml:**

```yaml

pages:
    name: Pages
    singular_name: Page
    fields:
        // i think putting template first would make more 
        // sense since it chooses which fields are visible
        template: 
            type: templateselect
            filter: '*.twig'
            group: content
        title:
            type: text
            class: large
            templates: ['home.twig']
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
            templates: ['*-suffix.twig', 'prefix-*.twig']
        body:
            type: html
            height: 300px
    taxonomy: [ chapters ]
    recordsperpage: 100


```

The default value for the `templates` property will be ['*.twig'], or all. This field will use the same pseudo-regex that the `filter` property uses on template fields. If a field is not relevant to a template as configured, we can simply add the 'hidden' class to the form-group and not display it. It won't require changes to the saving process.

**Other potential solution:**

Another way to do this would be to add a list of relevant fields at the top of the template, using annotations or something. In a case where the configuration gets really complicated, this may help to keep it organized. I don't like this solution as much because it's putting the content type configuration in a bunch of different places.
