### ISSUE TITLE
[extension:boltforms] Is it possible to change form template by default?

### ISSUE THREAD

**Issue by grosslarnakh** [bolt/bolt#3050]
Is where any way to turn on my custom boltforms template instead of boltforms_form.twig? Seems what boltforms.bolt.yml is the best place for doing this.

I need to made some bootstrapping to some forms and I fear what changes what I've made in boltforms_form.twig will be overwritten by default file in the future.

**Comment by GawainLynch** [comment]
Absolutely!

Once you've installed BoltForms, it will create the file `app/config/extensions/boltforms.bolt.yml`… It is not properly documented yet (ooops!), but you can set the following parameters:

```yaml
templates:
  fields: for_bar_fields.twig
  form: for_bar_form.twig
  email: for_bar_email.twig
  subject: for_bar_email_subject.twig
```

The names like `for_bar_fields.twig` can be what ever you want to name them, an in any relative path that Bolt/Twig knows about. For example on my production sites in my template directory I have a directory `theme/gawains_theme/extensions/boltforms/` and in there I keep the BoltForms override templates and would then do something like this:

```yaml
templates:
  form: theme/gawains_theme/extensions/boltforms/for_bar_form.twig
```
