### ISSUE TITLE
[extension:boltforms] Is it possible to send additional parameters to form?

### ISSUE THREAD

**Issue by grosslarnakh** [bolt/bolt#3051]
I've tried 

````
{{  boltforms('formname', { 'attr': {'class': 'foo'} }) }}

````
but it's not working.

**Comment by GawainLynch** [comment]
The Twig function itself is pretty basic:

```twig
{{  boltforms('formname', '<p>html_for_before_the_form</p>', '<p>html_for_after_the_form</p>') }}
```
What I underestimated when I designed BoltForms was how people were going to use it, I mostly assumed that the Twig part would be an example… Pretty dumb of me, hey :grin: 

That aside, it handles/passes all valid Symfony Forms attributes down, so the short example of what you want is this:
```yaml
foo_entry:
  type: text
  options:
    label: Foo's Bar
    attr:
        class: foo
```
