### ISSUE TITLE
Exception when upload directory is defined but missing

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3122]
Adding an `upload:` target to a Contenttype image filed without directory existing causes a Whoops!

```yaml
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
            upload: page_image_directory
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'

```

Result:
![screenshot from 2015-03-13 10 37 12](https://cloud.githubusercontent.com/assets/1427081/6636988/0ebf9e30-c96d-11e4-9830-bb20902bcd10.png)
