### ISSUE TITLE
ContentTypes.yml: Adding a field to group Meta is shown on in an additional Meta tab

### ISSUE THREAD

**Issue by klor** [bolt/bolt#3135]
In contenttypes.yml, I add a field ("bar") to group Meta.

Observed:
* On the editing page (/bolt/editcontent/foo/1), two Meta tabs are now shown (the field "bar" is now shown in an additional Meta tab).
* The title "Meta information" is shown above the "bar" field. I guess this is an additional issue, since everything should be shown below this heading.

Expected:
* On the editing page, all fields in the Meta group are shown on the same tab (one tab only).

contenttypes.yml:

```yaml
foo:
    name: Foo
    singular_name: Foo
    fields:
        ...
        bar:
            type: text
            name: Bar
            group: meta
```

Version 2.0.6
