### ISSUE TITLE
NiceUrls doesn't work

### ISSUE THREAD

**Issue by carlosleopoldo** [bolt/bolt#314]
I have configured and enabled NiceUrls extension, but I'm getting this error when trying to reach the url `site.com/about` 

![Captura de pantalla 2013-03-29 a la s 14 00 26](https://f.cloud.github.com/assets/1787349/318953/654fb6b2-98ab-11e2-8db8-7f9ee9e43666.png)

_config.yml_

```
about:
  from:
    slug: about
  to:
    contenttypeslug: page
    slug: about

about_team:
  from:
    slug: about/team
  to:
    contenttypeslug: page
    slug: team

```
