### ISSUE TITLE
Relations order

### ISSUE THREAD

**Issue by xtrasmal** [bolt/bolt#3155]
Hi everybolty,

I'm dreaming of a world where this is possible:

```yaml
relations:  
   books:
       multiple: true   
       style: tags
```
or

```yaml
relations:  
   books:
       multiple: true   
       style: sortable
```

In this dream world, I can arrange the order in which the relations are displayed...by hand. 
I call it the happy panda dream. 

In the way it is currently set up, I've got to set the order manually and it displays tags.
It's difficult re-arrange stuff, cause you need to remove then first.

So what do you all think? Do I have a valid point?
