### ISSUE TITLE
First item selectfield already filled in

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3203]
When I use a selectfield with multiple items, the first item i already selected when I edit an entry or create a new one. When I save this entry, the system thinks I selected the first item. Is it possible to keep the selectfield empty until I select an item manually?

**Comment by bobdenotter** [comment]
No, you can't unfortunately. What you _can_ do, is add an empty value first: 

```yml
        selectexample:
            type: select
            values: 
                '': '(choose one)
                a-tuin: A-tuin 
                donatello: Donatello
                rafael: Rafael
                leonardo: Leonardo

```
