### ISSUE TITLE
paths always are C:app/view/*

### ISSUE THREAD

**Issue by rkmax** [bolt/bolt#323]
I just installed bolt on my computer and all file CSS/JS paths always are `C:app/view/*`, obviously no load any file and I have no way related to `C:app/view/*`
## Example

![Error show by Chrome dev tools](http://i.imgur.com/4H4I5gD.png)
## installation steps

``` batch
cd c:/Code
git clone https://github.com/bolt/bolt.git local.bolt.example
cd local.bolt.example
composer install
```
## my enviroment settings
- Apache/2.2.23 (Win32)
- PHP 5.3.21
- Windows 8 x64
## vhost settings

``` conf
<VirtualHost *:80>
    DocumentRoot "c:/Code/local.bolt.example"
    ServerAlias local.bolt.example
    <Directory "c:/Code/local.bolt.example">
        Allow from all
        Order allow,deny
        AllowOverride all
        Options Indexes FollowSymLinks
        Options +ExecCGI
    </Directory>
</VirtualHost>
```
## app/config/config.yml

``` yaml
# Database setup. The driver can be either sqlite, mysql or postgres. For
# SQLite, only the databasename is required, while MySQL and PostgreSQL also
# require username, password and perhaps a hostname.
# If you're trying out Bolt, just keep it set to SQLite for now.
database:
  driver: mysql
  databasename: example_bolt
  username: bolt
  password: boltbolt

# The name of the website
sitename: Bolt Example
payoff: The amazing payoff goes here

# The theme to use. Be sure to copy the theme/base-2013 folder, and change the
# name here accordingly. Don't edit the templates in theme/base-2013, because
# they _will_ get updated in next releases
theme: base-2013

# The locale that'll be used by the application. If no locale is set the
# fallback locale is 'en_GB'. For available options, see: http://docs.bolt.cm/locales
locale: es_ES
#timezone: Zulu

# If your site is reachable under different urls (say, both blog.example.org/
# as well as example.org/), it's a good idea to set one of these as the canonical,
# so it's clear which is the primary address of the site. Don't include the
# http:// protocol prefix. Enable the following line to define a canonical url.
canonical: local.bolt.example

# Bolt can insert a <link rel="shortcut icon"> for all pages on the site. Note
# that the location given is relative to the currently selected theme. If you
# want to set the icon yourself, just don't enable the following line.
#favicon: images/favicon-bolt.ico

# The default content to use for the homepage, and the template to render it with.
homepage: page/1
homepage_template: index.twig

# The default content for the 404 page. Uses the 'record_template' template by default.
# Make sure this is set to an existing record, otherwise visitors will get an error-page
# when the request a non-existing page.
notfound: page/not-found

# The default template and amount of records to use for listing-pages on the site.
# Can be overridden for each contenttype, and for each record, if it has a
# 'templateselect' field.
record_template: record.twig

# The default template and amount of records to use for listing-pages on the site.
# Can be overridden for each contenttype.
listing_template: listing.twig
listing_records: 6
listing_sort: datepublish DESC

# Template for showing the search results. If not defined, uses the settings
# for listing_template and listing_records
search_results_template: searchresults.twig
search_results_records: 10

# The list of enabled extensions. For Example:
# GoogleAnalytics, FacebookLike, TwitterButton, FacebookComments, Disqus, RSSFeed, SimpleForms.
# Read each 'readme.md' from the Bolt Extensions screen, to see what they do.
enabled_extensions: [  ]

# Add jQuery to the rendered HTML, whether or not it's added by an extension.
add_jquery: false

# The default amount of records to show on overview pages. Can be overridden
# for each contenttype.
recordsperpage: 10

# template to use for sitemap and sitemap.xml
sitemap_template: sitemap.twig
sitemap_xml_template: sitemap_xml.twig

# The default size of image thumbnails, when using {{ record.image|thumbnail }}
thumbnails: [ 160, 120, c ]

# Show the 'debug' nut in the lower right corner for logged-in user. By default,
# the debugbar is only shown to logged-in users. Use the 'debug_show_loggedoff'
# option to show it to all users. You probably do not want to use this in a
# production environment.
debug: true
developer_notices: false
debug_show_loggedoff: true

# Use strict variables. This will make Bolt complain if you use {{ foo }},
# when foo doesn't exist.
strict_variables: false

# There are several options for giving editors more options to insert images, video,
# etc in the Wysiwyg areas. But, as you give them more options, that means they also have
# more ways of breaking the preciously designed layout. By default the most 'dangerous'
# options are set to 'false'. If you choose to enable them for your editors, please
# instruct them thoroughly on their responsibilty not to break the layout.
wysiwyg:
    images: false
    anchor: false
    tables: false
    fontcolor: false
    align: false
    subsuper: false
    embed: false
    ck:
        #allowedContent: true # Set this to 'true' to allow any elements and attributes in Wysiwg Elements
        #contentsCss: '' # Absolute Path to CSS File on Server because it's loaded by JavaScript stylesheetparser
        filebrowserWindowWidth: '480'
        filebrowserWindowHeight: '480'
    filebrowser:
        browseUrl: /bolt/filebrowser/pages
        #imageBrowseUrl: ''
        #uploadUrl: ''
        #imageUploadUrl: ''

# Bolt allows some modifications to how 'strict' login sessions are. For every option
# that is set to true, it becomes harder for a bad-willing person to spoof your login
# session. However, it also requires you to re-authenticate more often if you change
# location(ip-address) or your browser has frequent upgrades. Only change these if
# you know what you're doing, and you're having issues with the default settings.
# note: if you change any of these, all current users will automatically be logged off.
cookies_use_remoteaddr: true
cookies_use_browseragent: false
cookies_use_httphost: true
cookies_https_only: false # note: this is on the TODO list.

# The length of time a user stays 'logged in'. Change to 0 to end the session when the browser
# is closed. The default is 1209600: two weeks in seconds.
cookies_lifetime: 1209600

# Set the session cookie to a specific domain. Leave blank, unless you know what you're doing.
# When set incorrectly, you might not be able to log on at all.
# If you'd like it to be valid for all subdomains of 'www.example.org', set this to '.example.org'.
cookies_domain:

# The hash_strength determines the amount of iterations for encrypting passwords. A higher number means
# a harder to decrypt password, but takes longer to compute. '8' is the minimum, '10' is the default,
# '12' is better.
hash_strength: 10

```
