### ISSUE TITLE
CKEditor isn't included in templatefields if there isn't a HTML field for the content type

### ISSUE THREAD

**Issue by EJanuszewski** [bolt/bolt#3250]
### Will work

app/config/contenttypes.yml
```
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ chapters ]
    recordsperpage: 100
```
theme/themename/config.yml
```
templatefields:
    index.twig:
        section_1:
            type: html
            label: Section 1
        section_2:
            type: html
            label: Section 2
```

### Won't work

app/config/contenttypes.yml
```
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ chapters ]
    recordsperpage: 100
```
theme/themename/config.yml
```
templatefields:
    index.twig:
        section_1:
            type: html
            label: Section 1
        section_2:
            type: html
            label: Section 2
```

<strong>- Note the missing html field in the contenttype, I believe this is what causes the issue</strong>
