### ISSUE TITLE
[RFC] List/Repeating Field Spec

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3267]
**TLDR;** I would like to make list fields happen.

This is an attempt to bring together the discussions around this topic, propose a method of accomplishing it, and to re-open the concept up for discussion.

Related issues/discussions: #1420 #1843 #2261 

People have brought up implementing libraries such as [Sir Trevor](http://madebymany.github.io/sir-trevor-js/) but I think that we should roll our own implementation. The most obvious concern is that Sir Trevor looks, feels and operates completely different to how Bolt does. Yes with some CSS we can style it ourselves and with some Javascript we can put in all of the hooks but in the end you're putting an awful lot of effort to re-create something our application can already do. The current fields just need to be given some more superpowers and magic, and after that the sky is the limit. Leveraging what we've already got means that adding new field won't complicate things, and extensions that add new fields will be able to be leveraged as well.

Onto the design.

## Design

I am proposing two distinct kinds of lists here, a dead simple one and one that allows for more complexity. Funnily enough, I think the dead simple one will be more difficult to implement.

### Simple Lists

**Simple lists** allow you to flag a single field as repeatable, and give a limit to how many may be added. These are stored and accessed as arrays of whatever kind of data the original field was.

#### Defining

These will be defined by appending a `limit` value to a field definition in a contenttype. By default, this value is set to `1`, so a field cannot be repeated. Setting it to an integer above 1 will allow that many fields in the list, and setting it to `0` will allow for as many items as the machine will allow.

If some people are obsessed with semantics, we could make the keyword `none` the same as `0` to say *there is no limit*.

```yml
staff:
    singular_slug: employee
    fields:
        capabilities:
            type: text
            limit: 3 # Can only list a maximum of 3 capabilities
        pets:
            type: text
            limit: 0 # These staff can have as many pets as they want
        name:
            type: text
            limit: 1 # This is superfluous, limit is 1 by default but it means the field can't repeat
```

#### Accessing in templates

Easy!

```twig
{% for capability in employee.capabilities %}
    {{ capability }}
{% endfor %}
```

#### UI in backend

Forgive my 5 minute mockups

![image](https://cloud.githubusercontent.com/assets/3238878/6864431/fd046716-d4c5-11e4-8d1c-7a6349ebfc0a.png)

A simple extension of each field type where it is shrunk on the right side to make room for a delete and dragging handle, and a new field button at the top.

There's probably a use-case for a duplicate handle as well.

### Repeating Blocks

This is where more complexity comes in, but probably more ease in implementation. This allows you to specify one or more sets of fields, like you would a contenttype, to repeat again and again. In terms of storing data, there are useful implications but I'm excited for this feature to use as long-form content, breaking free of the bounds of CKEditor to make interesting pages.

Yes, heavily inspired by [Craft CMS' matrix content](https://buildwithcraft.com/features/matrix) and later by Sir Trevor.

#### Defining

This is an entirely new fieldtype, `list` that has an option called `items` 

```yml
pages:
    fields:
        content:
            type: list
            item_limit: 20 # This is optional
            items:
                image:
                    fields:
                        image:
                            type: image # Yikes thats a lot of indents
                blockquote:
                    label: Block Quote
                    fields:
                        quote:
                            type: html
                        citation:
                            type: text
```

It speaks for itself, but it does get a bit unweildy and things would get complicated if you want to allow for identical sets of list fields inside other list fields - could probably get by with some YAML inheritance but that isn't super obvious to everyone.

So I'm also proposing a method of defining blocks to use in `config.yml`

```yml
list_blocks:
    image:
        fields:
            image:
            type: image
    blockquote:
        label: Block Quote
        fields:
            quote:
                type: html
            citation:
                type: text
```

Then if you supply an array of strings in your list field definition, it will read from list blocks

```yml
pages:
    fields:
        content:
            type: list
            item_limit: 20 # This is optional
            items:
              - image
              - blockquote
```

It also makes it fairly straight forward to have say, a 'section' type that can have more list fields inside it

```yml
list_blocks:
    image:
        fields:
            image:
            type: image
    blockquote:
        label: Block Quote
        fields:
            quote:
                type: html
            citation:
                type: text
    section:
        fields:
            colour:
                type: text
            content:
                type: list
                items:
                  - image
                  - blockquote
```

Defining blocks in `config.yml` will also stop many identical, but not defined in the same place, contenttype arrays clogging up memory which is a bonus.

**Question:** Should we allow to define the blocks in two areas or just one (in config or in contenttypes)?

**Potential syntactic sugar** for repeating one kind of block only, use `item` instead of `items`

```yml
section:
    type: list
    item:
        image:
            type: image
        heading:
            type: text
```

#### Accessing in templates

Slightly more complex, but still easy

```twig
{% for block in content %}
    {% set type = block.getSlug() %} {# The variable `slug` is commonly used so we need to find a different way to access the definition of this #}
    {% if type == 'image' %}
        {{ whatever }}
    {% elseif type == 'blockquote' %}
        {{ yeahsure }}
    {% endif %}
{% endfor %}
```

#### UI in backend

![image](https://cloud.githubusercontent.com/assets/3238878/6864529/66745a84-d4c7-11e4-95cb-a2cb4fa35d4e.png)

Now there are a lot of ways to do this. I've opted for putting every block in a little block that you can drag around and collapse. I see a problem being that any of these fields could end up with quite a lot of fields in them depending on how customisable you want things to get.

One option could be to use modals. That way, if your block has a lot of fields they'll never get in the way and will be treated pretty well. Gets a bit iffy with lists inside lists so I'm not a fan.

There is definitely a use case for tabs here, or maybe one or more collapsible sets of fields in there. These are things that the feature doesn't need to launch with and will be good to gauge use cases for.

## Implementation

I'm proposing this feature land in Bolt 2.3, and I'm very happy to take that on.

The first "dead simple" kind is near impossible to reliably implement with our current storage/content layer. As the new system will expose the logic of every field, managing that will be far easier. I don't think, though, that this part should be in 2.3 but 2.4 rather, a release after the new storage if (planned to be) out. This is just a simpler and more efficient version of the list field type so I would count it as a lower priority.

The second kind, which I am more excited about, shouldn't be too difficult to implement. The template refactoring in #3229 makes it much easier to store array-like fields based on other field types. 

### JS Refactoring

Original issue: #2781 
I've updated that issue and will not clog this with even more content

### Storage

I know nothing, [leave it to the experts](https://github.com/bolt/bolt/wiki/Bolt-2.x-Refactoring).

~~I'm in favour of storing it all as JSON encoded fields because I'm a big fan of a 1:1 ratio for contenttypes:tables and records:rows. It makes it so much easier for moving data around and it isn't a headache to look at. In my eyes, this only restricts methods of searching and retrieving data. I understand that the latter would be a concern for some people, but they might want to look towards using relationships or writing an extension for the more advanced functionality, or we define a standardised method of storing values in other tables.~~

~~I think if other values are going in other tables, it should be done in a transparent way where the developer is aware when its happening. Defaulting to it is not transparent.~~

### To extension or not to extension

I think this should be in core because it's a heavily requested feature and people - intentionally or subconsciously - work around the lack of features like this. Designers and developers want to empower their editors to create great things, and the lack of repeating content hurts that ability in quite a few ways. I'm mainly thinking of long form content but there are plenty more use cases than that.

It will also open things up for extension more. Someone could turn the repeating content field into a fully blown Mailchimp style wysiwyg page editor. I would consider that extension material, definitely.

I think the 'dead simple' kind of list field is pretty damn difficult to introduce as an extension and I don't know how you'd make all of the functionality it needs to changed that pluggable. 

Regardless, refactoring needs to happen either way. If this was an extension, there would most likely be areas that need to be made more extendable before even the list field type could land.

Jeepers, that got long. Enjoy!
