### ISSUE TITLE
Adding a "Styles" combo to HTML field's CKeditor

### ISSUE THREAD

**Issue by JeromeBreizhtorm** [bolt/bolt#3297]
I'd like to achieve that : 
http://docs.ckeditor.com/#!/guide/dev_styles

but faces a few problems/questions :

First i understand that i have to add a styleSet to my ckeditor field configuration : 
```
body:
            type: html
            height: 300px
            options:
                ckeditor:
                    stylesSet: 'page_styles:path/to/some/styles.js'
```

**Where do i put this JS file ?**
 * in my theme : why not even if configuration shouldn't rely on themes. And when the app is running in a subdir (like mine), you can't rely on an absolute path (unless there is some kind of PATH var i can use in conf files ??). So i can get it to work with something like (which is ugly) : 
  ```
  stylesSet: 'page_styles:../../../../theme/mytheme/js/ckeditor/ckeditor_styles.js'
  ```
 * in app/view/js, so it is readable : but it will be overwritten in the next Bolt update.

Anyway, once it's done, the Styles Combo Plugin should be activated for my styles to be loaded and displayed in CKeditor, as it's not part of the package for the moment.

**How do i load a plugin into Bolt CKEditor ?**
I tried using CKEDITOR.plugins.addExternal and CKEDITOR.config.extraPlugins in the previous path/to/some/styles.js (and the CKeditor object seams fine in the output), but still can't see anything in the editor...

Thanks
