### ISSUE TITLE
gets disconnected after few seconds

### ISSUE THREAD

**Issue by medisfar** [bolt/bolt#3298]
An exception has been thrown during the rendering of a template ("You must be logged in to use this.") in "dashboard/_aside.twig" at line 25.

**Comment by bobdenotter** [comment]
Hi, have you made modifications to this section of config.yml? 

```yml
# Bolt allows some modifications to how 'strict' login sessions are. For every option
# that is set to true, it becomes harder for a bad-willing person to spoof your login
# session. However, it also requires you to re-authenticate more often if you change
# location(ip-address) or your browser has frequent upgrades. Only change these if
# you know what you're doing, and you're having issues with the default settings.
# note: if you change any of these, all current users will automatically be logged off.
cookies_use_remoteaddr: true
cookies_use_browseragent: false
cookies_use_httphost: true

# The length of time a user stays 'logged in'. Change to 0 to end the session when the browser
# is closed. The default is 1209600: two weeks in seconds.
cookies_lifetime: 1209600

# Set the session cookie to a specific domain. Leave blank, unless you know what you're doing.
# When set incorrectly, you might not be able to log on at all.
# If you'd like it to be valid for all subdomains of 'www.example.org', set this to '.example.org'.
cookies_domain:

# If your system is using a custom session configuration (such as a redis handler from a
# PHP extension) then we need to disable our session storage handler. In that case, set
# this setting to false. Do not change this, unless you know what you're doing!
# See: http://silex.sensiolabs.org/doc/providers/session.html#custom-session-configurations
session_use_storage_handler: true
```
