### ISSUE TITLE
Can't set dynamic route requirements in an extension

### ISSUE THREAD

**Issue by mattvick** [bolt/bolt#3366]
Can't add a dynamic route requirement to a Bolt route.

I'm defining my route as follows:

```yaml
formpages:
    path: '/{contenttypeslug}/{slug}'
    defaults:
        _controller: 'Bolt\Extension\Mahango\Forms\Extension::record'
    requirements:
        contenttypeslug: 'page'
        slug: 'Bolt\Extension\Mahango\Forms\Extension\Routing::getSlugRequirement'
    method: 'GET|POST'
```

This needs to be defined in `routing.yml` because if I use `$app->match()` in my extension the route is added with the lowest priority and I need it to be above the core `contentlink` route.

In my `getSlugRequirement()` method I want to query the database to get a subset of page records but I don't have access to the `$app` var when the method is being called.

I've looked at the core code and tried to use `$app->mount('', new Bolt\Extension\Mahango\Forms\Extension\Routing());` in my `bootstrap.php` but here the extension hasn't yet been initialised. It seems like whichever angle I come at this I don't ave access to the other side.

Is this a limitation of extensions?

How can I do get this to work?
