### ISSUE TITLE
/bolt/overview/:contentype Undefined index: datepublish DESC

### ISSUE THREAD

**Issue by rkmax** [bolt/bolt#343]
i have the following `contentypes.yml` file

``` yaml
entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        video:
            type: video
        body:
            type: html
            height: 300px
    relations:
        entries:
          multiple: false
          order: title
          label: Select a page
    taxonomy: [ categories, tags ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    sort: datepublish DESC
    recordsperpage: 10

testimonial:
    name: Testimonios
    singular_name: Testimonio
    fields:
        body:
            type: html
            height: 150px
        who:
            type: text
    taxonomy: [ chapters ]
    recordsperpage: 10
    sort: datepublish DESC
```

when insert second `testimonial` record I get `Undefined index: datepublish DESC` from Bolt/Storage in line 1369 when go to http://host/bolt/overview/testimonios

``` php
     // ...
     $second_sort = $a->contenttype['sort'];
     if ($a->values[$second_sort] == $b->values[$second_sort]) {
                return 0;
            } else {
                return ($a->values[$second_sort] < $b->values[$second_sort]) ? -1 : 1;
            }
        }
     // ...
```

now the problem here is because `$second_sort` is equal to `datepublish DESC` and must be `datepublish`. I'm looking where's the problem. if can help me :+1:
