### ISSUE TITLE
Content list in backend grouped incorrectly when sort specified on content type with taxonomy

### ISSUE THREAD

**Issue by caseyamcl** [bolt/bolt#3437]
I am seeing a weird issue in the administrative interface with a content type that contains a sort parameter, and has a taxonomy related to it.

Here's the the contenttype definition:

```yaml
softwaredocs:
    taxonomy: [ systems, swcategories ]
    default_status: publish
    sort: title
    fields:
        title:
            type:     text
            label:    Package Name
            class:    large
            required: true
        slug:
            type: slug
            uses: title
        homepage:
            type:    text
            label:   "Homepage Link (URL)"
            pattern: url
        version:
            label:    Version
            type:     text
            class:    narrow
        summary:
            label:    Summary
            type:     text
            postfix:  "Provide a one-line summary of what the software package is"
        body:
            label:    Body
            type:     html
```

And attached if what I see in the admin interface.  Notice that each taxonomy is listed multiple times.  If I remove either the `sort` or `taxonomy` attributes from the definition, everything works correctly.

![screenshot from 2015-04-23 13 52 02](https://cloud.githubusercontent.com/assets/53035/7303623/f47d5cce-e9bf-11e4-9c2c-3dcf865a8e88.png)
