### ISSUE TITLE
[RFC] Choose the admin title of a contenttype

### ISSUE THREAD

**Issue by davidgenetic** [bolt/bolt#3452]
I've bumped into a situation where the generated content's title in the administration area was not fitting for some reason. Instead of forcing people to use reserved field names like 'title', 'name', 'caption' or 'subject', it would be nice we could choose the field or format ourselves.

I've prepared a little commit (9b87931ff458b5209c5d59db4c717e6b9826bf82) where I've made the following possible:
```yaml
pages:
    singular_name: page
    fields:
        title:
            type: text
        subtitle:
            type: text
    title_format: "{{ record.title }} - {{ record.subtitle }}"
```
I can make a pull request if you think this is ok.
