### ISSUE TITLE
Boltforms/ContentType and Date field type

### ISSUE THREAD

**Issue by leocavalcante** [bolt/bolt#3459]
I was getting `Catchable fatal error: Object of class DateTime could not be converted to string` if a form field of type birthday linked to an ContentType field of type date.

The solution was:

**Bolt\Content.php below line 287**
```php
if ($this->values[$key] instanceof \DateTime) {
    $this->values[$key] = $this->values[$key]->format('c');
}
```

**Bolt\Extension\Bolt\BoltForms\Database.php below line 81**
```php
if ($value instanceof \DateTime) {
    $savedata[$key] = $value->format('c');
}
```
Not sure if is the best solution, but solved to me.

**Comment by bobdenotter** [comment]
Hi @leocavalcante,

Could you give a bit more information about what you were doing, that caused these errors? I _think_ your solution won't cause any side-effects, but we'd need to test those out.

**Comment by leocavalcante** [comment]
Sure!

To reproduce just link a Boltforms to a ContentType with a date/datetime type field:

**contenttypes.yml:**
```yaml
form_requests:
  name: Form Requests
  singular_name: Form Request
  fields:
    title:
      type: text
    date:
      type: date
    file:
      type: file
```

**boltforms.bolt.yml:**
```yaml
form_request:
  database:
    contenttype: form_requests
  fields:
    title:
      type: text
    date:
      type: date
    file:
      type: file
    submit:
      type: submit
```

**index.twig**
```twig
{{ boltforms('form_request') }}
```

Try to submit a request and got:
```
Catchable fatal error: Object of class DateTime could not be converted to string in C:\apache\htdocs\bolt-issue\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php on line 91
```

I added a file type cause I think it wont will link properly to. Just as headsup.
At the end I created a extension to handle my form request on my actual project.

Changing to table:
```yaml
form_request:
  database:
    #contenttype: form_requests
    table: bolt_form_requests
```
Doest not resolve, both `Bolt\Storage->insertContent()` and `Bolt\Extension\Bolt\BoltForms\Database->writeToTable()` are not handling different kinds of type.
