### ISSUE TITLE
FontSize and Font Family in Ckeditor 

### ISSUE THREAD

**Issue by oazet** [bolt/bolt#3630]
How to add select FontSize and Font Family in Ckeditor Bolt cms?

Used bolt cms version cms 2.2

**Comment by GawainLynch** [comment]
In your [`app/config/config.yml`](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L278-L296) file you will see this section:
```yml
wysiwyg:
    images: false
    anchor: false
    tables: false
    fontcolor: false         # Allow users to mess around with font coloring.
    align: false             # Add 'align left', 'align right',etc.
    subsuper: false          # Add buttons for subscript and superscript, using <sub> and <sup>
    embed: false             # allows the user to insert embedded video's from Youtube, Vimeo, etc.
    underline: false         # add a button to underline text, using the <u>-tag.
    strike: false            # add a button to add stikethrough, using the <s>-tag.
    blockquote: false
    codesnippet: false
    specialchar: false       # adds a button to insert special chars like '€' or '™'.
    ck:
        allowedContent: true # If set to 'true', any elements and attributes are allowed in Wysiwg Elements
        autoParagraph: true  # If set to 'true', any pasted content is wrapped in <p> tags for multiple line-breaks
        disableNativeSpellChecker: true # If set to 'true' it will stop browsers from underlining spelling mistakes
        allowNbsp: false     # If set to 'false', the editor will strip out `&nbsp;` characters. If set to 'true', it will allow them. ¯\_(ツ)_/¯
        # viewSourceRoles: [ 'admin', 'developer' ] # the roles which are allowed to use the [Source]-button.
```

You can set font colours there. For font family, that is something you control in a template with your CSS.
