### ISSUE TITLE
Template specific select field does not save

### ISSUE THREAD

**Issue by hydrospell** [bolt/bolt#3675]
## Bug Summary

Select fields defined under Template Specific Fields do not save. 

## Specifics

Select fields under Template Specific Fields render fine in the backend, but selected values do not save. i.e. `record.templatefields.my_selectfield` shows up blank and upon returning to the same editor page or reloading, the select field renders fine but shows that no value is selected. 

## Steps To Reproduce

Create a `select` field type in a Theme's `config.yml`. Here's a sample:

```
templatefields:
    page-process.twig: # Our homepage template
        proj_modules:
            label: "Project Modules"
            type: select
            values: project_image_modules/id
            keys: slug
```

Then, edit a page with this Template and try to save after selecting a value for this Field. Reload the editor page or try to output the selected value using `record.templatefields.proj_modules`. 

_"Steps to reproduce"--has anyone made inappropriate jokes about this before? (sorry.)_

## Expected Result

Selected value for this select field should be saved. 

## Actual Result

Selected value is not saved. 

## Additional Notes

Upon hitting Save, the POST request that goes out does include the field and selected value in question, so the backend's frontend should not be the cause of this problem.
