### ISSUE TITLE
Possibility to add a list of records dynamically in a menu 

### ISSUE THREAD

**Issue by benjbdev** [bolt/bolt#372]
Hello,

I would to know if it's possible to add some records dynamically in a menu 

```
main:
  - label: Home
    path: homepage
  - label: Records
    path: records/
    submenu:
      - (here a dynamic list of records)
```

Thanks !
