### ISSUE TITLE
[BUG] Users that have delete or publish permissions are unable to do so until they also have the edit permission

### ISSUE THREAD

**Issue by bnelson-cainc** [bolt/bolt#3802]
I'm using Bolt 2.2.4, installed via git; I'm using Chrome version 43.0.2357.132 (64-bit); also tested in Safari 8.0.5 (10600.5.17).

I've defined a couple of new roles, editor-admin and qe.  For the former, I wanted this role to be able to delete records; for the latter, I wanted qe to be able to publish/depublish.  Here's the relevant section from our `permissions.yml` file:
```yaml
contenttype-all:
    edit: [ developer, admin, exec-editor, editor-admin, contributor, qe ]
    create: [ developer, admin, exec-editor ]
    publish: [ editor-admin, admin, exec-editor, qe ]
    depublish: [ editor-admin, admin, exec-editor, qe ]
    delete: [ editor-admin, developer, admin ]
    change-ownership: [ editor-admin, developer, admin ]

contenttype-default:
    edit: [ editor, owner, editor-admin ]
    create: [ author ]
    change-ownership: [ owner, editor-admin ]
    view: [ anonymous ]
```
As you can see editor-admin and qe both have edit; editor-admin doesn't need it, and probably shouldn't have it, but it's something we can live with for now.  However, qe absolutely shouldn't be able to edit content, but they can't see the publish or depublish menu items in the GUI until I also give them edit.
The problem seems to be that if you don't enable edit, then the edit button part of the menu isn't shown, which is correct, but if you click on the pulldown arrow, no operations are listed either (just info).

Steps to reproduce:

Edit this part of the `permissions.yml` file to be like:
```yaml
contenttype-all:
    edit: [ developer, admin, exec-editor, contributor ]
    create: [ developer, admin, exec-editor ]
    publish: [ editor-admin, admin, exec-editor, qe ]
    depublish: [ editor-admin, admin, exec-editor, qe ]
    delete: [ editor-admin, developer, admin ]
    change-ownership: [ editor-admin, developer, admin ]

contenttype-default:
    edit: [ editor, owner ]
    create: [ author ]
    change-ownership: [ owner, editor-admin ]
    view: [ anonymous ]
```
Ensure an existing page is created in Bolt.
Log in with either editor-admin or qe role.
Click on Pages -> View Pages

Expected Result:
User has the ability to perform various other operations such as delete or publish the page, depending on the role(s) the user has associated with their username.

Actual Result:
The pulldown arrow is present, but no operations are listed inside, so the user is unable to do anything at all to the page.
