### ISSUE TITLE
Can't use relation fields in title_format

### ISSUE THREAD

**Issue by philbates35** [bolt/bolt#3849]
I would like to be able to use a field from one of my content type's relations in it's admin title (set with the `title_format` config).

Use case: I have a `repeating_events` content type, and a `repeating_event_instances` content type. Each `repeating_event` is linked to many `repeating_event_instances`. Each `repeating_event_instance` has a single `date` field, and it is linked to a single `repeating_event`.

I would like the admin screen to display like the following example:

```
01/01/2015 - Repeating Event 1
02/01/2015 - Repeating Event 2
08/01/2015 - Repeating Event 1
```

I've had a quick look in the source, and it seems that it `title_format` you can only pass the field names of the fields of the content type in question. Meaning that it is currently only possible for my admin screen to look like this:

```
01/01/2015
02/01/2015
08/01/2015
```

I'm sure you can see how this would be confusing to the user.

I envisage the updated `title_format` to allow you to do something like this:

```
repeating_event_instances:
    name: Repeating Event Instances
    singular_name: Repeating Event Instance
    title_format: [ date, relations.repeating_events.name ]
    fields:
        date:
            type: date
            required: true
    relations:
        repeating_events:
            multiple: false
            label: Select a repeating event
            order: name
```

Let me know what you think!

Thanks.

**Comment by Pinpickle** [comment]
May I suggest writing a [custom content class](https://docs.bolt.cm/extensions/essentials#overriding-default-8216content8217-class)? I have done something very similar with title logic, it shouldn't be too hard to accomplish what you want (this is not tested)

```php
class RepeatingEventInstance extends \Bolt\Content {
    public function getTitle()
    {
        $relatedEvents = $this->related('repeating_events');
        $relatedEvent = $relatedEvents[0];
        
        return $this->values['date'] . ' - ' . ($releatedEvent ? $relatedEvent->values['name'] : 'Unknown Event');
    }
}
```

And in your `contenttypes.yml`

```yml
repeating_event_instances:
    # All of your stuff
    class: \Your\Namespace\RepeatingEventInstance
```
