### ISSUE TITLE
Unable to edit entry with owner permission

### ISSUE THREAD

**Issue by iMaxxx** [bolt/bolt#3909]
I'm unable to edit entries using the 'owner' permissions. Following an example...
Editing is only possible with Admin and User1
I can open the test page on back end and can see the edit button for all entries where I'm the owner. But when I press on it I get forwarded to overview page an get the error access denied.

#### Users
>№ 1 Admin root
>№ 2 User1 chief-editor
>№ 3 	User2 test-editor

#### permissions.yml
```yaml
roles:
     test-editor:
        label: Inhalte-Editor
    chief-editor:
        description: This user can edit any content in the system.
        label: Chef-Editor
    admin:
        description: User-level administrator.
        label: Administrator
    developer:
        description: Developer access. Only required to change system-level settings.
        label: Entwickler
    guest:
        description: This user can log on, but is not allowed to edit any content.
        label: Gast Editor

roles-hierarchy:
    manipulate:
        admin: [ ]
        developer: [ admin ]
        chief-editor: [ admin, developer ]
        guest: [ admin, developer ]
        test-editor: [ admin, developer ]

global:
    about: [ admin ] # view the 'About Bolt' page
    clearcache: [ admin, developer ]
    contentaction: [ admin, developer ]
    dashboard: [ everyone ]
    dbcheck: [ admin, developer ]
    dbupdate: [ admin, developer ]
    dbupdate_result: [ admin, developer ]
    extensions: [ developer ]
    extensions:config: [ developer ]
    fileedit: [ admin, developer ]
    files:config: [ developer ]
    files:theme: [ developer ]
    files:uploads: [ admin, developer, verwalter,chief-editor ]
    files: [ admin, developer,verwalter]
    prefill: [ developer ]
    profile: [ everyone ] # edit own profile
    settings: [ admin, developer, everyone ]
    translation: [ developer ]
    useraction: [ admin, developer,verwalter ] # enable/disable/delete
    useredit: [ admin, developer,verwalter ] # user settings
    users: [ admin, developer,verwalter ] # view user overview
    roles: [ admin, developer ] # view the roles overview
    maintenance-mode: [ everyone ] # view the frontend when in maintenance mode
    omnisearch: [ everyone ]
    # Access to the various logs
    changelog: [ admin, developer ]
    systemlog: [ admin, developer ]
    # The following permissions are particularly important: login and postLogin
    # determine who may see and use the login form. If you set them to anything
    # but 'anonymous', only users will be able to log in that are logged in
    # already, which is probably never what you want.
    login: [ anonymous ]
    postLogin: [ anonymous ]
    # Likewise, 'logout' needs to be granted to 'everyone', otherwise people
    # cannot log out anymore.
    logout: [ everyone ]

contenttype-all:
    edit: [ developer, admin ]
    create: [ developer, admin ]
    publish: [ developer, admin ]
    depublish: [ developer, admin ]
    view: [ developer,admin ]
    delete: [ developer, admin ]
    change-ownership: [ developer, admin ]

contenttype-default:
    edit: [ owner,admin ]
    create: [ admin ]
    change-ownership: [ admin ]
    view: [ anonymous ]
    publish: [ admin ]
    depublish: [ admin ]
    change-ownership: [ admin ]

contenttypes:
    test:
        edit: [ admin,owner ]
        create: [ admin, test-editor]
        publish: [ admin ]
        depublish: [ admin ]
        delete: [ admin ]
        view: [ admin, test-editor ]
        change-ownership: [ admin]
```
