### ISSUE TITLE
Add a target option in Menu Yaml Config

### ISSUE THREAD

**Issue by dadaxr** [bolt/bolt#3964]
The title speaks for itself :)

But a sample : 
```yaml
header:
    - label: external link
      link: http://www.external-link.com/
      target: _blank
      class: first
```

**Comment by dadaxr** [comment]
Oops ... it's allready possible and just use that option in the menu template ...

Just a sample for those who were asking the same : 

in the menu.yml : 
```
header:
    - label: External Link
      link: http://www.my-external-link.com/
      target: _blank
      class: first
```

and in the _sub_menu.twig ( which is the default template called by the  {{ menu('header') }} twig function 

```
<a href="{{ item.link }}" 
       {% if item.title is defined %}title="{{ item.title|escape }}"{% endif %}
       {% if item.target is defined %}target="{{ item.target|escape }}"{% endif %}
       class="{% if item|current %}current {% endif %}{% if item.class is defined %}{{item.class}}{% endif %}">
       {% if item.label is defined %}{{item.label}}{% else %} - {% endif %}
    </a>
```
