### ISSUE TITLE
Use a different slug for database tables and urls

### ISSUE THREAD

**Issue by helderco** [bolt/bolt#397]
Hi,

I have a content type like this:

``` yaml
agencies:
    name: Travel Agencies
    singular_name: Travel Agency
    fields:
        [...]
```

But when trying to update the database tables, it gets rewritten to `bolt_travel-agencies` which produces an error.

**SQLite**

``` sql
CREATE TABLE bolt_travel­-agencies (id INTEGER NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME NOT NULL, username VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, PRIMARY KEY(id))
```

An exception occurred while executing 'CREATE TABLE bolt_travel­-agencies (id INTEGER NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME NOT NULL, username VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, PRIMARY KEY(id))': SQLSTATE[HY000]: General error: 1 near "-­": syntax error

**MySQL**

``` sql
CREATE TABLE bolt_travel­-agencies (id INT UNSIGNED AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME NOT NULL, username VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
```

An exception occurred while executing 'CREATE TABLE bolt_travel­-agencies (id INT UNSIGNED AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME NOT NULL, username VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '­-agencies (id INT UNSIGNED AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, ' at line 1

---

Even if I add:

``` yaml
agencies:
    name: Travel Agencies
    singular_name: Travel Agency
    slug: travel_agencies
    singular_slug: travel_agency
```

It still makes the table names as `bolt_travel-agencies`.

I would expect that for table names I would have `bolt_travel_agencies` while on URLs `/travel-agencies/[...]`.

How can I have a multiple word name for a content type?
