### ISSUE TITLE
Taxonomy sort ordering on default listing pages incorrect

### ISSUE THREAD

**Issue by tompato** [bolt/bolt#3977]
So I have a content type setup in 'contenttypes.yml' with a taxonomy and no sorting value set and then you setup the taxonomy as follows:
```yml
staff_position:
    name: Staff Position
    slug: staff_position
    behaves_like: grouping
    options: { head: "Head", dept: "Department Head", teacher: "Teacher", other: "Misc" }
    has_sortorder: true
```
When visiting the listing page for that content type which is merely looping around the records such as `{% for record in records %} Do stuff {% endfor %}` it does not apply the custom ordering and will only list them in the order they were created (newest first), despite the sort order and taxonomy values being set correctly when dumping the records that are returned.

If you add a simple `{% setcontent records = 'contenttype' %}` at the start of the listing template then it suddenly applies the sorting order correctly. Although this is sort of a fix, it makes the pagination stuff break obviously, so it's not ideal.

A few things to note:
* The presence of a pager or not seems to have no effect
* Removing all records in the taxonomy table and starting again made no difference
* Applying the taxonomy with only one option as mentioned above makes no difference
* The content type definitely has no sort value set in content types.yml

And the kicker - The back-end view seems to work fine in applying the custom sort ordering and filtering.

P.S  - yes many caches were cleared :hatching_chick: :hatched_chick:
