### ISSUE TITLE
Pagination has incorrect canonical

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3995]
I have a listing of a content type that doesn't have individual pages - that means that the listing page is how one would access all of the content.

I have created the route in `routing.yml`

```yaml
bookspage:
    path: '/books'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::listing'
        contenttypeslug: books
```

And if I go to `http://mysite/books?page=2`, I get the second page *but* the canonical does not have the page query string in it.

```html
<link rel="canonical" href="//mysite/books">
```

I'm aware there may be some debate as to whether the query string should be added in all cases... I'm not sure myself. I'd appreciate if someone could point me towards a workaround because search engines indexing the pages as unique is important. As a last resort, I'd disable the canonical.
