### ISSUE TITLE
Templatefields flawed/broken by design?

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4004]
Currently we document/highlight templatefields as given the example in [base-2014](https://github.com/bolt/bolt/blob/master/theme/base-2014/config.yml#L36-L45):

```yaml
templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
```

However, the are stored in the database as:
```json
{
    "section_1" : "foo",
    "section_2" : "bar",
    "image" :  {
        "file" : "file.jpg"
    }
}
```

That taken into account if you define:
```yaml
templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
    otherfield.twig:
        section_3:
            type: text
            label: Section 1
        section_4:
            type: html
            label: Section 2
        file:
            type: file
```

The fields associated with `otherfield.twig` are completely ignored, and we have zero backwards compatible ways of fixing this.

We also have [non-existing function calls](https://github.com/bolt/bolt/blob/release/2.2/src/Content.php#L409) to resolve template field data.

Anyone have suggested approaches?

**Comment by bobdenotter** [comment]
I think it might be not this big of an issue, and it _might_ just be a mixup with labels.. for example, if i do this: 

```YML
templatefields:
    extrafields-a.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: text
            label: Section 2
        image:
            type: image
    extrafields-b.twig:
        section_3:
            type: text
            label: Section 3
        section_4:
            type: text
            label: Section 4
        section_5:
            type: html
            label: Section 5
        file_1:
            type: file
```

Pages with `extrafields-a.twig` and `extrafields-b.twig` work both as expected.. See screenshot: 

![screen shot 2015-08-22 at 19 23 45](https://cloud.githubusercontent.com/assets/1833361/9425076/77d8da7e-4903-11e5-8da3-349132ccb3be.png)


![screen shot 2015-08-22 at 19 22 51](https://cloud.githubusercontent.com/assets/1833361/9425077/7dd85620-4903-11e5-91fb-8dbb138af85a.png)

And, they both get stored in the DB as they should: 

![screen shot 2015-08-22 at 19 24 21](https://cloud.githubusercontent.com/assets/1833361/9425079/932003a2-4903-11e5-9d0f-b06d1676a0f1.png)

**Comment by GawainLynch** [comment]
Unsure… mine is  a fresh pull of `release/2.2` and new set up.

**Comment by bobdenotter** [comment]
This was on my "working on release/2.2" version. Up to date with that branch. Will try a fresh 2.2.8 install.

**Comment by GawainLynch** [comment]
HEAD would be the best bet… Maybe it is something new… Not sure how though.

**Comment by bobdenotter** [comment]
Did a fresh 2.2.8 install, and it works too: 

![screen shot 2015-08-22 at 19 37 17](https://cloud.githubusercontent.com/assets/1833361/9425134/3ef9ceb4-4905-11e5-91a4-477bc9915055.png)

@GawainLynch One thing that's slightly weird in the UI, is that you have to set the template, then save, **and then** refresh the page to see the new template fields.. sure you've done that?

**Comment by bobdenotter** [comment]
And, works on master as well:  

![screen_shot_2015-08-22_at_19_44_44](https://cloud.githubusercontent.com/assets/1833361/9425158/561d2108-4906-11e5-953f-fcc2375ea817.png)

**Comment by GawainLynch** [comment]
Got me screwed… 100% different results every time both ends :frowning:

**Comment by bobdenotter** [comment]
Did you see this comment? You sure you saved it properly? 

> One thing that's slightly weird in the UI, is that you have to set the template, _then_ save, and _then_ refresh the page to see the new template fields.. sure you've done that?

**Comment by GawainLynch** [comment]
```
$ cd /tmp
$ git clone https://github.com/bolt/bolt.git
$ cd bolt
$ composer install
$ php -S localhost:8123 -t . index.php 
```

**Comment by GawainLynch** [comment]
Same result on master… same result on the refactor branch I am on

**Comment by bobdenotter** [comment]
What ends up in your DB, then? 


Also, go make dinner for Erin! ;-)

**Comment by GawainLynch** [comment]
Erin: How is dinner coming along
Gawain: Oh my goodness, it is tasting awesome… Back in a second, I need to check if there is a response…

The OP is a cleaned up copy/pasta of the `.dump`

**Comment by GawainLynch** [comment]
Set up:
```
$ cd /tmp
$ git clone https://github.com/bolt/bolt.git
$ cd bolt
$ git checkout release/2.2
$ composer install
$ php -S localhost:8123 -t . index.php 
```

Edit `theme/base-2014/config.yml`:
```yaml
templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Extra Fields Section 1
        section_2:
            type: text
            label: Extra Fields Section 2
    otherfields.twig:
        section_1:
            type: text
            label: Other Fields Section 1
        section_2:
            type: text
            label: Other Fields Section 2
```

Open a *Page* ContentType in the [UI editor](http://localhost:8123/bolt/editcontent/pages#content):
![screenshot from 2015-08-23 06-01-31](https://cloud.githubusercontent.com/assets/1427081/9427011/71883fee-495c-11e5-84b4-589519a443b0.png)

The first value is the only one available for selection

Save the page and go to the **Templates** tab:
![screenshot from 2015-08-23 06-06-21](https://cloud.githubusercontent.com/assets/1427081/9427021/2badfd46-495d-11e5-9d83-6a236219377f.png)

Query the database table directly:
```
$ sqlite app/database/bolt.db 
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> SELECT * FROM bolt_pages;
1|template-fields-test|2015-08-23 05:06:07|2015-08-23 05:07:38|2015-08-23 05:05:46||{"section_1":"ValueA","section_2":"ValueB"}||1|draft|Template Fields Test||||extrafields.twig
sqlite> 
```

```
$values = '{"section_1":"ValueA","section_2":"ValueB"}';
dump(json_decode($values, true));
```
```
array:2 [▼
  "section_1" => "ValueA"
  "section_2" => "ValueB"
]
```

**Comment by bobdenotter** [comment]
It's still early, but I can't spot what's wrong with that.. What should've wound up in the DB instead? 

Or are you referring to `otherfields.twig` missing from the list? Does the file exist in the theme folder?

**Comment by GawainLynch** [comment]
Ugh… Yes, I hadn't copied `otherfields.twig` correctly (`otherfield.twig` singular)… That explains the dropdown list.

What I am still not seeing is how do we distinguish what that belongs to:
```
{"section_1":"OtherValue1","section_2":"OtherValue2"}
```

**Comment by bobdenotter** [comment]
Distinguish between what and what? It just stores the fields associated with the chosen template.

**Comment by GawainLynch** [comment]
> Distinguish between what and what?

```yaml
templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Extra Fields Section 1
        section_2:
            type: text
            label: Extra Fields Section 2
    otherfields.twig:
        section_1:
            type: text
            label: Other Fields Section 1
        section_2:
            type: text
            label: Other Fields Section 2
```

Both templates are assigned the same field names, i.e. `section_1` and `section_2`
