### ISSUE TITLE
Maintenance mode is blocking off some of the backend

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#4013]
I have a content type, `modules`, defined like so:

```yml
modules:
    name: Key Modules
    singular_name: Key Module
    singular_slug: module
    fields:
        title:
            type: text
            class: large
        course_no:
            label: Module Number
            type: integer
            min: 1
        slug:
            type: slug
            uses: title
        can_register:
            label: Available for Registration?
            type: checkbox
        description:
            type: html
    viewless: true
    sort: module_no
```

I've enabled maintenance mode, and when I go to the overview page (`/bolt/overview/modules/`), I get the maintenance mode page. This doesn't happens with another content type on the website (note the very similar definition):

```yml
electives:
    name: Electives
    singular_name: Elective
    singular_slug: elective
    fields:
        title:
            type: text
            class: large
        course_no:
            label: Elective Number
            type: integer
            min: 1
        slug:
            type: slug
            uses: title
        can_register:
            label: Available for Registration?
            type: checkbox
        description:
            type: html
    viewless: true
    sort: elective_no
```

There are 5 other content types that I can access without a problem.

With the problematic content types, I can access the `editcontent` page just fine.

**Edit:** I'm the root user, logged in, but I can't access the site with maintenance mode on. Things are amiss!

On Bolt 2.2.8.
