### ISSUE TITLE
[Feature] Configurable route binding for each taxonomy

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4014]
_taxonomy.yml_

``` yaml
categories:
    ...
    route: categorieslink
    ...
```

_routing.yml_

``` yaml
categorieslink:
    path: /categories/{slug}
    defaults:
        _controller: Bolt\Controllers\Frontend::taxonomy
    requirements:
        slug: [Bolt\Controllers\Routing::getTaxonomyRequirement, [categories]]
```
