### ISSUE TITLE
No related entries on preview

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4044]
Hello,

I have contenttype `A` and contenttype `B`.

On `A` I can select one of `B`. On the template for `B` I can fetch `A` with related().. But When I preview `B` the relation to `A` is `false`.

Looks like a bug to me.

**Comment by SahAssar** [comment]
Is this just when previewing `b`, or is the relation to `a` always false from `b` ?

**Comment by PhillippOhlandt** [comment]
It's just in the preview.

**Comment by SahAssar** [comment]
Yep, seeing the same thing here. Looks like a bug. Confirmed in 2.2.10 and Master.

Only seems to happen if B does not have the relationship defined in contenttypes.yml.

**Comment by PhillippOhlandt** [comment]
Yes. In my case, its Tiles and Pages. I assign a Page to a Tile. But cannot fetch the Tile in the Page template in preview mode. I am on 2.2.9

**Comment by bobdenotter** [comment]
I'm having a hard time reproducing this. Could either of you post a `contenttypes.yml` that shows when the problem occurs?

**Comment by PhillippOhlandt** [comment]
Here are the two contenttypes:

```
tiles:
    name: Tiles
    singular_name: Tile
    fields:
        title:
            type: text
            class: large
            required: true
            group: common
        position:
            type: select
            values: [ P1, P2, P3, P4, P5 ]
            required: true
        location:
            type: location
        headline:
            label: Headline
            type: text
            group: content
        sub_headline:
            label: Sub headline
            type: textarea
        textposition:
            label: Set the position of the headline and text
            type: tiletextposition
            class: tiletextposition
        textcolor:
            label: Text color
            type: text
            postfix: RGB HEX (#ffffff) code. Leave blank for black.
        image:
            label: Background
            type: image
            attrib: background # Note: retrieve this in your template with {{ record.values.image.background }}
            extensions: [ jpeg, jpg, png ]
        template:
            type: templateselect
            filter: 'tile_*.twig'
            group: common
    liveeditor: false
    recordsperpage: 100
    record_template: tile_default.twig
    default_status: held
    relations:
        pages:
            multiple: false
            label: Select a page
            order: -id

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            required: true
        slug:
            type: slug
            uses: title
        template:
            type: templateselect
            filter: 'page_*.twig'
        headline:
            label: Headline
            type: text
            class: large
        sub_headline:
            label: Sub Headline
            type: text
        introduction:
            type: html
    recordsperpage: 100
    record_template: page_default.twig
    default_status: published
    relations:
        authors:
            multiple: false
            label: Select an author
            order: -id
        books:
            multiple: false
            label: Select a book
            order: -id
        lists:
            multiple: false
            label: Select a list
            order: -id
```

So you can select a Page on a Tile entity. 

I have to following in my template for the pages:

```
{% set data = {
    tile: record.related('tiles')[0],
    page: record
}%}

{{ dump(data) }}
```

Then create a Page, create a Tile, assign the Page to the Tile, go back to the edit form of the Page and click preview. `data.tile` is null in preview mode but filled when not in preview mode. 

Note:
On the contenttypes above, I use some custom field types and some other relations.
