### ISSUE TITLE
Routing: listing {contenttypeslug} with a different template error (Multilanguage support /routing and templating)

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#4160]
**Summary:** I want to list an specific template for a {contenttypeslug} to make a workaround for multilanguage support but the template specification (template:'listing_textos_eng' }) does not work, in the routing, any clue?
 Please see the attached PNG file  thanks in advance!!
**Specifics:** Version: 2.2.10 - 

###### ------------------------------------------------------------------------------
```yaml
ENGcontentlisting:
  path:               '/{contenttypeslug}/eng'
  defaults:           { _controller: 'Bolt\Controllers\Frontend::listing',template:'listing_textos_eng' }
  requirements:
    contenttypeslug:  'Bolt\Controllers\Routing::getPluralContentTypeRequirement'         
```
![template wrong](https://cloud.githubusercontent.com/assets/2666701/10154774/f717a8a0-6641-11e5-9b2a-f349d680adea.png)

![profiler](https://cloud.githubusercontent.com/assets/2666701/10155102/b33a0128-6646-11e5-86e9-9b295b5e0bba.png)

//=================== contenttypes.yml:
```yaml
textos:
    name: Textos
    singular_name: Texto
    fields:
        title:
            type: text
            class: large
            group: Text
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
            group: Text
        spanish:
            type: html
            height: 300px
            postfix: "<p><em>Texto en español</em></p>"
            group: Spanish
        english:
            type: html
            height: 300px
            postfix: "<p><em>Texto en inglés</em></p>"
            group: English      
        image:
            type: image
            group: media
        file:
            type: file
            group: media            
    record_template: texto.twig
    listing_template: listing_textos.twig
    default_status: publish
```
//===================listing_textos_eng.twig:
```twig
{% set currentslug = paths.current|replace({'/eng':''}) %}
{% setcontent records = currentslug  %}

{% include '_header.twig' %}

    <article>
        <ul class="secondary-menu">
            <h1>listing eng</h1>
            {% for record in records %}   
            <li>
                <a href="{{ record.link }}/eng-text">{{ record.title }}–<span>{{ record.subtitle }}</span></a> <a href="{{ paths.files }}{{record.file}}" class="pdf" target="_blank" >PDF</a>
            </li>
            {% endfor %}
        </ul>
    </article>

    {# If there are more records than will fit on one page, the pager is shown. #}
    {{ pager() }}


{% include '_footer.twig' %}
```
