### ISSUE TITLE
Default 'pages' content type name change has no effect on backend UI

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#4161]
When I change the 'pages' content type name and singular_name fields to have them set in another language the change has no effect on the UI.

So when setting the values to this: (Dutch/NL names)

```
pages:
    name: Paginas
    singular_name: Pagina
    fields:
        title:
```

gives me a UI that still has the linktext in the backend sidebar as "Pages", Bekijk 'Pages', Nieuwe 'page'. 

But the slugs do get updated to `/pagina/` and `/paginas/`!  (see screenshot)

I expect the translated names to appear in the UI as well.

Note:
If I create a new content type "articles" and give theme the dutch name "artikelen"  and singular_name "artikel" these get printed properly in the backend UI. "Artikelen", Bekijk Artikelen, Nieuwe Artikel.

![screen shot 2015-09-29 at 10 01 06](https://cloud.githubusercontent.com/assets/5597447/10158190/a736367c-6690-11e5-810a-667d8178c6b4.png)

**Comment by rarila** [comment]
All backend contenttype localisation is done using menu ``Settings: Translations | Contenttypes``. (Ends up in ``bolt/app/resources/translations/nl_NL/contenttypes.nl_NL.yml`` in your case)

**Comment by sbonardt** [comment]
Exactly, that's the weird thing about it. "Artikelen" does get used in the UI. How is that possible if it's _not_ being used from the translation file "bolt/app/resources/translations/nl_NL/contenttypes.nl_NL.yml" as thats all commented out?

**Comment by bobdenotter** [comment]
I still think this is an issue. @rarila: while technically you are correct, this issue is confusing and hard to understand for users. So in that regard it _is_ broken.

**Comment by rarila** [comment]
Was looking that up at the moment. In [latest version](https://github.com/rarila/bolt/blob/master/app/resources/translations/nl_NL/contenttypes.nl_NL.yml#L77) is "Nieuwe pagina" in contenttypes.nl_NL.yml. So, @sbonardt What do you have there?

@bobdenotter I always told you it is a broken design to have localisation data in two places ;-) This gotta be fixed in 3.0

**Comment by bobdenotter** [comment]
The thing is that sbonardt _explicitly_ defines the `name: ` for the contenttypes, and for _one_ of them the name is ignored, while for the _other_ the name is used as defined in `contenttypes.yml`. This is not something that can be explained to people.

**Comment by sbonardt** [comment]
jep. that's it. :)

I have nothing in my NL translation file (it's all commented out) but 'articles' gets "translated" (the name and singular name appear to be used, while for pages it doesn't seem to get used. If this is in core translation or not, I wouldn't know. And if I look in the translation file for my language it's not there.

**Comment by rarila** [comment]
@sbonardt If you create a new contenttype then there's no translation at all and a generic one is used (that with some luck is grammatically halfway correct). You have to add the translation by yourself then.

@bobdenotter Yes you can't. That's why all localisation stuff has to go in the localisation part (``contenttypes.xx_XX.yml``) and only the definition of database has to be in ``contenttypes.yml``. Then it's simple

**Comment by rarila** [comment]
@sbonardt The generic ones are to be found [here](https://github.com/rarila/bolt/blob/master/app/resources/translations/nl_NL/messages.nl_NL.yml#L453)

**Comment by bobdenotter** [comment]
I know we've had this discussion before, and my opinion was overruled, but it really doesn't make any sense to me. :-/

**Comment by sbonardt** [comment]
Hi @rarila thanks for the link.

As example, the translation for 'New %contenttype%'  is there. It's new: "Nieuwe %contenttype%"

So the "New" part is translated to "Nieuwe" but the %contenttype% not. However, I do see a translated name in the UI for one content type "Artikelen" but not for the other "Pages". How come "Articles"  does get translated to "artikelen" and "artikel" but "Pages"  does not get translated to "paginas" and "pagina"? Where can that be found? They both are fairly generic to me.

```
pages:
    tablename: pages
    name: Paginas
    singular_name: Pagina
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ chapters ]
    recordsperpage: 100


# Articles
articles:
    name: Artikelen
    singular_name: Artikel
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ tags ]
    recordsperpage: 100
```
