### ISSUE TITLE
Relation contenttype with no title column

### ISSUE THREAD

**Issue by nikgo** [bolt/bolt#4259]
**Summary**
A relation with a contenttype that have no (well-known) title column throws an exception on contenttype edit page.

**Details**

* Request URI: /bolt/editcontent/persons
* Exception:

> Doctrine \ DBAL \ Exception \ SyntaxErrorException
> An exception occurred while executing 'SELECT id, as title FROM bolt_buildings buildings ORDER  BY number ASC': SQLSTATE[HY000]: General error: 1 near "as": syntax error

* Bolt Version: current master (33e82875fd69d38e0de5bea1c5ef8b18a2a455a1)
* Database: SQLite

**Steps to reproduce**

* Create this two contenttypes:
```yaml
persons:
    name: Persons
    singular_name: Person
    fields:
        name:
            group: person
            type: text
            class: large
            label: "Nachname"
            variant: inline
            required: true
        firstname:
            type: text
            class: large
            label: "Vorname"
            variant: inline
            required: true
        slug:
            type: slug
            uses: [ name, firstname ]
        image:
            type: image
    relations:
        buildings:
            multiple: true
            label: Buildings
            order: -number
            format: "#{{ item.number|escape }} {{ item.address|escape }} <span>(ID {{ item.id }})</span>"

buildings:
    name: Buildings
    singular_name: Building
    fields:
        address:
            type: text
            class: large
        slug:
            type: slug
            uses: [ address ]
        number:
            type: text
            pattern: "[0-9]{1,4}"
            variant: inline
        information:
            type: html
```
* Go to bold backend and try to create or edit a new person.

**Debug**

* The relation lists are get in `Bolt\Storage\RecordModifier`, method: `getRelationsList`
* The relation list is get via `Bolt\Storage\Repository\ContentRepository`, method: `getSelectList($contentType, $order)`
* SQL Query is built in same class in method `querySelectList($contentType, $order)`
```php
       $qb = $this->createQueryBuilder($contentType);
        $qb->select('id, ' . $this->getTitleColumnName() . ' as title')
            ->orderBy($order, $direction)
        ;
```
* `$this->getTitleColumnName()` search for a well-known definition of a 'title' column:
```php
      $names = [
            'title', 'name', 'caption', 'subject', // EN
            'titel', 'naam', 'onderwerp',          // NL
            'nom', 'sujet',                        // FR
            'nombre', 'sujeto'                     // ES
        ];
```
* Problem: Title column of contenttype 'buildings' should be the first text field, here 'address'. The function `getTitleColumnName()` return in this case currently nothing, and result in a wrong sql query.
