### ISSUE TITLE
Custom slug generation

### ISSUE THREAD

**Issue by C4Grey** [bolt/bolt#4327]
Here is a little problem, I have a content type with a slug defined like this:
````yaml
broadcasts:
    name: Broadcasts
    singular_name: Broadcast
    slug: broadcasts
    singular_slug: broadcast
    fields:
        slug:
            type: slug
            uses: id
````
So I am expecting that Bolt will generate a URL like /broadcasts/1 for a single entry after saving of this new entry, but instead it generates something like /broadcasts/slug-qsgkn1. When I unlocked a slug field, a URL was changed to /broadcasts/broadcast-1. This is a little bit closer to a desired format, but maybe there is some other way to create a custom slug(especially to avoid this lock-unlock procedure that will be a little bit uncomfortable for content managers)? For example, maybe I should to make some extension related to the Silex URL Generator...sorry, I dont know the framework architecture well and will appreciate any help that allow me to create my own extension that will generate custom slugs.
