### ISSUE TITLE
[v2.2.13] Can't remove create, edit, publish and depublish permissions for chief-editor role

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4336]
Hey,

I want to remove the create, edit, publish and depublish permissions for the chief-editor role from 2 content types.

Here is one entry from my permissions.yml

```
    authors:
        edit: [ admin, developer ]
        create: [ admin, developer ]
        publish: [ admin, developer ]
        depublish: [ admin, developer ]
        delete: [ admin, developer ]
        # Roles that can see the area in the admin section
        view: [ developer, admin ]
```

But the permissions are still there, look here:
https://infinit.io/_/3bd59Q7
