### ISSUE TITLE
"Relationships" shows only 'from' relations, not the 'to' ones. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4338]
On a test site, updating from 2.2x to 2.3. 

Before: 

![screen shot 2015-10-26 at 16 29 13](https://cloud.githubusercontent.com/assets/1833361/10734001/6a76bc8a-7c01-11e5-9d0a-73d429863154.png)

After: 

![screen shot 2015-10-26 at 16 42 21](https://cloud.githubusercontent.com/assets/1833361/10734011/73062296-7c01-11e5-9370-69894abad59e.png)

If we look in the DB, we'll see that the missing ones are in the 'to' column. 

![screen shot 2015-10-26 at 16 48 26](https://cloud.githubusercontent.com/assets/1833361/10734027/89785724-7c01-11e5-832b-faafdf54f1a0.png)

pinging @rossriley @GawainLynch

**EDIT** Missing visual:
![incoming relationship](https://cloud.githubusercontent.com/assets/1427081/10784232/d8ec84c0-7d54-11e5-8861-e52d0e6e2189.png)

**Comment by bobdenotter** [comment]
Also notice it says "new programma" instead of "edit programma" in the second screenshot.

**Comment by GawainLynch** [comment]
> Also notice it says "new programma" instead of "edit programma" in the second screenshot.

Feature :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
To reproduce this, simply create a relationship in two contenttypes:

```
pages:
    name: Pages
    singular_name: Page
    fields:
      [..]
    relations:
        showcases:
            multiple: true
            order: title
            label: Select showcases

[..]

showcases:
    name: Showcases
    singular_name: Showcase
    fields: 
        [..]
    relations:
        pages:
            multiple: true
            order: title
            label: Select pages
```

Now, edit a 'page', add some relationships to showcases. Save them, and they stick.. Now, go to 'showcases', and edit the showcase you just added a relationship to. Notice how it doesn't show up as a relationship here.
