### ISSUE TITLE
Editing an existing record shows 'New ..' instead of 'Edit .. » ..'. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4339]
For example, see screenshot: 

![screen_shot_2015-10-26_at_18_18_32](https://cloud.githubusercontent.com/assets/1833361/10736641/73ad1742-7c0e-11e5-91ac-29ba07389ac2.png)

Steps to reproduce: 

Create a contenttype. The key is to add a 'title' field, not named `title`: 

```
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        the_title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: the_title
        body:
            type: html
            height: 300px
```

Then, update the DB, and add some loripsum records.. So far, so good: 

![screen shot 2015-10-26 at 18 24 28](https://cloud.githubusercontent.com/assets/1833361/10736726/d17a4c96-7c0e-11e5-9f73-c2e226301b74.png)

Notice that the 'guessed' titles here are correct. It uses the `->getTitle()` method as it should. 

Now, if you edit one of them, it'll say "New Dummy" instead of "Edit Dummy". If I edit `app/view/twig/editcontent/editcontent.twig`, like so: 

```
    \Content :
    {{ dump(context.content) }}

    context.content.the_title :
    {{ dump(context.content.the_title) }}

    context.content.getTitle()
    {{ dump(context.content.getTitle()) }}

    context.content.herpderpnonexistant()
    {{ dump(context.content.herpderpnonexistant()) }}
    ...

```

This is the output: 

![screen shot 2015-10-26 at 18 33 32](https://cloud.githubusercontent.com/assets/1833361/10736997/171fdfc6-7c10-11e5-8468-e2f2a94e9d67.png)

So, `context.content` _is_ `\Bolt\Storage\Entity\Content`, as it should. It just doesn't work. And that's when I got lost. 

Halp? ¯\\(°_o)/¯
