### ISSUE TITLE
Required on custom select field doesnt seem to be working

### ISSUE THREAD

**Issue by bjrnblm** [bolt/bolt#4353]
When i set a `required: true` on the a select field it does not seem to do anything. For example the `subpaginas.hoofdpagina` field here:

```
paginas:
    name: Pagina's
    singular_name: Pagina
    fields:
        titel:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: titel
        afbeelding:
            type: image
        inhoud:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: 'pagina_*.twig'
    record_template: pagina_standaard.twig
    default_status: publish

subpaginas:
    name: Subpagina's
    singular_name: Subpagina
    fields:
        hoofdpagina:
            type: select
            values: paginas/titel
            postfix: "Selecteer een pagina"
            autocomplete: true
            sort: titel
            group: content
            required: true
        subtitel:
            type: text
            class: large
            group: content
            label: Titel
            required: true
        slug:
            type: slug
            uses: subtitel
        subinhoud:
            label: Inhoud
            type: html
            height: 300px
            allowtwig: true
    record_template: subpagina_standaard.twig
    default_status: publish
```

It renders the following code for the select:

```
<select id="hoofdpagina" name="hoofdpagina" style="width: 100%;" tabindex="-1" title="" class="select2-offscreen">          
    <option value="0" selected="selected"></option>          
    <option value="2">Contact</option>
    <option value="6">Deze pagina bestaat niet (meer)</option>            
    <option value="1">Over ons</option>        
    <option value="7">Sitemap</option>
</select>
```

There seems to be a `required` tag missing, also it renders an empty extra row with value 0. Therefor this field always has a value and the required error is not shown.

<img width="829" alt="screen shot 2015-10-28 at 12 26 02" src="https://cloud.githubusercontent.com/assets/2300511/10787185/26b8fa34-7d6f-11e5-895c-fc02b09a8920.png">

The Bolt version we are running is: 2.2.13
