### ISSUE TITLE
select fieldtype as a templatefield does not save value

### ISSUE THREAD

**Issue by asiral** [bolt/bolt#4358]
You can easily re-create this in a docker.

In the 'demo' theme, edit config.yml and add a field under the 'extrafields.twig' like this:

```
templatefields:
    extrafields.twig:
        teaser:
            type: select
            values: [1,2,3]
```

Creating a page with the extrafields.twig template and choosing a value for this field of the newly created page, you can see there is no value saved.

In extrafields.twig, adding {{ dump(record.templatefields) }} confirms this.

If it lasts long enough to save anyone time: http://bolt_1x0xe5.bolt.dockerfly.com/page/test
