### ISSUE TITLE
Can't save select fieldtype with hash ids

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4375]
When you define a field with select fieldtype
```yaml
industry:
    type : select
    values :  { 1 : 'Retail', 2 : 'Distribution', 3 : 'Production'}
    multiple:  true
```
and select the first option on editcontent page, the value is being saved (in database) as `['Retail']`, not `[1]`.
It only works if one of ids in hash has non-numeric characters: 
```yaml
    values :  { 1 : 'Retail', 2 : 'Distribution', 3 : 'Production, 'need to hack': 'hulk sad'}
```
but even in this case it's being saved as `["1"]`, not as `[1]`
