### ISSUE TITLE
Thumbnails seems not working correctly

### ISSUE THREAD

**Issue by kur1977** [bolt/bolt#4389]
Hi.
In config.yml I have
```yaml
thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: fit
    notfound_image: view/img/no_image.jpg
    error_image: view/img/default_error.png
    save_files: true
    allow_upscale: true
    exif_orientation: false
```

I try to change the cropping parameter to something else(fit, borders, resize), but thumbs and images are displayed cropped.
