### ISSUE TITLE
auto-creation of subfolders in /files/ for contenttype uploads

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4405]
##### Feature suggestion
I suggest this feature: create directory, pointed in contenttype for upload fields.
So if i set
```yml
image:
    type: image
    upload: 'articles'
```
bolt should create that directory. At the moment it just shows `upload not allowed`.

It should be made via command in menu or everytime on backend login or elsewhere..
