### ISSUE TITLE
Creating a record for a slugless contenttype entity gives an error

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4477]
Having this entity:
```yml
faqs:
    fields: #these fields only
        question:
            type: text
        answer:
            label: "Ответ"
            type: textarea
```
saving new record, it gives "_Integrity constraint violation: 19 NOT NULL constraint failed: bolt_faqs.slug_"
![2015-11-17 01-32-49](https://cloud.githubusercontent.com/assets/2145313/11192397/1ff2ab94-8ccb-11e5-9dd7-cf2193a0e803.png)
