### ISSUE TITLE
Updating databases with SQlite breaks when adding a field.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#448]
When installing the default contenttypes that come with a new setup, Bolt breaks when you add a field to the contenttype:

``` yml
entries:
    name: Entries
    singular_name: Entry
    fields:
       [snip]
        body:
            type: html
            height: 300px
        body2:
            type: html
            height: 300px            
    relations:
```

When updating the DB you get the following error.

```
An exception occurred while executing 'ALTER TABLE bolt_entries ADD COLUMN body2 CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
```
