### ISSUE TITLE
Default publish date for timed publish

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#4505]
contenttypes.yml:

``` yaml
foo:
    default_status: timed
    default_publish_date: this sunday 11:59:00
```

**Comment by SahAssar** [comment]
Just to be clear this is a proposal to have default publish date option in contenttypes.yml, right?

**Comment by SahAssar** [comment]
Also for depublish date I hope :)

**Comment by GawainLynch** [comment]
Or for @jkazimir 

```yaml
foo:
    default_status: timed
    default_publish_date: December 31 1969 16:00 PST
```
