### ISSUE TITLE
"Default" values in contenttypes.yml aren't used.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4532]
If you do this in contenttypes.yml: 

```
        datetime:
            type: datetime
            default: "2000-01-01"
            variant: inline
        date:
            type: date
            default: "first day of last month"
            variant: inline
        integerfield:
            type: integer
            index: true
            default: 666
        floatfield:
            type: float
        selectfield:
            type: select
            values: [ none, foo, bar ]
        multiselect:
            type: select
            values: [ A-tuin, Donatello, Rafael, Leonardo, Michelangelo, Koopa, Squirtle ]
            multiple: true
            postfix: "Select your favourite turtle(s)."
            default: "Donatello"
```

New records use those default values in 2.2.13: 

![screen_shot_2015-11-25_at_16_56_04](https://cloud.githubusercontent.com/assets/1833361/11402213/fbaee2fc-9396-11e5-8ae1-92a034c79c5f.png)

In 2.3 however, these are ignored: 

![screen_shot_2015-11-25_at_16_56_33](https://cloud.githubusercontent.com/assets/1833361/11402222/06a784ac-9397-11e5-8199-2b3ae3d2d8ac.png)
