### ISSUE TITLE
Image upload via content type not working, creates JS error

### ISSUE THREAD

**Issue by stefantalen** [bolt/bolt#4539]
Bolt version: > 2.2.13 (2.2.14 too)
Browsers: Safari 9.0.1 + Google Chrome 46.0.2490.86

Content Type configuration:

```yml
projects:
    name: Projecten
    singular_name: Project
    slug: ons-werk
    singular_slug: ons-werk
    record_template: project.twig
    listing_template: projects.twig
    listing_sort: -datepublish
    #listing_records: 10
    fields:        
        title:
            label: Titel
            type: text
            group: Teksten
            required: true
        slug:
            type: slug
            uses: title
        activities:
            label: Werkzaamheden
            type: textarea
        method:
            label: Werkwijze
            type: textarea
        materials:
            label: Materialen
            type: textarea
        intro:
            label: Korte omschrijving
            type: textarea
            required: true
        description:
            label: Omschrijving
            type: markdown
        project_image:
            label: Algemene afbeelding
            type: image
            attrib: alt
            required: true
            group: Afbeeldingen
        images_before:
            label: Afbeeldingen "Voor"
            type: imagelist
        images_during:
            label: Afbeeldingen "Tijdens"
            type: imagelist
        images_after:
            label: Afbeeldingen "Na"
            type: imagelist
    relations:
        diensten:
            multiple: true
            label: Selecteer een of meerdere diensten
            order: id
            format: "{{ item.title }}"
```

When uploading an image for `images_before` the progress bar appears with the filename that should be uploaded but this JS error pops up and the file is never uploaded:

```txt
TypeError: (b.type||b.form.prop("method")||"").toUpperCase is not a function. (In '(b.type||b.form.prop("method")||"").toUpperCase()', '(b.type||b.form.prop("method")||"").toUpperCase' is undefined) _initFormSettings - lib.min.js:8312:305
```

The same goes when trying to upload a `project_image` but there is no progress bar shown.
