### ISSUE TITLE
MySQL can't create table with hyphen in ContentType name

### ISSUE THREAD

**Issue by stefantalen** [bolt/bolt#4567]
I was trying to see if I could fix my issue #4539 but stumbled upon this error after checking out the master branch:

```sql
An error occured while updating `bolt_ons-werk`. The error is An exception
occurred while executing 'CREATE TABLE bolt_ons-werk (id INT AUTO_INCREMENT NOT
NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged
DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME
DEFAULT NULL, username VARCHAR(32) DEFAULT '', ownerid INT DEFAULT NULL, status
VARCHAR(32) NOT NULL, templatefields LONGTEXT DEFAULT NULL COMMENT
'(DC2Type:json_array)', title VARCHAR(256) DEFAULT '' NOT NULL, activities
LONGTEXT NOT NULL, method LONGTEXT NOT NULL, INDEX IDX_2AA2566B989D9B62 (slug),
INDEX IDX_2AA2566BAFBA6FD8 (datecreated), INDEX IDX_2AA2566BBE74E59A
(datechanged), INDEX IDX_2AA2566BA5131421 (datepublish), INDEX
IDX_2AA2566BB7805520 (datedepublish), INDEX IDX_2AA2566B7B00651C (status),
PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE =
InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an
error in your SQL syntax; check the manual that corresponds to your MySQL server
version for the right syntax to use near '-werk (id INT AUTO_INCREMENT NOT NULL,
slug VARCHAR(128) NOT NULL, datecreated D' at line 1
```

The only thing I changed was adding this content type:

```yml
## Content type for issue 4539
projects:
    name: Projecten
    singular_name: Project
    slug: "ons-werk"
    singular_slug: "ons-werk"
    record_template: project.twig
    listing_template: projects.twig
    listing_sort: -datepublish
    #listing_records: 10
    fields:        
        title:
            label: "Titel"
            type: text
            group: Teksten
            required: true
        slug:
            type: slug
            uses: title
        activities:
            label: Werkzaamheden
            type: textarea
        method:
            label: Werkwijze
            type: textarea
```
Looks like something changed compared to the 2.2 version because I didn't have this issue then.

I was also looking for some unit tests that checks the systems output of content types but I can't find them, where should I look?
