### ISSUE TITLE
Viewing a preview of a record clears the unsaved record warning

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#4640]
If I make a new record, or edit an existing one, edit some fields, and then try to leave the page without saving I will get a warning if I try to navigate away from the page.

If I preview the record (via the preview button in the editor page), and *then* try to navigate away from the page, I will no longer get such a warning. The expected behaviour is that I would still get a warning.

Tested on version `2.2.15`.

**Comment by bobdenotter** [comment]
Hey @Pinpickle! Long time no see! 

I've noticed this once or twice, too. It depends (i think) on the types of fields present. Thanks for logging, because we should investigate this.

**Comment by Pinpickle** [comment]
Hello @bobdenotter! It has been a while. Unfortunately university and student visas are very good at putting the freelance web developer out of a job. That's not to say I haven't been following what Bolt has been up to. It is very exciting!

For more usefulness, here is the contenttype. I noticed the bug with editing the body and title fields:

```yml
posts:
    name: Posts
    singular_name: Post
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        body:
            type: markdown
            height: 300px
        image:
            type: image
        # template:
        #    type: templateselect
        #    filter: 'pages/*.twig'

        meta_title:
            group: meta
            prefix: '<h3>SEO Information</h3>'
            label: Meta Title
            type: text
        meta_description:
            label: Meta Description
            type: textarea

    recordsperpage: 100
    listing_records: 9
    listing_template: pages/blog.twig
    record_template: pages/post.twig
```
