### ISSUE TITLE
contenttype name with _ (underscore) not allowed

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4674]
If you create a content type with an underscore in the identifier the database update will break. The following will result in a lot of notices like `Notice: Undefined index: custom_things in /[]/html/src/Storage/Database/Schema/Builder/ContentTables.php on line 33`

```yml
custom_things:
  name: Things
  singular_name: Thing
  fields:
    title:
      type: text
      required: true
      label: "Title"
    slug:
      type: slug
      uses: title
    body:
      type: textarea
      label: "Body"
```

Also the fields `title` and `body` will not be created, so the database update will keep nagging you that the database is broken.
