### ISSUE TITLE
post and prefix dont work in repeater fields

### ISSUE THREAD

**Issue by activestylus** [bolt/bolt#4710]
Pretty easy to duplicate:

```yaml
products:
    name: Products
    singular_name: Product
    fields:
        title:
           type: text
           prefix: Texting Prefix
           postfix: Texting Postfix
        variants:
            label: "Available in:"
            type: repeater
            group: Product Options
            limit: 10
            fields:
                title:
                  type: text
                  prefix: Testing nested prefix
                  postfix: Testing nested postfix
```

The top level text shows but the nested ones do not. (tested on master branch)
