### ISSUE TITLE
ContentType names with Capital Letters break

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4754]
This will break:
```yaml
Jobs:
  name: Jobs
  singular_name: Job
  fields:
```
Error:
```
Bolt - Fatal error.
Class: Bolt\Exception\StorageException
Message: Attempted to load mapping data for unmapped class Jobs
Code: 0
Bolt\Storage\Mapping\MetadataDriver->loadMetadataForClass()
[root]/src/Storage/EntityManager.php, line 256
```

This will work:
```yaml
jobs:
  name: Jobs
  singular_name: Job
  fields:
```
