### ISSUE TITLE
unable to save records with an empty select field

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4763]
When I have a select field in a content type I cannot create entries if I don't select anything. Which is a problem is there are no records in 'othertype'

```yaml
mythings:
  name: Things
  singular_name: Thing
  fields:
    title:
      type: text
      label: Title
    slug:
      type: slug
      uses: title
    myselect:
      type: select
      values: othertype/id,title
      autocomplete: true
      label: "Select structure tree parent"
```

This occurs when running on a mysql database because it seems to create a column with not null set

```sql
  `myselect` longtext COLLATE utf8_unicode_ci NOT NULL,
```

And the bolt back-end will send a null anyway.
