### ISSUE TITLE
[RFC] custom formatting of listing item

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4816]
##### Issue
Sometimes i need to customize the way, how my list looks like. Maybe it's interesting to have an ability to setup, how bolt formats each row in listing? Now it looks like heavy usage of `title` field and some other random fields. We can add a new property, that defines, how will Bolt format this string.

##### Probably it could look like:
```yml
persons:
    singular_name: Person
    editcontent_listing_format: 'item.last_name|default('Pleast set the last name')'
    fields: 
        …
```
we can use another property name

##### additionally
There are different types of listings. Should we allow user to customize them all?
