### ISSUE TITLE
[BUG] Unable to generate a URL for the named route "preview" since 2.2.17

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#4870]
Since 2.2.17 Bolt refuses editing some of my multi-language contenttypes.
Reverting to 2.2.16 everything works, but with 2.2.17 and 2.218 I get the following error trying to edit or create a multilingual contenttype:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "preview" as such route does not exist.") in "editcontent/_buttons.twig" at line 36.

contenttype:
```yaml
en-pages:
    name: Pages
    singular_name: Page
    fields: &pagefields
        title:
            type: text
            class: large
            group: content
            required: true
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
        sorting:
            type: integer
            label: Display order
        background-image:
            type: image
            group: media
            label: Background Image (1920 x 1080)
        teaser-image:
            type: image
            label: Teaser Image (840 x 175)
        seo-keywords:
            type: text
            group: seo
            label: SEO Keywords (Use comma to separate)
        seo-description:
            type: textarea
            label: SEO Description
    relations:
        de-pages: &langrelations
            multiple: false
            label: Select a page
            order: id
    sort: sorting
    icon_many: "fa:file-text-o"
    icon_one: "fa:file-text"
    record_template: page.twig
    show_in_menu: English
de-pages:
    name: Seiten
    singular_name: Seite
    fields: *pagefields
    relations:
        en-pages: *langrelations
    sort: sorting
    icon_many: "fa:file-text-o"
    icon_one: "fa:file-text"
    record_template: page.twig
    show_in_menu: Deutsch

**Comment by SahAssar** [comment]
What does your routing.yml look like?

**Comment by rompcik** [comment]
My routing.yml looks like this (and works with 2.2.16!):

```yaml
# ------------------------------------------------------------------------------
# [en,de] Automatic Selection of Language for Frontpage
# ------------------------------------------------------------------------------
homepage:
    path:               /
    defaults:           { _controller: 'Hotel\Controller::i18nFront' }

# ------------------------------------------------------------------------------
# [en] English
# ------------------------------------------------------------------------------

en-home:
    path:               /en
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-pages', 'slug': 'home' }


en-offers:
    path:               /en/offer/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-offers' }
    contenttype:        en-offers

en-pages:
    path:               /en/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-pages' }
    contenttype:        en-pages

# ------------------------------------------------------------------------------
# [de] Deutsch
# ------------------------------------------------------------------------------

de-home:
    path:               /de
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-pages', 'slug': 'home' }

de-offers:
    path:               /de/angebot/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-offers' }
    contenttype:        de-offers

de-pages:
    path:               /de/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-pages' }
    contenttype:        de-pages
    
unknown:
    path:               /{slug}
    defaults:           {  _controller: 'Bolt\Controllers\Frontend::record', _before: 'Hotel\Controller::i18nBefore', 'contenttypeslug': 'Bolt\Controllers\Routing::getAnyContentTypeRequirement' }
```
