### ISSUE TITLE
[RFC] As a content editor I would like template specific fields to persist between template changes.

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#4874]
Template specific fields are currently cleared when changing from one template to another. Whilst this is the default behaviour, having the option to persist values would be advantages. It is helpful to sometimes change the template temporarily and then you want to change it back. 

The warnings work but they do not allow for efficient working.

**Comment by SahAssar** [comment]
IIRC it used to work like this (a side-effect of how it was implemented), but it's a bit counterintuitive that the data would persist when the data model has changed... The only way to do this well enough would be to only persist values that have both the same key *and* the same fieldtype, and even that seems pretty niche to me.

Thoughts?

**Comment by tomntech** [comment]
I would say that the underlying model has all the fields, then the displayed fields in the editor are based upon the selected template. That way you can persist the values.

**Comment by bobdenotter** [comment]
This is correct: If the field _key_ names are the same, they will persist if you toggle them. For example, this works as expected, when toggling between 'page' and 'record':

```
templatefields:
    page.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
    record.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
```
