### ISSUE TITLE
[RFC] Allow templatefields, taxonomies and relations to be in any tab

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#4875]
Allow templatefields, taxonomies and relations to be in any tab:
- [ ] templatefields
- [ ] taxonomies
- [ ] relations

**Comment by SahAssar** [comment]
The goal (IIRC) is to have templatefields, relations and taxonomies behave more like "normal" fields, but this is still not implemented and tested. I have an extension that does this in a very crude and probably not very forwards compatible manner, but you can check it out if you want at http://extensions.bolt.cm/view/1732aa8a-cc16-11e5-bf25-14cdca8e654f

**Comment by bobdenotter** [comment]
This is correct: If the field _key_ names are the same, they will persist if you toggle them. For example, this works as expected, when toggling between 'page' and 'record':

```
templatefields:
    page.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
    record.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
```
