### ISSUE TITLE
[RFC] Including uploaded images from a post into an HTML field

### ISSUE THREAD

**Issue by smokeysmokeyd** [bolt/bolt#4885]
Howdy,

Thanks so much for all y'alls hard work.

I'm looking for a suggestion of how to embed images uploaded along with a post, in the HTML 'body' of that post.

For example, If I've got a content-type like this:

```
page:
   - name: Page
   - fields:
      - images:
         - type: imagelist
      - body:
         - type: html
```

And I want to include some of the files uploaded in the `images` field, into the HTML field. I've thought about achieving this by enabling twig in the html fields but I wonder if you all might suggest another way. Ideally I'd like to be able to easily select specific images from the imagelist at particular locations along the body, which is content-specific and the reason why I can't just embed them in the template.

Hope my explanation is clear! Thank you!

Smokey

 - Relevant Bolt Version: [ 2.2 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.5 ]
 - Used webserver: [ Apache ] version [ 2 ]
