### ISSUE TITLE
Twig variable missing in editor for text fields

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4907]
This shows up in master editing a Showcase with Twig set to strict.
```
Key "default" for array with keys "class, label, variant, canUpload, type" 
does not exist in "@bolt/editcontent/fields/_text.twig" at line 32
```

**Comment by bobdenotter** [comment]
On IRC, @EJanuszewski reported something similar: 

```
Impossible to access an attribute ("getEmptySet") on a string variable ("") in "@bolt/editcontent/fields/_repeater.twig" at line 26
```

As far as I can trace it, it seems to have to do with 'default' not being set on repeaters. If I edit the default contenttypes.yml to have: 

```
        repeater:
            type: repeater
            group: repeater
            limit: 3
            prefix: "<p>This allows you to create multiple sets of fields. Use the add button at the bottom to create a new empty set.</p>"
            fields:
                repeattitle:
                    type: text
                    default: 'foo'

```

It works. I have no idea how to fix that though. @rossriley, any ideas?
