### ISSUE TITLE
[BUG] character encoding in taxonomy selection

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4917]
In the back-end selection of taxonomy ampersands will be double encoded:

![image](https://cloud.githubusercontent.com/assets/1488214/13356254/a010ca08-dca4-11e5-849d-41889df6e043.png)

Details
-------

 - Relevant Bolt Version: 3.0 alpha5 / master
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Nginx
 - For UX/UI issues: n/a

Reproduction
------------
Create a category with some entries that have ampersands:

```yml
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options:
      app: App
      website: Website
      interactive: 'Games & Interactive experiences'
      film: Film & Video
```

Make that an active category for a content type and wittness the double encoding
