### ISSUE TITLE
[BUG ]templatefield contenttype select not saving pages/title value

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#4990]
I use the following config in my 'contenttypes.yml' and my 'config.yml' in my theme dir. The yaml code below works for the 'contenttype' in my 'contenttypes.yml' but the code does not work in my theme's 'config.yml'

This is in my theme's 'config.yml' the 'section_1_button:' does show up in the backend but will not save.

```yaml
templatefields:
    index.twig: # Our homepage template
        section_1_heading:
            label: "Titel linker blok"
            type: text
        section_1_body:
            label: "Tekst linker blok"
            type: html
            class: equalize
        section_1_button:
            info: Je kies hier een pagina uit de lijst waar de knop van de widget naar toe moet linken. Wil je een externe link laat dit veld dan leeg.
            label: Link pagina aan button
            type: select
            multiple: false
            prefix: "Je kies hier een pagina uit de lijst waar de knop van de widget naar toe moet linken. Wil je een externe link laat dit veld dan leeg."
            values: pages/title
            autocomplete: true
            keys: slug
```

This code is in my 'contenttypes.yml' and saves fine.

```yaml
asides:
    name: Sidebar widget
    singular_name: Aside
    fields:
        title:
            type: text
            class: large
            group: content
        image:
           type: image
        body:
            type: html
            height: 300px
        button:
           info: Je kies hier een pagina uit de lijst waar de knop van de widget naar toe moet linken. Wil je een externe link laat dit veld dan leeg.
           label: Link pagina aan button
           type: select
           prefix: "Je kies hier een pagina uit de lijst waar de knop van de widget naar toe moet linken. Wil je een externe link laat dit veld dan leeg."
           values: pages/title
           autocomplete: true
           keys: slug
        image:
            type: image
            group: media
    relations:
        pages:
          multiple: true
          order: title
          label: Select a page
    record_template: _aside.twig
    default_status: publish
    sort: -datepublish
    searchable: false
    viewless: true
    recordsperpage: 10
```

Details
-------

 - Relevant Bolt Version: [ 2.2.6 | master ]
 - Install type: [ Github checkout ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache | 2.4 ]
 - For UX/UI issues: [ Version 48.0.2564.116 (64-bit) ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. **Bug summary**: Make a field of the type select and give it a value of page/titel, this wil work/save properly is it is in contenttypes.yml. The same yaml code will not work in a templatefield in config.yml. All other fields save fine, both in the contenttypes.yml and config.yml in my theme folder. 
 2. **Specifics**: The problem happens on the homepage 'index.twig'.
The field is a dropdown and it is populated with page/title's to choose from.
https://www.dropbox.com/s/qrlf0fvxr69azao/Screenshot%202016-03-10%2015.21.08.png?dl=0

After saving the select boxes are still showing my choice, but I hit F5 and refresh the page the select boxes are empty again. And the content does not show up on the site.

 3. **Steps to reproduce**: Create a contenttype in contenttypes.yml and template field in config.yml of your theme, give it the type 'select' and with the 'value' **page/title** as described above. 
 4. **Expected result**: I was expecting that the content would be saved just as it was in the contenttypes.yml. But the field remain empty.
 5. **Actual result**: I have debug mode on and no error messages are displaying.
