### ISSUE TITLE
Checkbox displays wrong value directly after saving, db = ok

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4997]
Hi, some odd behaviour with the checkbox in 2.2.19. This occurred after the fix in #4869

Steps to reproduce:
- In entry, checkbox is 0. 
- Set it to 1.
- Save the entry
- checkbox resets to 0 on screen. (but is correctly set to 1 in DB)
- reloading the page displays correct setting, 1.

(other way around is no problem:
- set from 1 to 0
- save
- still 0.
)

-------

 - Relevant Bolt Version: 2.2.19
 - browsers: chrome, FF

**Comment by bobdenotter** [comment]
Ping @rarila: My guess is that this is a quirk where the fields are 'reset' after saving. Could you look into this?

**Comment by rarila** [comment]
@bobdenotter will check that later. Just as a reminder changing that on [that line](https://github.com/bolt/bolt/blob/release/2.2/app/src/js/modules/editcontent.js#L304) from ``(item == "on")`` to ``item === '1'`` should fix that on 2.x.

v3 is another story…

**Comment by anketwokings** [comment]
Thanks! Fixed in 2.2.19-pl1, already put on clients website, and works like a charm. :)

**Comment by GawainLynch** [comment]
:+1:

**Comment by ToBe998** [comment]
Still broken in 2.2.19-pl1.

Reloading a page is now working, but just pressing "save" still does reset the checkbox.

**Comment by bobdenotter** [comment]
@ToBe998: Have you done a hard-refresh and/or cleared your browser's cache?

**Comment by ToBe998** [comment]
Tested in Chrome 49 even uncached.

1) Load page in editor
2) Check checkox
3) Press Save -> **Unchecked again - Error**
4) Reload page (or freshly open a page with a checked box -> Checked - Ok

**Comment by bobdenotter** [comment]
> "Unchecked again - Error" 

Error? What error does it give?

**Comment by ToBe998** [comment]
No sorry. The error i meant is "The checkbox state is unchecked but should be checked" .

**Comment by bobdenotter** [comment]
@ToBe998 I can't reproduce this..

My CT: 

```

dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        check1:
            type: checkbox
        check2:
            type: checkbox
        check3:
            type: checkbox
        check4:
            type: checkbox
```

Setting them is reflected in the frontend.. for example: 

![screen shot 2016-04-25 at 17 02 37](https://cloud.githubusercontent.com/assets/1833361/14788312/9c622afa-0b07-11e6-99f6-9928376dc1d6.png)

![screen shot 2016-04-25 at 17 02 52](https://cloud.githubusercontent.com/assets/1833361/14788318/a06f60c2-0b07-11e6-8934-ae148e1bd273.png)

Then, changing them: (and saving, and reloading too)

![screen shot 2016-04-25 at 17 04 11](https://cloud.githubusercontent.com/assets/1833361/14788356/c3c9e8e4-0b07-11e6-8e75-cd3420626c1e.png)

![screen shot 2016-04-25 at 17 04 18](https://cloud.githubusercontent.com/assets/1833361/14788366/cd4473da-0b07-11e6-93bf-c54605964423.png)
