### ISSUE TITLE
Is it possible to have multiple imagelists in one contenttype

### ISSUE THREAD

**Issue by HeleenE** [bolt/bolt#500]
I've have changed yaml so I could have multiple imagelists in one contenttype, but when I edit a record of this contenttype and upload a image to one of the imagelists it automatically gets added to the other list. Is this not supported? Or am I doing something wrong? 

```
    images-left:
        type: imagelist
    images-right:
        type: imagelist
```
