### ISSUE TITLE
where {% setcontent %} not working on tags taxonomy

### ISSUE THREAD

**Issue by rkmax** [bolt/bolt#502]
I'm using bolt 1.1.2 lastest_stable .tgz and I have a `elementos` content type with a `tag` taxonomy i'm trying to make the following in my template
### template.twig

```
{% setcontent elementos = "elementos" where { tag: 'acondicionado' } %}
<p>Total de elementos {{productos|length}}</p>
<ul>
    {% for elemento in elementos %}
        <li><a href="{{elemento.link}}">{{elemento.title}}</a></li>
    {% endfor %}
</ul>
```

always show all `elementos` only 5 `elementos` has the tag 'acondicionado'
### *.yml

```
# taxonomy.yml
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags

# contenttypes.yml
elementos:
    name: Elementos
    singular_name: Elemento
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    sort: title
    recordsperpage: 10
    taxonomy: [ tags ]
```
