### ISSUE TITLE
[bug] v3 content type fields with float are not using html5 elements

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#5029]
See also https://github.com/bolt/docs/issues/315

If I set up a content type with the following field

``` yml
    vote:
      type: float
      requred: true
      label: Vote
      min: 0
      max: 10
      step: 0.1
```

The generated HTML is actually:

``` html
<div class="col-sm-9">
        <input class="form-control narrow" data-validate="{&quot;float&quot;:null}" id="vote" name="vote" type="text" value="111">
    </div>
```

I can enter values that are larger than 10 in the bolt back end ... I'd expect those values to be limited
## Details
- Relevant Bolt Version: 3.0 alpha 7
- Install type: Composer install
- PHP version: 5.6
- Used webserver:  Nginx 
- Browser: Chrome 49
