### ISSUE TITLE
[BUG] 'slug' does not render in a 'repeater' field

### ISSUE THREAD

**Issue by dlevninja** [bolt/bolt#5033]
In a repeater field, 'slug' content-types do not render

Details
-------

 - Relevant Bolt Version: [ 3.0]
 - Install type: [  Composer install ]
 - PHP version: [ 5.5.9 ]
 - Used webserver: [ Apache  ] version [ 2.4.7 ]

Reproduction
------------

Create a test content-type:
```
test:
    name: tests
    slug: tests
    singular_name: test
    singular_slug: test
    fields:
        repeater:
            type: repeater
            fields:
                title:
                    type: text
                slug:
                    type: slug
                    uses: [ title ]
```

Renders like this for me:
![repeater_slug](https://cloud.githubusercontent.com/assets/15038931/13832565/06902e10-eba3-11e5-8afc-551192c2d99e.png)

Looking at the HTML, a slug field isn't even sent to the browser, so it's not a UI problem...

I can be more specific with details if nobody else can reproduce this problem? Not using the most recent master but one of a few commits back. I'd be happy to investigate if I had an idea of where to look.

**Comment by GawainLynch** [comment]
Thus quoth @rossriley:

> slugs are disallowed at the moment in repeaters, along with relations, taxonomy, repeaters and templatefields

**Comment by dlevninja** [comment]
hmmmm... any ideas as to why? I assume that it's because there's some complexities involved in implementing those things?

**Comment by bobdenotter** [comment]
@dlevninja a `slug` is not a regular field, but it has implicit functionality, which makes it different than a "regular" text field. It's almost like having two "last modified" or two "publication status" fields. Besides the _technical_ limitations, we'd need to think about how this would make sense from an end user's point of view. 

What's your usecase for having `slug` fields in a repeater?

**Comment by dlevninja** [comment]
Hmm, I see...

What I'm trying to implement is something as follows:

I would like a `body` field for a content-type let's say... `article`. This `body` field will contain photos that have titles and captions, as well as other metadata associated... These photos are included inline in the body, in such a way that is specific to each article and is not something that can be slid into a cookie-cutter template.

How I'm thinking to implement this is have a repeater field 'photos' where a user can add photos and is able to reference those photos programmatically (with macros) with twig templates in the `body` field. For instance, a user would insert a photo `{{ include_photo("golden-gate-bridge") }}` in the `body` of an article about San Francisco; the 'golden-gate-bridge' referenced is the value of the slug for the photo.

Here is a snippet which describes the content-type I'm thinking of above. Still after this I've got to figure a way to implement these macros to actually work (i.e. how will I define them globally for all entries of a particular content-type?).

```
articles:
    name: articles
    slug: articles
    singular_name: article
    singular_slug: article
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: [ title ]
        body:
            type: html
            height: 150px
            enabletwig: true
        photos:
            type: repeater
            group: Photos
            fields:
                title:
                    type: text
                slug:
                    type: text
                    uses: [ title ]
                image:
                    type: image
```

Sample `body` entry for an `article`:
```
San Francisco is a lovely place to visit! Aside from its vibrant culture, large homeless population, and soaring rent, it has some lovely landmarks as well.

{{ insert_photo('golden-gate-bridge') }}

Across the bay from San Francisco is another place that I think is called Oakland, or maybe Fresno; I'm not totally sure. But this is filler text anyways so I guess it doesn't really matter what I'm saying.
```

I would appreciate any guidance you may have of how to implement what I'm looking for!

Thanks so much,
dlevninja<3
