### ISSUE TITLE
[RFC] Consolidate templatefields and template names in theme.yml

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#5068]
Currently we have two different objects in `theme.yml` for adding metadata to template files (names and custom fields)

```yml
templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image
    anotherextrafields.twig:
        markdown:
            type: markdown
            label: A markdown field
        geolocation:
            type: geolocation
            label: A geolocation field
        image:
            type: image

# There can be defined the templates for the template chooser
templateselect:
    templates:
         - name: 'Template with extra fields'
           filename: 'extrafields.twig'
         - name: 'Another template with extra fields'
           filename: 'anotherextrafields.twig'
```

This isn't particularly DRY (what if we change the filename of a template?) and will lead to more issues if we come up with more metadata around templates. I think we should bundle them like so:

```yml
templates:
    record.twig:
        name: Default Template
        fields:
            # Insert fields here
```

Details
-------

 - Relevant Bolt Version: 2.2/master
