### ISSUE TITLE
[BUG] Uniqueness of field names in repeater field

### ISSUE THREAD

**Issue by andrewtheone** [bolt/bolt#5072]
```
somecontenttype:
   fields:
       title:
           type: text
       slug:
           type: slug
           uses: title
       attributes
           type: repeater
           limit: 10
           fields:
                title: 
                     type: text
       properties
           type: repeater
           limit: 10
           fields:
                title: 
                     type: text
```

Uppon saving the content, only properties title is saved, nor attributes or content's title is saved, slug is i believe generated from the content's title.

- Bolt version: master
- Database: MySQL (5)
edit:
What makes it stranger, if I have 3 attributes, and 1 properties, 0 attributes and 1 properties are saved.
