### ISSUE TITLE
[RFC] add include and group options to {{ fields() }}

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#5078]
The new `{{ fields() }}` tag has no include options, but it has some weird options like "extended" and "common".

As a theme developer I probably want to show or hide fields - it does not make sense to hide "extended" fields so the only option that is useful at the moment is the "exclude" option if I have already rendered some fields like in the following example.
```twig
{{ record.title }}
{{ popup(record.image, 100, 100) }}
{{ record.body }}
{{ fields(exclude = [ 'title', 'image', 'body']) }}
```

If would be nice to have the opposite too so only certain fields are rendered:
```twig 
<article>
  <h1>{{ record.title }}</h1>
  <div class="maincolumn">
    {{ popup(record.image, 100, 100) }}
    {{ record.body }}
    {{ fields(include = [ 'geolocation_address', 'imagelist', 'some_checkbox']) }}
  </div>
  <aside>
    {{ record.anotherhtmlfield }}
  </aside>
</article>
```

Also an option to render only a group - like the groups in `contenttypes.yml` might come in handy - so you can control the display of the following content type:
```yml
entries:
    name: Posts
    singular_name: Post
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        image:
            type: image
            group: media
        imagelist:
            type: imagelist
        video:
            type: video
    taxonomy: [ categories, tags ]
```
with this simple template:
```twig 
<article>
  <h1>{{ record.title }}</h1>
  <div class="maincolumn">
    {{ record.teaser }}
    {{ fields(include_groups = [ 'media', 'taxonomy']) }}
  </div>
  <aside>
    {{ record.body }}
  </aside>
</article>
```

Details
-------

 - Relevant Bolt Version:  3.0 / master
