### ISSUE TITLE
[BUG] Images not uploaded on templatefields

### ISSUE THREAD

**Issue by joshuan** [bolt/bolt#5134]
Upload button on imagelist field not available on the template fields tab.

Details
-------
 - Relevant Bolt Version: master
 - Install type: Github checkout
 - PHP version: 5.5
 - Used webserver: Apache 2.4
 - For UX/UI issues: OS X 10.11.4, Chrome 49

Reproduction
------------
theme.yml
```
templatefields:
    "pages/page_company.twig":
        fotos1:
            type: imagelist
            upload: office
```
contenttypes.yml
```
pages:
    fields:
        fotos2:
            type: imagelist
            upload: office
        template:
            type: templateselect
            filter: 'pages/page_*.twig'
```
On main tab upload to fotos1 available and upload to fotos2 "Upload not allowed"
