### ISSUE TITLE
Imagelist in templatefields is quirky: Doesn't "stick", Stack not working.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5142]
Let's say we have this: 

```
templatefields:
    extrafields.twig:
        text2:
            type: text
        fotos2:
            type: imagelist
            upload: office
        image:
            type: image
```

It looks OK, but the imagelist field isn't working correctly. See screenshot: 

![screen_shot_2016-04-07_at_09_49_44](https://cloud.githubusercontent.com/assets/1833361/14344171/4d2ff97c-fca6-11e5-944f-727a502cb2ea.png)

Additionally, the value in the field is gone after a page-refresh. 

The value _is_ saved in the DB: 

![screen shot 2016-04-07 at 09 54 29](https://cloud.githubusercontent.com/assets/1833361/14344247/c5dd5d24-fca6-11e5-8323-b390875f9fce.png)

But upon retrieval of the page, it's there, but I'm guessing it has a few too many backslashes: 

![screen shot 2016-04-07 at 09 56 51](https://cloud.githubusercontent.com/assets/1833361/14344298/208cbb16-fca7-11e5-81e6-d0df4fd898b4.png)
 

Details
-------

 - Relevant Bolt Version: [ master ]
