### ISSUE TITLE
Templatefields (and repeaters) should NOT allow templateselect.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5143]
You can currently do this: 

```
templatefields:
    extrafields.twig:
        template:
            type: templateselect
            filter: 'pages/page_*.twig'
```

Which will put the template selector on the template tab, _if_ there are template fields. 

![screen shot 2016-04-07 at 10 16 26](https://cloud.githubusercontent.com/assets/1833361/14344749/d03450a4-fca9-11e5-8874-7071a021b8fc.png)

You'll only see the templatefield selector on a certain selection of templates. It just doesn't make sense to allow recursive selection of the used template. For a more thorough explanation of this, see #5143.
