### ISSUE TITLE
Routing: Weird behavior on custom bindings

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5211]
This is the first time I tinker with the custom route bindings. For testing, I enabled chapter route binding in the `routing.yml`

```
chapterbinding:
    path: /{chapters}/{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: showcases
        chapters: showcase
    requirements:
        chapters: [ controller.requirement:singleTaxonomy, [chapters, showcase] ]
    contenttype: showcases
```

I have the 3 standard chapter `main`, `meta` and `other`.

Now I have the record with the id `5` in the main chapter but can access it with this URLs:
- `/main/5`
- `/meta/5`
- `/other/5`
- `/showcase/5`

The direct record link generated from the backend is `/showcase/5` because that's the fallback.

Same with the category-binding. I can access the record via a category which is not applied to the record.

This doesn't seem to be the correct behavior, right?
## Details
- Relevant Bolt Version: 3 Beta 2
- Install type: composer
- PHP version: 7.0.4
- Used webserver: php-dev

**Comment by PhillippOhlandt** [comment]
I also tested the `datecreated` example from here: https://docs.bolt.cm/master/templates-routes#routing

My code:

```
pagebinding:
    path: /{datecreated}/{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: page
        datecreated: "2222-22-22"
    requirements:
        datecreated: \d{4}-\d{2}-\d{2}
    contenttype: pages
```

I had to add the default `datecreated` otherwise the backend would throw an error. The backend also always use the default `2222-22-22` then.

The frontend generates the correct links with the real creation date. But it's the same as above, I can change the date in the URL like I want, it doesn't matter, I still get the record.
