### ISSUE TITLE
[BUG] performance with multiple repeater fields

### ISSUE THREAD

**Issue by d-m-** [bolt/bolt#5214]
Hi!

Objects that have a contenttype with multiple repeater fields and a modest amount of rows in the repeaters suffer from incredibly large access times in the backend (such that they become useless on typical server configurations).

Some data:
------
* After adding three additional repeaters to the showcase contenttype (see below), a fresh showcase (having only a title) can be accessed in ~400ms on my system.
* Adding three items to each repeater using only the repeatertitle fields: 4500ms to load after save.
* After adding 6 additional items (in total): 23 seconds.

This is due to a single query:
![screenshot](https://cloud.githubusercontent.com/assets/8940346/14598588/49ea61d4-0553-11e6-9e11-8e2f024b82c8.jpg)

Details
-------

 - Relevant Bolt Version: [ 2.2 | 3.0 | master ]
 - Install type: github
 - PHP version: 7
 - Used webserver: php built-in

I reproduced this also on other systems

Reproduction
------------

* install bolt with default config
* add the following to the showcase contenttype:
```        
      repeater2:
            type: repeater
            fields:
                repeattitle2:
                    type: text
                repeatimage2:
                    type: image
                    extensions: [ gif, jpg, png ]
                repeatcontent2:
                    type: html
        repeater3:
            type: repeater
            fields:
                repeattitle3:
                    type: text
                repeatimage3:
                    type: image
                    extensions: [ gif, jpg, png ]
                repeatcontent3:
                    type: html
        repeater4:
            type: repeater
            fields:
                repeattitle4:
                    type: text
                repeatimage4:
                    type: image
                    extensions: [ gif, jpg, png ]
                repeatcontent4:
                    type: html
```
* create a new showcase
* add some content to the repeaters
