### ISSUE TITLE
[BUG] Repeater fields with multiple select not saving as json

### ISSUE THREAD

**Issue by mikenosko** [bolt/bolt#5225]
Let say I have a repeater field with fields defined as:

```
...
        question:
            type: repeater
            group: questions
            limit: 10
            fields:
                validation:
                    type: select
                    multiple: true
                    choices: [...]
...
```

The form it creates renders correctly but on save it saves into the value_text and not value_json in bolt_field_value table (I'm using sqlite).

Also after reloading the edited page data isn't pre-filled in the relevant field.

The multiple select works fine when not repeater.

Details
-------

 - Relevant Bolt Version: [ 3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
