### ISSUE TITLE
[RFC] Repeater fields: Allow for multiple subtypes / blocks

### ISSUE THREAD

**Issue by psren** [bolt/bolt#5307]
The new repeater type is great.
You can repeat 1 to n elements of the same type.

It would be cool if you could select between different possible types there.
## Details
- Relevant Bolt Version: [ 3.1 | 4.0 | master ]
## Intention

Allow for something "pagebuilder-like"
## Idea

``` yaml
      repeater:
            type: repeater
            group: repeater
            limit: 3
            prefix: "<p>This allows you to create multiple sets of fields. Use the add button at the bottom to create a new empty set.</p>"
            fields:
                repeatabletexttype:
                   repeattitle:
                       type: text
                   repeatimage:
                       type: image
                       extensions: [ gif, jpg, png ]
                   repeatcontent:
                       type: html
               repeatableothertype:
                   repeattitle:
                       type: text
```

Implementation in Sulu CMF looks like that.

![bildschirmfoto 2016-05-12 um 13 25 28](https://cloud.githubusercontent.com/assets/1016798/15213182/d4570854-1845-11e6-9652-0fba3a3fc946.png)
(Like in Bolt 3.0)

![bildschirmfoto 2016-05-12 um 13 25 31](https://cloud.githubusercontent.com/assets/1016798/15213187/e13b724e-1845-11e6-8781-c3a6b650c8ea.png)
One can add multiple types in custom order. This allows for a "pagebuilder" experience with custom elements.

![bildschirmfoto 2016-05-12 um 13 26 00](https://cloud.githubusercontent.com/assets/1016798/15213198/fc050f36-1845-11e6-8dca-f4c17639dff7.png)
The type of a element can be changed, too.

**Comment by Pinpickle** [comment]
This was in the original RFC for the repeating spec, and was known as "block" fields:

https://github.com/bolt/bolt/issues/3267

**Comment by psren** [comment]
And has it been implemented? I couldn't find it anywhere in the Docs or relase notes

**Comment by bobdenotter** [comment]
psren. Not yet, We're soon going to solidify the plans for 3.1 and onwards. For now, it's just the repeaters as-is, and the templatefields that are at your disposal.

**Comment by psren** [comment]
Ah okay. Should i leave this open since the others RFC is closed?

**Comment by SahAssar** [comment]
psren: yep, this should probably be kept open.

**Comment by dantleech** [comment]
what would be nice here (and something that I wanted to do in Sulu) is to have just references to types which are defined elsewhere:

```yaml
repeater:
    type: repeater
    group: repeater
    limit: 3
    prefix: "<p>This allows you to create multiple sets of fields. Use the add button at the bottom to create a new empty set.</p>"
    default_type: hotel
    types:
        - hotel
        - car
```

and have those "types" defined somewhere else:

```yaml
contentblocks: # or maybe contentmixins
    hotel:
        name:
            type: text
        starts:
            type: integer
    car:
        name:
            type: text
        model:
            type: text
```

This will allow for reuse of fiddly blocks which would otherwise be duplicated and make the YAML more legible.

Such definitions could also be included to compose content types etc. somehow.

Just putting that idea out there..
