### ISSUE TITLE
Using hyphens in taxonomies breaks stuff

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5338]
Details
-------

 - Relevant Bolt Version: [  master ]

Reproduction
------------

Add this to taxonomy.yml:

```
foo-tags:
    slug: foo-tags
    singular_slug: foo-tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
```

```

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
    taxonomy: [ foo-tags ]
    recordsperpage: 100
```

Then, editing an (exisitng) 'page' will give the following error: 

```
An exception occurred while executing 'SELECT content.*, GROUP_CONCAT(incomingrelation.id) as _incomingrelation_id, GROUP_CONCAT(incomingrelation.from_id) as _incomingrelation_fromid, GROUP_CONCAT(incomingrelation.from_contenttype) as _incomingrelation_fromcontenttype, GROUP_CONCAT(foo-tags.id ORDER BY foo-tags.id ASC) as _foo-tags_id, GROUP_CONCAT(foo-tags.slug ORDER BY foo-tags.id ASC) as _foo-tags_slug, GROUP_CONCAT(foo-tags.name ORDER BY foo-tags.id ASC) as _foo-tags_name, GROUP_CONCAT(foo-tags.taxonomytype ORDER BY foo-tags.id ASC) as _foo-tags_taxonomytype FROM bolt_activiteiten content LEFT JOIN bolt_relations incomingrelation ON content.id = incomingrelation.to_id AND incomingrelation.to_contenttype='activiteiten' LEFT JOIN bolt_taxonomy foo-tags ON content.id = foo-tags.content_id AND foo-tags.contenttype='activiteiten' AND foo-tags.taxonomytype='foo-tags' WHERE content.id = ? GROUP BY content.id, content.id' with params ["1"]:\n
\n
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-tags_id, GROUP_CONCAT(foo-tags.slug ORDER BY foo-tags.id ASC) as _foo-tags_slug' at line 1
"""
```

**Comment by GawainLynch** [comment]
Have you pulled in yesterday's fix?

**Comment by bobdenotter** [comment]
@GawainLynch Yes, up to date. Note that this is in *taxonomies*, and not in *contenttypes* :-)

**Comment by GawainLynch** [comment]
>  Note that this is in taxonomies, and not in contenttypes 

@bobdenotter: Since when did you start thinking I could read :laughing:

**Comment by bobdenotter** [comment]
Here's the full stack dump, for those interested: 

```
Bolt - Fatal error.
Class: Doctrine\DBAL\Exception\SyntaxErrorException
Message: An exception occurred while executing 'SELECT content.*, GROUP_CONCAT(incomingrelation.id) as _incomingrelation_id, GROUP_CONCAT(incomingrelation.from_id) as _incomingrelation_fromid, GROUP_CONCAT(incomingrelation.from_contenttype) as _incomingrelation_fromcontenttype, GROUP_CONCAT(foo-tags.id ORDER BY foo-tags.id ASC) as _foo-tags_id, GROUP_CONCAT(foo-tags.slug ORDER BY foo-tags.id ASC) as _foo-tags_slug, GROUP_CONCAT(foo-tags.name ORDER BY foo-tags.id ASC) as _foo-tags_name, GROUP_CONCAT(foo-tags.taxonomytype ORDER BY foo-tags.id ASC) as _foo-tags_taxonomytype FROM bolt_activiteiten content LEFT JOIN bolt_relations incomingrelation ON content.id = incomingrelation.to_id AND incomingrelation.to_contenttype='activiteiten' LEFT JOIN bolt_taxonomy foo-tags ON content.id = foo-tags.content_id AND foo-tags.contenttype='activiteiten' AND foo-tags.taxonomytype='foo-tags' WHERE content.id = ? GROUP BY content.id, content.id' with params ["1"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-tags_id, GROUP_CONCAT(foo-tags.slug ORDER BY foo-tags.id ASC) as _foo-tags_slug' at line 1
Code: 0
Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php, line 116

Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php, line 836

Doctrine\DBAL\Connection->executeQuery()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php, line 206

Doctrine\DBAL\Query\QueryBuilder->execute()
[root]//src/Storage/Repository.php, line 92
[]
Bolt\Storage\Repository->find()
[root]//src/Controller/Backend/Records.php, line 78
array:1 [▼
  0 => "1"
]
Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]//vendor/symfony/http-kernel/HttpKernel.php, line 62

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, line 586

Silex\Application->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, line 563

Silex\Application->run()
[root]//index.php, line 14
[]
```

**Comment by Twiebie** [comment]
Running into the same problem when using a hyphen in a contenttype.

**contenttypes.yml:**
```
foo-bar:
    table_name: foo_bar
    name: Foo Bar
    slug: foo-bar
    singular_name: Foo Bar
    singular_slug: foo-bar
```

Then trying to create a new 'Foo Bar' results throws an error:

```
Bolt\Exception\StorageException thrown with message "Attempted to load mapping data for unmapped class foo-bar"

Stacktrace:
#9 Bolt\Exception\StorageException in /home/vagrant/code/sites/erac.dev/vendor/bolt/bolt/src/Storage/Mapping/MetadataDriver.php:371
#8 Bolt\Storage\Mapping\MetadataDriver:loadMetadataForClass in /home/vagrant/code/sites/erac.dev/vendor/bolt/bolt/src/Storage/EntityManager.php:256
#7 Bolt\Storage\EntityManager:getRepository in /home/vagrant/code/sites/erac.dev/vendor/bolt/bolt/src/Controller/Base.php:337
#6 Bolt\Controller\Base:getRepository in /home/vagrant/code/sites/erac.dev/vendor/bolt/bolt/src/Controller/Backend/Records.php:74
#5 Bolt\Controller\Backend\Records:edit in /home/vagrant/code/sites/erac.dev/vendor/symfony/http-kernel/HttpKernel.php:139
#4 call_user_func_array in /home/vagrant/code/sites/erac.dev/vendor/symfony/http-kernel/HttpKernel.php:139
#3 Symfony\Component\HttpKernel\HttpKernel:handleRaw in /home/vagrant/code/sites/erac.dev/vendor/symfony/http-kernel/HttpKernel.php:62
#2 Symfony\Component\HttpKernel\HttpKernel:handle in /home/vagrant/code/sites/erac.dev/vendor/silex/silex/src/Silex/Application.php:586
#1 Silex\Application:handle in /home/vagrant/code/sites/erac.dev/vendor/silex/silex/src/Silex/Application.php:563
#0 Silex\Application:run in /home/vagrant/code/sites/erac.dev/public/index.php:14
```
