### ISSUE TITLE
BUG Not able to use - (hyphen) in field name for repeating fields

### ISSUE THREAD

**Issue by kupalizer** [bolt/bolt#5348]
It is possible to use hyphen in the field name(contenttypes.yml) but the repeater field values are not gong to be read in the bolt admin edit field section

example:
```
price-new:
            type: repeater
            group: prices
            fields:
                price:
                    type: integer
                year
                    type: integer
```

Details
-------

 - Relevant Bolt Version: [ 3.0.1 ]
 - Install type: [Composer install ]
 - PHP version: [ 5.6.10 ]
 - Used webserver: [ Apache  ]
