### ISSUE TITLE
Fields added to `group: taxonomy` in contenttypes break in Bolt 3. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5368]
For example, this: 

```
        headercolor:
            type: select
            values: [ zwart, wit ]
            group: taxonomy
```
