### ISSUE TITLE
[RFC] Create a "stacked" content type route

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#5404]
Hi all,

my current task is to implement a route which can stack content types.
> Look at contenttype1 first and at contenttype2 second. Display the first contenttype you found.

I think it's a common task that contenttypes share the same route.

## Details
If you have two content types `page` and `landingpage` and you need them to listen to the same route, you currently can't solve it.

## Example
Contenttype 1: `landingpage`
Contenttype 2: `page`

You have an entry for `page`:
Ordinary page type
```
title: Contact
slug: contact
body: Text for contact with own template and form etc
```

You have an entry for `landingpage`:
Very special type. Always the same template but totally different to page.
```
title: Washington
slug: washington
leftText: Text to describe your service for Washington
rightTeaser: Another field which is needed
```

The route should know that it needs to check the `page` contenttype first and if there is no one found, the `landingpage` contenttype.
```yaml
pagebinding:
  path:              /{slug}
  defaults:          { _controller: 'Bolt\Controllers\Frontend::stackedRecord', 'contenttypeslugs': ['page', 'landingpage'] }
  contenttype:       ['pages', 'landingpages']
  requirements:
    contenttypeslugs: 'Bolt\Config\Requirement::anyContentType'
```

I created an action for the Frontend controller. I will post it with a PR if you want to. But I have no tests written yet.
