### ISSUE TITLE
For site migrators, a redirects.yml file

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#544]
Over time, and as Bolt improves, developers will start moving over from another CMS, or simple website file structure. As such, and in terms of redirecting old pages to new ones, SEO should be considered.

Let's consider this: I'm migrating my old site over to Bolt, and I need to send a 301 Moved Permanently response for specific URIs to make Google and friends happy. I'd want to be able to do this in a `redirects.yml` file, or even, perhaps, the admin panel itself. Let's say we were doing it with the YAML file:

``` yml
redirects:
    services:
        request: /services.html
        path: services
    webdesign:
        request: /services/web-design.html
        path: services/1 OR path: services/web-design
```

We could maybe even consider using wilcards or named routes:

``` yml
redirects:
    pages:
        requestpattern: /{page}.html
        pathpattern: /page/{page}
```

For compatibility, and the reduction of conflict, we could even specify regex patterns for each placeholder:

``` yml
redirects:
    pages:
        requestpattern: /{page}.html
        pathpattern: /page/{page}
        where:
            page: "[a-z0-9-_]+"
```

With 1.2 just around the corner, perhaps getting a redirect to point to a specified route in `routes.yml`?

``` yml
redirects:
    pages:
        requestpattern: /{page}.html
        route: pagebinding
```

If `pagebinding`'s `path` was set to `/{slug}`, any request for `/about.html` would redirect to `/about`. That way, we could change the route if we wanted to, and the redirect would still work.

@bobdenotter, do you think this is viable?
