### ISSUE TITLE
[BUG] Video field does not work (sometimes) when used w/markdown (+ repeater?) field

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5470]
When I add a video field on a contenttype with a markdown field the "refresh" button does not work and the video metadata is not retrieved. If I remove the markdown type it works as expected.

**edit**: This does work with only a markdown and video field, will try and narrow the problem down.

Cannot reproduce this at the moment, the full contenttype is:

``` yaml
footype:
    name: homepages
    singular_name: Homepage
    fields:
        # main
        title:
            label: Titre
            type: text
            class: large
            group: Foobar
            default: Some default
        subtitle:
            label: Sous-titre
            type: text
            group: Foobar
            default: Some default

        # présentation
        presentation_title:
            label: Titre
            type: text
            class: large
            group: Présentation
            default: Qui Sommes Nous?
        presentation_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            class: large
            group: Présentation
            default: Présentation

        # actualities
        actualities_title:
            label: Titre
            type: text
            class: large
            group: Actualités
            default: Actualités
        actualities_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            class: large
            group: Actualités
            default: Présentation

        # prez-de-chez-vous
        chezvous_title:
            label: Titre
            type: text
            class: large
            group: Règions
            default: Près de chez vous!

        soutenir_title:
            label: Titre
            type: text
            class: large
            group: Soutenir
            default: Près de chez vous!
        soutenir_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            group: Soutenir
            default: Ensemble soutenons la recherche
        soutenir_items:
            label: Links
            type: repeater
            group: Soutenir
            limit: 3
            fields:
                title:
                    label: Titre
                    type: text
                    default: Devenir Adhérant
                image:
                    label: Image
                    type: image
                    extensions: [ gif, jpg, png ]
                content:
                    label: Contenu
                    type: textarea
                link:
                    label: Lien
                    type: text

        # misc
        youtube_title:
            label: Chaine Youtube
            type: video
            group: Youtube
```

Will have to investigate again later
