### ISSUE TITLE
[BUG] repeater fields not working with markdown field type

### ISSUE THREAD

**Issue by flrvt** [bolt/bolt#5489]
My `page` content type has two repeater fields. Each of which contain body text.

Because of issue #5469 I changed the body text fields to `markdown` instead of `html` but I am still encountering problems.

My repeaters don't work when there are `markdown` fields in it. They do if I replace them with `textarea` fields.
The 'Add new ... set' button appears but a javascript error is logged in the console when clicked upon (also when the page loads):
```
bolt.js?46353df487:9 Uncaught TypeError: Cannot read property '$' of undefined
```

my contenttypes.yml:
```yml
pages:
    name: Pages
    singular_name: Page
    fields:
        content:
            type: repeater
            group: content
            fields:
                title:
                    type: text
                    variant: inline
                    class: large
                subtitle:
                    type: text
                    variant: inline
                body:
                    type: markdown
                    height: 200px
        show_features:
            type: checkbox
            label: 'Show features'
            group: features
        features:
            type: repeater
            limit: 4
            fields:
                icon:
                    type: image
                title:
                    type: text
                    variant: inline
                    class: narrow
                body:
                    type: markdown
                    height: 200px
                btn_label:
                    type: text
                    variant: inline
                    class: narrow
                    label: 'Button label'
                btn_url:
                    type: text
                    variant: inline
                    label: 'Button link'
    recordsperpage: 100
    default_status: published
```

Details
-------

 - Relevant Bolt Version: 3.0.7
 - Install type: Composer install
 - PHP version: 7.0
 - Used webserver: Apache

Reproduction
------------

 1. Do a clean install of Bolt 3.0.7 via composer
 2. Configure the pages content type as described above
 3. Create a new page and see the behaviour
