### ISSUE TITLE
[RFC] Consider using hints on more fields in the backend

### ISSUE THREAD

**Issue by EzeRangel** [bolt/bolt#5513]
Details
-------
I was thinking it would be nice and useful for the client who will use the backend, to make hints like multimedia (geolocation, video, image, etc) available to other fields like html or textarea.

I know the prefix/postfix option was created for that reason but there are cases the explanation of the field is too large that cannot be presented very well.

Maybe something like this.
```
contenttype:
  ...
  ...
  fields:
    textarea:
      type: textarea
      hint: "You can write up a large amount of text here, explaining the client what is the purpose of these field."
```
