### ISSUE TITLE
Select by records does not work with multiple fields.

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5517]
f.e. this from the default bolt setup:

```yaml
        selectentry:
            type: select
            values: entries/id,title
            postfix: "Select an entry"
            autocomplete: true
            sort: title
```

![bug](https://cloud.githubusercontent.com/assets/530801/16626485/fa916ea2-43a0-11e6-9835-452d04c94b29.png)

Both entries have a title:
