### ISSUE TITLE
Underscores in taxonomies (tags) break admin input

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#5543]
If you use `behaves_like: tags` in taxonomies, the admin interface for content type creation is broken. In `3.0.3` the tags no longer prefilled and in `3.0.10` the tag field never shows up.

Details
-------

 Bolt Version: `3.0.2` and `3.0.10`

Reproduction
------------

Buggy tags
```
teaser_tags:
    name: Teaser Tags
    slug: teaser_tags
    singular_name: Teaser Tag
    singular_slug: teaser_tags
    behaves_like: tags
    allow_spaces: false
```

"Fixed" tags
```
teasertags:
    name: Teaser Tags
    slug: teasertags
    singular_name: Teaser Tag
    singular_slug: teasertags
    behaves_like: tags
    allow_spaces: false
```

Obviously the fix is not using `_` and rename the taxo to `teasertags`.
