### ISSUE TITLE
[RFC] Successor to templatefields

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#5545]
I'll start with the caveat that this probably won't be a feature until 4.0 but it may also be the case that we need to start doing some preparatory work in the 3.x series so now is as good a time as any to start getting some comments.

As you may or may not know, the current implementation of Templatefields, whilst a very useful end-user feature is not ideal from a storage point of view, it uses a fair amount of complicated code to bolt into the current setup and also the end result is stored as an encoded json field.

So, the challenge is, how best do we supercede/replace the current implementation.

One initial idea, is that we make a more flexible concept of 'Value dependent fields' that is a set of fields that are only shown when the value of another field is equal to xxxx.

That would allow us to do the equivalent to templatefields which shows a set of fields when the template field is equal to xxxx.twig but it also opens up other possibilities such as survey type fields, show these questions if the answer to question 1 is xxxxx.

So...
1. Are value dependent fields the best way to attack this?
2. Let's have ideas for the configuration syntax in `contenttypes.yml` / `theme.yml`
3. Any better ideas?
4. Would appreciate it if anyone wants to help out on the UI side once we get to implementation, since a fair amount of functionality will need to be handled via javascript.

**Comment by SahAssar** [comment]
Stepping back for just a second, what is the goal for refactoring/replacing templatefields? It's a hacky implementation and does not fit well with the rest of the storage, but is the goal to "just" fix that or go beyond (for 4.0)?

While 'Value dependent fields' would be awesome, it requires a lot more FE work than changing how the storage for it works (I'm not at all saying changing storage does not require much work, I know this is very complicated and appreciate the work very much, just saying it does not probably require FE work, and currently it seems like we have more BE persons than FE persons). So basically it is up to how much time @rarila (and how much time he is willing to teach probably me, and perhaps phillipp) can put in if I understand this right since it will require hot-loading of basically every field and also making extension fields hot-loadable (which is probably a huge job since they can differ so much).

That said, lemme say this:

1/2. This goes back to how much freedom a theme author should have versus a site config... Personally I'd like that they are in theme.yml so that one can ship a theme with pre-configed fields and if the fields are "template specific" they should probably be in the template, right?

3; No better ideas here...

4. I'd love to help out, but as above I think I need rarila's help to do so,

**Comment by GawainLynch** [comment]
> it uses a fair amount of complicated code to bolt into the 

I see what you did there :wink: 

> While 'Value dependent fields' would be awesome, it requires a lot more FE work than changing how the storage for it works [… plus disclaimer]

Well, Ross has his hands up so far on the work, but having had no small amount of time invested in the storage work that went into 3.0, I'd have to say I don't agree.

Templatefields is apparently a great **concept**, but how it hooks into Bolt in v2, and the sacrifices we had to make to even get it to work in v3 is the stuff of nightmares … it has been a massive amount of work — I spent a couple of weeks on it before giving up and handing it back to Ross, who then spent another month — and cleaning it up is going to be more hellish "fun".

TBH, if the vote solely  was mine, I'd rip it out completely for v4 and let someone have a go in extension-land.

> Are value dependent fields the best way to attack this?

I can't think of a better one right now, but would be in favour of collectively defining a direction and iterating over said direction — maybe something we enable with a "experimental" config flag during 3.x to mitigate BC.

> Let's have ideas for the configuration syntax in contenttypes.yml / theme.yml

I'd have to see more of the idea for how my brain works

> Any better ideas?

Rip it out! Get rid of it! :fire: 

> Would appreciate it if anyone wants to help out on the UI side once we get to implementation, since a fair amount of functionality will need to be handled via javascript.

This is where I think we need to look at this stuff form bus-factor … @rarila only has so much time, and we can't hold up the progression of that work as a result.

There is no shortage of talented UI people in our community, and it is well and truly time this area got some sponsorship type attention so that @rarila can focus more on what needs to be done and @bobdenotter , @SahAssar & @PhillippOhlandt are good people to help that happen. :wink:

**Comment by rossriley** [comment]
Ok, thought I'd flesh out what I was thinking so that we know better what we are talking about.

From a backend point of view we could re-use a lot of the code / concepts from Repeaters, so we can view the 'data formerly known as templatefields' as a field collection, identical to a single component of a repeating field collection. That means that values can be stored properly in the db rather than in JSON as they currently are.

For syntax I was thinking something along these lines:

```
# Current specification in theme/config.yml
templatefields:
  extrafields.twig:
    section_1:
      type: text
      label: Section 1
    section_2:
      type: html
      label: Section 2
    image:
      type: imagelist
        

# Would become: (pages = name of contenttype to add to) 				
fields:
  pages: 
	extrafields:
	  type: dependent
	  watch: template
	  value: extrafields.twig
	  fields:		
	    section_1:
	      type: text
	      label: Section 1
	    section_2:
	      type: html
	      label: Section 2
	    image:
	      type: imagelist				
```

The main change here is that we allow the theme to add normal fields, effectively allowing additions to `contenttypes.yml` the new `dependent` field type watches another field for a specific value and when they match the new fields should get shown.

In terms of UI we can copy the strategy of repeaters in that we output an HTML template for the above fields, but don't render them, then add a JS listener to the field specified in the `watch` variable, once that matches then we copy the HTML template into the DOM and they become a standard part of the form submission.

**Comment by GawainLynch** [comment]
> data formerly known as templatefields

We shall now only refer to them as ![](https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Prince_logo.svg/25px-Prince_logo.svg.png)

**Comment by GawainLynch** [comment]
I may be missing the obvious here, but what if you don't want to "watch", but just do similar to what happens in a TF now?

**Comment by PhillippOhlandt** [comment]
@GawainLynch I think thats what Ross' example is, it watches the templateselect field for a specific value (a template name). 

I like the proposed YML structure from Ross.

**Comment by graham73may** [comment]
I've had to implement conditional fields in for a project I'm working on at the moment. I've added this to the store as: https://github.com/graham73may/bolt-conditional-fields

```
# The condition array
    condition:
    # The trigger field (check the fields id in the HTML)
        field: fieldname | taxonomy-taxonomyname
    # The operator to test the condition with
        operator: = | !=
    # If the condition is met, show or hide this field
        show: true | false 
    # The values to match the condition against  
        value: [ '' ] | [ a,b,c] | { "a":'A', "b":'c' } 
```

Which you would use on a field as such:

```
map:
    label: "Map"
    type: geolocation
    condition:
        field: template
        operator: '='
        show: true
        value: [ "page-contact.twig" ]
```

Full config examples in the git README.

The plugin itself is mostly javascript that shows/hides bolt-fieldsets, so any bugs should only have minor implications (e.g. something being hidden incorrectly).
