### ISSUE TITLE
Bug: disabling news block in dashboard

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#5549]
Looks like the ability to hide Bolt news on the dashboard doesn't work.
Tested the following config setting on 2 Bolt 3.0.10 installs.

```
# Options for backend user interface
backend:
    news:
        disable: true     # Disable news panel. Defaults to false. "Alerts" will still be shown.
#    stack:
#        disable: true     # Disable stack usage. Defaults to false.
```

Bolt 3.0.10
