### ISSUE TITLE
Error with custom field type in templatefields

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5562]
```
Unknown column type "flexiselect" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). 
```

Defintiion in `theme.yml`

```yaml
templatefields:
    foobar/pages/page_homepage.twig:
        partenaires:
            type: flexiselect
            value_service: barf.foo.repository.generic
            value_method: homepagePartnairesForSelect
            option_template: partenaires/_flexiselect_option.twig
```

The field definition:

```php
class FlexiSelectField extends FieldTypeBase
{
    public function getName()
    {
        return 'flexiselect';
    }

    public function getTemplate()
    {
        return '_flexiselect.twig';
    }

    public function getStorageType()
    {
        return 'json_array';
    }
}
```

Works in non-template fields:
