### ISSUE TITLE
[BUG] current() twig filter always returns false when running bolt in a subfolder

### ISSUE THREAD

**Issue by gandalf3** [bolt/bolt#5585]
Currently active menu items are not styled any differently.
Dumping `item|current` and `item.record` from within the for loop in  `base-2016/partials/_sub_menu.twig` shows that the `current()` twig function appears to only return false, and [`item.record`](https://docs.bolt.cm/3.0/content/menus) is `null`.

**Added after debugging:** This is because the current() twig filter always returns false when running bolt in a subfolder.

Details
-------

 - Relevant Bolt Version: 3.0.11 (worked in bolt 2)
 - Install type: Zip/tarball
 - PHP version: 7.0.8
 - Used webserver: Apache 2.4.23

Reproduction
------------

1. Create a new bolt installation (In a subfolder)
2. View the sample site, and note that menu items referring to the current record are not getting the "active" class they should be
3. Dump `item.record` from inside the for loop in `base-2016/partials/_sub_menu.twig`. It returns null, suggesting that `current()` returning false is just a symptom of the real issue.

On my installation:
* `base-2016/partials/_sub_menu.twig` does indeed test `item|current` on line 23
* `config/menu.yml` defines paths, not links

No visible error messages are produced.

**Comment by SahAssar** [comment]
Could you post your menu.yml? Cause it seems to work for me (although this is on a git install):

![image](https://cloud.githubusercontent.com/assets/5096632/17116223/152e1f6a-52b7-11e6-8c9a-9c25caa4b97c.png)

**Comment by gandalf3** [comment]
I'm testing this on a fully [default tarball](https://bolt.cm/distribution/bolt-latest.tar.gz) install, nothing modified.

```
# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/content/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Second item
      path: entry/1
      submenu:
          - label: Sub 1
            path: entry/2
          - label: Sub 2
            class: menu-item-class
            path: entry/3
          - label: Sub 3
            path: entry/4
          - label: Sub 4
            class: sub-class
            path: page/3
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last
```
