### ISSUE TITLE
HTML field in repeater doesn't work if not the last in the field set.

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5596]
I thought I had already created a bug report for this, but I don't think I did.

Works:

```
examples:
    name: examples
    singular_name: example
    fields:
        text:
            type: textarea
        sections:
            type: repeater
            fields:
                image:
                    type: image
                afficher:
                    type: select
                    values: [ "Gauche", "Doite" ]
                text:
                    type: html
```

Doesn't work:

```
examples:
    name: examples
    singular_name: example
    fields:
        sections:
            type: repeater
            fields:
                image:
                    type: image
                afficher:
                    type: select
                    values: [ "Gauche", "Doite" ]
                text:
                    type: html
        text:
            type: textarea
```

![brok](https://cloud.githubusercontent.com/assets/530801/17153228/8d4024c8-5373-11e6-87e0-9c0780f70be2.png)

Tested with bolt v3.0.10

(super helpful) Javascript error:

```
TypeError: c is undefined bolt.js:8:8921
```
