### ISSUE TITLE
[BUG] contenttypes and underscores

### ISSUE THREAD

**Issue by gonoszcsiga** [bolt/bolt#5601]
Hi, I trying to update my Bolt 2 to Bolt 3 and contenttypes.yml is giving me an error. I used underscores everywhere, but Bolt 3 doesn't like this.

Reproduction
------------
Create a content type in contenttypes.yml:
```yaml
foo_bars:
    slug: foo_bars
    singular_slug: foo_bar
    fields:
        title:
            type: text
            required: true
        slug:
            type: slug
            uses: title
    relations:
        foo_bars:
            multiple: true
```
and you will get this message on admin:

___"In the contenttype for 'Foo_bar', the relation 'foo-bars' is defined, which is not a valid contenttype. Please edit contenttypes.yml, and correct this."___

Details
-------

 - Relevant Bolt Version: 3.0.11
 - Install type: trying to update my Bolt 2 to Bolt 3 :)
 - PHP version: 7.0
 - Used webserver: Nginx 1.10.0

The relevant lines in Config.php parseContentType() function:
```php
        // when adding relations, make sure they're added by their slug. Not their 'name' or 'singular name'.
        if (!empty($contentType['relations']) && is_array($contentType['relations'])) {
            foreach (array_keys($contentType['relations']) as $relkey) {
                if ($relkey != Slugify::create()->slugify($relkey)) {
                    $contentType['relations'][Slugify::create()->slugify($relkey)] = $contentType['relations'][$relkey];
                    unset($contentType['relations'][$relkey]);
                }
            }
        }
```
The error happens when ```$relkey``` is compared to slugified ```$relkey``` and it doesn't match, after this it unsets my correct foo_bars key and it set an incorrect foo-bars.

Solution?
---------------
My solution currently is to rename the slug value and the relations key to foo-bars and hope it doesn’t break anything elsewhere. 
But it is definitely a bug, because nowhere to be found in the documentation: "do not use underscores in the slug values". :)

My thoughts:

The content type slug (I prefer calling this code) calculation is very weird in Bolt. Using the slugified key (if not numeric) or slug (without! slugify) or slugify the name... it is complicated. Why not using one required value for this purpose?
