### ISSUE TITLE
Bold 3.0.11 – Taxonomy from Bolt 2.X error – content may be created, but reopening for edit is not possible

### ISSUE THREAD

**Issue by lexislav** [bolt/bolt#5612]
I am updating older website from Bolt 2.X to Bolt 3.0.11.
The same taxonomy definition does'n work in bolt 3.0.11.
The issue can be easily replicated by adding taxonomy bellow to clean Bolt3 install, for exampel to Entries.

When saving content, the Error message appears, but the content is saved.
Listed contetnt cann't be reopened for edit – error message again.

Any ideas how to fix this is very wellcome.
Worked like charm in 2.X…

Details
-------

Bug „works“ on localhost (MAMP) and on production server as well.

 - Relevant Bolt Version: [ 3.0.11 | 2.X ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0.0 / 5.5 ]
 - Used webservers: [ MAMP/Apache + Apache on server ]

Critical taxonomy definition in my taxonomy.yml:

```
druhy-peciva:
    name: Druhy pečiva
    slug: druhy-peciva
    singular_name: Druh pečiva
    singular_slug: druh-peciva
    behaves_like: categories
    multiple: true
    options: { chleby: "Chleby", bagety: "Bagety", bile-pecivo: "Rohlíky, housky, hvězdičky", banketni-pecivo: "Banketní pečivo", sladke-pecivo: "Koláče, buchty a další sladkosti", vicezrne-pecivo: "Vícezrné pečivo" }
    has_sortorder: true
```

Reproduction
------------

Error message
------------
```
SyntaxErrorException in AbstractMySQLDriver.php line 90:
An exception occurred while executing 'SELECT content.*, 
GROUP_CONCAT(incomingrelation.id) as _incomingrelation_id, 
GROUP_CONCAT(incomingrelation.from_id) as _incomingrelation_fromid, 
GROUP_CONCAT(incomingrelation.from_contenttype) as _incomingrelation_fromcontenttype, 
GROUP_CONCAT(druhy-peciva.sortorder ORDER BY druhy-peciva.sortorder ASC) as _druhy-peciva_sortorder, 
GROUP_CONCAT(druhy-peciva.id ORDER BY druhy-peciva.sortorder ASC) as _druhy-peciva_id, 
GROUP_CONCAT(druhy-peciva.slug ORDER BY druhy-peciva.sortorder ASC) as _druhy-peciva_slug, 
GROUP_CONCAT(druhy-peciva.name ORDER BY druhy-peciva.sortorder ASC) as _druhy-peciva_name, 
GROUP_CONCAT(druhy-peciva.taxonomytype ORDER BY druhy-peciva.sortorder ASC) as _druhy-peciva_taxonomytype, 
GROUP_CONCAT(DISTINCT CONCAT_WS('_', f_hmotnost.name, f_hmotnost.grouping, f_hmotnost.id)) as hmotnost 
FROM bolt_pecivo content 
LEFT JOIN bolt_relations incomingrelation ON content.id = incomingrelation.to_id AND incomingrelation.to_contenttype='pecivo' 
LEFT JOIN bolt_taxonomy druhy-peciva ON content.id = druhy-peciva.content_id AND druhy-peciva.contenttype='pecivo' AND druhy-peciva.taxonomytype='druhy-peciva' 
LEFT JOIN bolt_field_value f_hmotnost ON f_hmotnost.content_id = content.id AND f_hmotnost.contenttype='pecivo' AND f_hmotnost.name = 'hmotnost' 
WHERE content.id = ? GROUP BY content.id, content.id' with params ["1"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near 
'-peciva_sortorder, GROUP_CONCAT(druhy-peciva.id ORDER BY druhy-peciva.sortorder ' at line 1
```
