### ISSUE TITLE
[RFC] Sorting contenttypes

### ISSUE THREAD

**Issue by navelpluisje** [bolt/bolt#5640]
When adding an integer field to the content type an name it sortorder it behaves like it does with the sortorder in taxonomies.
This has been tested in version 3.

```
contenttype:
  name: My Type
  singular_name: mytype
  show_in_menu: false
  show_on_dashboard: false
  sort: sortorder
  fields:
     name:
        type: text
        class: large
        label: Naam
    sortorder:
        type: integer
        min: 0
        label: Volgorde
```

This will result in:
<img width="674" alt="screen shot 2016-08-04 at 19 43 58" src="https://cloud.githubusercontent.com/assets/1625221/17413035/f65b669e-5a7f-11e6-9369-f0b642638e09.png">

The output thhough is not sorted (yet).

This happens to be an unespected feature, but would be nice if it is espected
