### ISSUE TITLE
Using ID in slugs - field does not exist

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#565]
This is in reference to #346, #348 and the newsitem at http://bolt.cm/newsitem/bolt-11-released.

The newsitem states that I can used the `id` field for my slugs ("The 'uses' value for slugs in contenttypes now support multiple fields, so you can create slugs like `'123-lorem-ipsum'` for `[id, title]`."), but the admin panel states that this field does not exist.

```
In the contenttype for 'events', the field 'slug' has 'uses: id', but the field 'id' does not exist.
```

My content type definition looks like this:

``` yml
events:
    name: Events
    slug: events
    singular_name: Event
    singular_slug: event
    fields:
        name:
            type: text
            class: large
            required: true
        slug:
            label: Permalink
            type: slug
            uses: [ name, id ]
    ...
```
