### ISSUE TITLE
[BUG] Checkboxes revert to 0 on v3.1.0

### ISSUE THREAD

**Issue by bintoro** [bolt/bolt#5705]
After upgrading to v3.1.0 (manually, from a zipfile), checkboxes on page records are saved as 0 even when they are checked.

I looked at the DOM node of a checkbox, and it does show `checked: true` and `value: "1"` before saving. I'm using SQLite as the storage backend.

Can anyone else reproduce this?

**Comment by bintoro** [comment]
Downgrading to 3.0.12 resolves the issue; reinstalling 3.1.0 introduces it again.

**Comment by GawainLynch** [comment]
@SahAssar: you've chased this one around the garden before, any idea before one starts digging?

**Comment by SahAssar** [comment]
@GawainLynch Well, sorta, but I'll need to dig some more before I'm sure. Last times in #4778 and #4997 it seems to have been a different problem, but lemme have a look tomorrow and I'll see what I see.

**Comment by bobdenotter** [comment]
I have not been able to reproduce it.. I've tried on Bolt 3.1.0, both MySQL as well as SQLite. See the short screencast: 

http://recordit.co/OYvMaMr8wD

contenttype: 

```
dummy:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        checkb:
            type: checkbox
        content:
            type: html
            height: 150px
    show_on_dashboard: true
    default_status: publish
    searchable: false
```

Can you give more info on what you're doing exactly?
