### ISSUE TITLE
[BUG] Backend not save field when it named with "_"

### ISSUE THREAD

**Issue by joshuan** [bolt/bolt#5713]
Example, my contenttype.yml:
```
as:
    singular_slug: a
    fields:
        title:
            type: text

bs:
    singular_slug: b
    fields:
        act_id:
            type: select
            values: as
        actid:
            type: select
            values: as
```

When i click "Save" in /bolt/editcontent/bs, bolt don't save act_id (set to NULL or default value), but normal save actid.

Details
-------
 - Relevant Bolt Version: 3.1
 - Install type: GitHub checkout
 - PHP version: 5.6
 - Used web server: Apache 2.4
