### ISSUE TITLE
[BUG] Error With Slug on ContentType definition and underscore on fields definition

### ISSUE THREAD

**Issue by acidline** [bolt/bolt#5741]
It seems there is a bug with the content type definition in yml file.

 - Relevant Bolt Version: 3.1.0
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Nginx

My Question / Bug [ I don't know ;) ]

What is the real relation between contenttype name definition and slug definition.
If I defined content type like this, I have 2 problems : 

```
adherents:
    name: Adherents
    singular_name: Adherent
    slug: Magasins
    slug_singular: Magasin
    fields:
         title:
             type: text
             group: identification
             required: true
             label: Nom de l'enseigne
         descriptif:
             type: html
             required: true
             height: 300
             label: Description
        date_start:
             type: datetime
             label: Date de début
```

**First**, Bolt detect database error, the "table bolt_magasins doesn't exists". Why Bolt wants change my table name "bolt_adherents" to "bolt_magasins" ? Slug has the priority on Entity name ?

**Second**, the date_start field is bad, field record isn't inserted in DB. But if I change date_start to datestart, it's works fine.

Thank's for your answers,

**Comment by bobdenotter** [comment]
Hi @acidline, we're aware of this. See #5601 and the linked issues for relevant information. 

In short: We're working on it, but it's more complex than it might seem at first glance. For now, please work around it by avoiding underscores.

**Comment by bobdenotter** [comment]
About the other question: `slug` is supposed to be the "machine name". for use in URLs etc. So, either do: 

```
adherents:
    name: Adherents
    singular_name: Adherent
    slug: adherents
    slug_singular: adherent
```

or: 

```
magasins:
    name: Magasins
    singular_name: Magasin
    slug: magasins
    slug_singular: magasin
```
