### ISSUE TITLE
[3.1.x] Markdown rendering regression

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#5743]
Noticed today by @PhillippOhlandt that bolt.cm wasn't rendering Markdown as HTML, rather just plain text MD source.

Reverting to 3.0.x-dev or earlier fixes problem.

Details
-------

 - Relevant Bolt Version: 3.1.0+ 
 - Install type: any

**Comment by bobdenotter** [comment]
This is prolly related to my changes in how filtering and sanitization is enforced since 3.1.0. Will look into it.

**Comment by bobdenotter** [comment]
I can't really reproduce this.. If I make a simple content type, like this: 

```
dummy:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: markdown
            height: 150px
```

Both of these will produce proper Markdown output: 
```
    {{ record.content|markdown }}

    {{ fields() }}
```

What happens on bolt.cm, is because we're doing `{{ record|excerpt(600) }}`. As far as I know, 'excerpt' has never parsed markdown, right?
