### ISSUE TITLE
[BUG] Renaming properties in a repeater in templatefields yields error

### ISSUE THREAD

**Issue by Senne** [bolt/bolt#5765]
Renaming or removing a property in a repeater in templatefields in theme.yml after you've added content to it produces the following error in the CMS:

> Invalid repeating field configuration for [property name]
## Details
- Relevant Bolt Version: 3.1.0
- Install type: Zip/tarball install
- PHP version: 5.6.10
- Used web server: Apache
## Reproduction

Step 1:  Add this to theme.yml

```
templatefields:
  index.twig:
    example:
      type: repeater
      fields:
        title:
          type: text

```

Step 2:  Fill in the title in the CMS and save it

Step 3:  Rename the "title" property to something else in theme.yml

```
templatefields:
  index.twig:
    example:
      type: repeater
      fields:
        title_other:
          type: text
```

Step 4: Go to the CMS
