### ISSUE TITLE
[BUG] datetime fields don't get updated

### ISSUE THREAD

**Issue by rwchhs** [bolt/bolt#5821]
Details
-------

 - Relevant Bolt Version: 3.1.1 ... 3.1.3
 - Install type: Zip/tarball install
 - PHP version: 7.0.9
 - Used web server: Apache 2.4.7
 - DBMS: MySQL Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
 - For UX/UI issues: Chromium 53.0.2785.116 (64-bit)

Reproduction
------------
​
**Bug summary**: 
datetime fields do not seem to get updated when edited through the backend. This appears to be independent of which locale Bolt is configured to use. However, browser and OS are using German locales, if that helps. This was observed on two different PCs/accounts. Suspiciously, no errors are being raised at any point. Not in Bolt's System Log, not in the MySQL error log, and not in apache's/php's logs.

**Steps to reproduce**:
    - Create a contenttype with a datetime field
    - Create a new item with this contenttype and put something in the datetime field using the datepicker control
    - Save/update the item
    - Reload the page

**Expected result**: 
    - On reloading the page, we should see the datetime we just entered 

**Actual result**: 
    - The datetime field is empty. No values are written to the database, even though this item is marked as having been edited. You can add other fields to this contenttype and see that they are being updated just as expected, but datetime seems broken. No error messages are being displayed (not in the JS console, either).

**Comment by bobdenotter** [comment]
Can we see the contenttype from contenttypes.yml? I can't reproduce this yet.

**Comment by rwchhs** [comment]
```YAML
tests:
    name: Tests
    singular_name: Test
    fields:
        datetime_start:
            type: datetime
            label: Datum und Uhrzeit          
            group: Veranstaltung
```

That already does it for us.
