### ISSUE TITLE
Repeating fields Saving to a Database

### ISSUE THREAD

**Issue by qooco** [bolt/bolt#5834]
Why Repeating fields stored only in "bolt_field_value" table

Why we can`t use custom tables
**example: table features**
```
id | repeattitle     | repeatimage     | repeatcontent     | contenttype    | content_id
0    row1            value                value                 pages            5
1    row2            value                value                 pages            5
2    row3            value                value                 pages            5
```

```
pages:
        title:
           type: text
        features:
            type: repeater
---->     table: features
            fields:
                repeattitle:
                    type: text
                repeatimage:
                    type: image
                    extensions: [ gif, jpg, png ]
                repeatcontent:
                    type: html
```
