### ISSUE TITLE
[BUG ?] Could not use a new specific field type on templatefields

### ISSUE THREAD

**Issue by nbehier** [bolt/bolt#5952]
When I specify a specific `field type` (from extension) on section `templatefields` of my `theme.yml` file and want to use it, it seems to launch a [500 error on saving my content](https://github.com/bolt/bolt/issues/5951) .

Details
-------

- Relevant Bolt Version: [ 3.2.0 beta 5 ]
- Install type: [ Zip/tarball install ]
- PHP version: [ 5.6 ]
- Used web server: [ Apache ]
- For UX/UI issues: [ Chrome v53 windows ]

Reproduction
------------

 1. Add `BoltFieldGeojson` to your Bolt installation, to get new field type `geojson`
 2. Change your `theme.yml` for 
```
templatefields:
    voyage.twig:
        geoinfos:
            type: geojson
            label: "Navigation"
            map:
                zoom: 13         # Initial zoom level for the default backend map (0 for all earth, 23 for house details)
                max_zoom: 18     # Max detailed zoom level for the backend map
                height: 300px    # Height for the backend map
                lat: 37.498      # Center latitude for the default backend map
                long: 23.445     # Center longitude for the default backend map
templateselect:
    templates:
         - name: 'Page de type Voyage'
           filename: 'voyage.twig'
```
 3. Open a Page, and change the template for the new one
 4. Try to save it... and get a 500 ajax error with message `DBALException in DBALException.php line 240: 
Unknown column type "geojson" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.`
