### ISSUE TITLE
Pre-filling breaks on a contenttype that has no 'title' column. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5966]
Details
-------

 - Relevant Bolt Version: [  3.2 | master ]

Reproduction
------------

Create a contenttype like: 

```
dummy_ct:
    name: Dummies_ct
    singular_name: dummies_ct
    fields:
        anchor:
            type: text
            class: large
        slug:
            type: slug
            uses: [ anchor ]
        content:
            type: html
            height: 150px
```

Go to dashboard, update DB, add "loripsum", see: 

![screen shot 2016-10-27 at 17 21 24](https://cloud.githubusercontent.com/assets/1833361/19773423/d33cc708-9c69-11e6-9b1a-f2e4169db77d.png)

----------

```
# 1	Symfony\Component\Debug\ErrorHandler::handleError(8, "Undefined index: title", "/Users/bob/Sites/bolt-origin/ …", 227, [array]) 
[root]/src/Legacy/Storage.php # line 227
# 2	Bolt\Legacy\Storage::preFillSingle("speaker_pl", [array], [array]) 
[root]/src/Legacy/Storage.php # line 133
# 3	Bolt\Legacy\Storage::preFill([array]) 
# 4	call_user_func_array([array], [array]) 
[root]/src/Storage/EntityManager.php # line 430
# 5	Bolt\Storage\EntityManager::__call("preFill", [array]) 
[root]/src/Controller/Backend/General.php # line 168
# 6	Bolt\Controller\Backend\General::prefill(Request) 
# 7	call_user_func_array([array], [array]) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 144
# 8	Symfony\Component\HttpKernel\HttpKernel::handleRaw(Request, 1) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 64
# 9	Symfony\Component\HttpKernel\HttpKernel::handle(Request, 1, [true]) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 586
# 10	Silex\Application::handle(Request) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 563
# 11	Silex\Application::run(Request) 
[root]/src/Application.php # line 93
# 12	Bolt\Application::run() 
[root]/index.php # line 12
```
