### ISSUE TITLE
[bug] Exception when saving a new record without title.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5982]
Details
-------

 - Relevant Bolt Version: [ 3.2 | master ]

Reproduction
------------

Have contenttype: 

```
blocks:
    slug: blocks
    singular_slug: block
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: html
            height: 150px
```

Create "new block", click "save". See: 

![screen shot 2016-11-02 at 17 07 40](https://cloud.githubusercontent.com/assets/1833361/19936867/679318a8-a11f-11e6-9359-2c64706e8a5c.png)

Full stack trace: 

```
#1	Symfony\Component\Debug\ErrorHandler::handleError(8, "Undefined property: Bolt\Stor…", "/Users/bob/Sites/bolt-origin/ …", 325, [array])
[root]/src/Storage/Entity/Content.php # line 325
#2	Bolt\Storage\Entity\Content::getTitle() 
[root]/src/Storage/Entity/MagicAttributeTrait.php # line 22
#3	Bolt\Storage\Entity\Entity::__get("title") 
[root]/src/Storage/Entity/Content.php # line 325
#4	Bolt\Storage\Entity\Content::getTitle() 
[root]/src/Storage/Entity/Content.php # line 56
#5	Bolt\Storage\Entity\Content::get("title") 
[root]/src/Storage/Field/Type/TextType.php # line 21
#6	Bolt\Storage\Field\Type\TextType::persist(QuerySet, Content) 
[root]/src/Storage/Repository.php # line 304
#7	Bolt\Storage\Repository::persist(QuerySet, Content, [array]) 
[root]/src/Storage/Repository.php # line 382
#8	Bolt\Storage\Repository::insert(Content) 
[root]/src/Storage/Repository.php # line 359
#9	Bolt\Storage\Repository::save(Content) 
[root]/src/Storage/ContentRequest/Save.php # line 242
#10	Bolt\Storage\ContentRequest\Save::saveContentRecord(Content, [NULL], [array], [true], "", "new", "/bolt/overview/foo") 
[root]/src/Storage/ContentRequest/Save.php # line 120
#11	Bolt\Storage\ContentRequest\Save::action([array], [array], "", [true], "new", "/bolt/overview/foo") 
[root]/src/Controller/Backend/Records.php # line 71
#12	Bolt\Controller\Backend\Records::edit(Request, "blocks", "") 
#13	call_user_func_array([array], [array]) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 144
#14	Symfony\Component\HttpKernel\HttpKernel::handleRaw(Request, 1) 
[root]/vendor/symfony/http-kernel/HttpKernel.php # line 64
#15	Symfony\Component\HttpKernel\HttpKernel::handle(Request, 1, [true]) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 586
#16	Silex\Application::handle(Request) 
[root]/vendor/silex/silex/src/Silex/Application.php # line 563
#17	Silex\Application::run(Request) 
[root]/src/Application.php # line 93
#18	Bolt\Application::run() 
[root]/index.php # line 12
```
