### ISSUE TITLE
[BUG] 3.2.2 - Unable to save entries in templatefield repeaters

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6046]
Confirmed as a bug in 3.2.2 only:

theme.yml:

```
templatefields:
    services/index.twig:
        services:
            type: repeater
            label: Services
            fields:
                title:
                    type: text
                body:
                    type: html
```

Whenever an entry has been added to the templatefield, the whole site breaks, throwing the following exception:

![uncaught exception fieldconfigurationexception](https://cloud.githubusercontent.com/assets/1776058/20309845/81aeb824-ab41-11e6-847e-03eb9f5ca0cb.png)

Also cleared cache, totally removed the cache folder, recreated the `theme.yml` file just incase it was some weird line ending thing, all sorts.

Above config does work in 3.2.1.

Details
-------

 - Relevant Bolt Version: 3.2.2 ONLY
 - Install type: Composer install
 - PHP version: 5.6

Reproduction
------------

1. Create a theme.yml using above config
2. Create a page / contenttype and have it use the specified theme
3. Create a new record and add entries into the templatefield
4. Observe exception
