### ISSUE TITLE
[BUG] link() method inconsistences between Entity\Content and Legacy\Content

### ISSUE THREAD

**Issue by maetthu** [bolt/bolt#6066]
Bolt version 3.2.2. When content is fetched using the repository methods, the link() method doesn't return the correct URL to the entry as opposed to the legacy content class, which returns the correct link.

```PHP
// wrong links: falling back to id instead of slug
$content = $app['query']->getContent('pages/1');
dump($content->link()); // outputs: "/page/1"

$content = $app['storage']->getRepository('pages')->find(1);
dump($content->link()); // outputs: "/page/1"

// correct link: using slug
$content = $app['storage']->getContent('pages/1');
dump($content->link()); // outputs: "/page/SLUG"
```

Matching routing:
```YML
contentlink:
    path: /{contenttypeslug}/{slug}
    defaults:
        _controller: controller.frontend:record
    requirements:
        contenttypeslug: controller.requirement:anyContentType
```
