### ISSUE TITLE
[BUG] Underscores in field names blocks saving data 

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6082]
Using underscores in the field name (not the contenttype name) causes that field to not be saved in the DB. I've had this example:

```yaml
 accordeon_1_title:
    type: text
    label: Título
accordeon_2_title:
    type: text
    label: Titulo
```
 
I've changed it to:
```yaml
accordeon1title:
    type: text
    label: Título
accordeon2title:
    type: text
    label: Título
```

And now it's saving properly.

Details
-------

 - Relevant Bolt Version: 3.2.2
 - Install type: Composer install
 - PHP version:  7.0 
 - Used web server: Apache version 2.4
