### ISSUE TITLE
[BUG] Sortable multiple select fields break the edit page

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#6093]
Adding `sortable:true` to a multiple select field inside a repeater causes the entire layout to implode. 

![image](https://cloud.githubusercontent.com/assets/6642498/20643151/800e937e-b418-11e6-891a-f3b9b330bc2d.png)

Details
-------

 - Relevant Bolt Version: 3.2.2
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache
 - For UX/UI issues: Chrome stable latest

Reproduction
------------
```
        agenda:
            type: repeater
            fields:
                time:
                    type: text
                title:
                    type: text
                speakers:
                    type: select
                    multiple: true
                    # TODO: Bug for sortable selects in repeaters - comment out sortable and the page works again.
                    sortable: true
                    values: people/title
```

**Comment by bobdenotter** [comment]
@graham73may Could you check if this is still happening after #6096 lands?

**Comment by graham73may** [comment]
Hi @bobdenotter - No the layout glitch is still occurring the same as the screenshot. 

My full CT that causes the screenshot is:

```
# Sessions
sessions:
    name: Sessions
    singular_name: Session
    fields:
        title:
            class: large
            group: content
            required: true
            type: text
        slug:
            type: slug
            uses: title
        body:
            group: content
            height: 300px
            type: html
        session_start:
            group: "Meta"
            label: "Session start"
            type: datetime
            options:
                datetimepicker:
                    changeMonth: true
                    changeYear: true
                    yearRange: "-100:-0"
            condition:
                field: taxonomy-eventtypes
                operator: '='
                show: true
                value: [ one-off-events, summits-and-conferences ]
        session_end:
            group: "Meta"
            label: "Session end"
            type: datetime
            options:
                datetimepicker:
                    changeMonth: true
                    changeYear: true
                    yearRange: "-100:-0"
            condition:
                field: taxonomy-eventtypes
                operator: '='
                show: true
                value: [ one-off-events, summits-and-conferences ]
        speakers:
            group: "Meta"
            label: "Speakers"
            multiple: true
            sortable: true
            type: select
            values: people/title
        agenda:
            type: repeater
            fields:
                time:
                    type: text
                title:
                    type: text
                speakers:
                    type: select
                    multiple: true
                    sortable: true # This is the cause
                    values: people/title
    taxonomy: [ priorities, categories, tags ]
    icon_many: "fa:list"
    icon_one: "fa:list"
    recordsperpage: 25
    sort: -session_start
```

**Comment by bobdenotter** [comment]
I've reduced it to a minimal example where this error occurs: 

```
sessions:
    name: Sessions
    singular_name: Session
    fields:
        title:
            class: large
            group: content
            required: true
            type: text
        slug:
            type: slug
            uses: title
        agenda:
            type: repeater
            fields:
                speakers:
                    type: select
                    multiple: true
                    sortable: false # This is the cause
                    values: page/title
```

I can reproduce it, so I'll look into fixing it.
