### ISSUE TITLE
[BUG] Second repeater in templatefield breaks the backend

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6174]
If a repeater is defined in a templatefield it saves and display normally when adding the first one, but on adding a second one breaks the backend.

Details
-------

 - Relevant Bolt Version: 3.2
 - Install type: Composer install 
 - PHP version: 7.0
 - Used web server: Apache 2.4

Reproduction
------------

This is in my `theme.yml` file:

```yaml
templatefields:
    ayuda.twig:
        repeater:
            type: repeater
            fields:
                repeattitle:
                    type: text
                repeatcontent:
                    type: html
```

And when saving the record with more than one repeater and then refreshing the page it shows me this:

![captura de pantalla 2016-12-15 a la s 11 45 50](https://cloud.githubusercontent.com/assets/3504472/21237525/9eee52cc-c2bc-11e6-9991-f217a663fa9c.png)
