### ISSUE TITLE
[BUG] can't generate path('homepage') @ backend in 3.2.3

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#6175]
My 'routing.yml' now starts with
```
homepage:
  path: /
  defaults:  { _controller: 'Mapple\Site\Controller\Front::base_action'}
```
which previously (before 3.2+ upgrade) worked like a charm (even without Homepage route inside routing.yml).

But now, in all instances of `{{ path('homepage') }}` like [here](https://github.com/bolt/bolt/blob/release/3.2/app/view/twig/_base/_page-no_nav.twig#L21) it throws an error.
```
<div class="view-site">
    <a href="{{ path('homepage') }}" target="_blank"><i class="fa fa-fw fa-external-link-square"></i> {{ __('general.phrase.view-site') }}</a>
</div>
```
![image](https://cloud.githubusercontent.com/assets/2145313/21258296/e996cde8-c3ae-11e6-90dc-92b24fd65b22.png)

My suggestion, is that problem is in generating frontend routes for backend.

Could a problem be here:

![image](https://cloud.githubusercontent.com/assets/2145313/21258256/ba1fa076-c3ae-11e6-8111-fbeb8a7277d4.png)

What else can i provide to analyze the problem?

#### Details:
- v3.2.3
- composer install
- custom bolt paths:
```yml
paths:
    app               : vendor/bolt/bolt/app
    logs              : app/vars/logs
    database          : app/database
    cache             : app/vars/cache
    extensionspath    : app/extensions
    themebase         : src/Site/
    config            : src/Site/config
    translations      : src/Site/config/translations
    extensionsconfig  : src/Site/config/extensions
    web               : web
    files             : web/files
    view              : web/bolt-public/view
```
