### ISSUE TITLE
[BUG] Mismatch between legacy and new storage?

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6228]
Details
-------

 - Relevant Bolt Version: 3.2.5
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache version 2.4

Reproduction
------------

From the Slack channel:

zomars [10:12]  
My `contentypes.yml`file:

```yaml
portfolio:
    name: Portafolio
    singular_name: Portafolio
    slug: portafolio
    singular_slug: portafolio
    tablename: portafolio
```

zomars [10:12]  
Gets me this:
![pasted image at 2017_01_06 10_12 am](https://cloud.githubusercontent.com/assets/3504472/21726316/82beb04e-d3f9-11e6-9cc6-cc343c172408.png)

My tablename is portafolio but the taxonomy contenttype is portfolio. This shows me the correct taxonomy in the Back-End, but `null` in the Front-End.

I’ve manually changed the DB to this:

![pasted image at 2017_01_06 10_14 am](https://cloud.githubusercontent.com/assets/3504472/21726330/92f295f2-d3f9-11e6-82d1-7f13d2ae1ad9.png)

zomars [10:14 AM]  
And now it gives me the correct taxonomies in the Front-End BUT `null` in the Back-End

sahassar [10:14 AM]  
Aaaah... Might be worth opening an issue about that, since it's a mismatch betweeen legacy and new storage (I'd guess)
