### ISSUE TITLE
[BUG] Vague exception when you've got an invalid contenttypes.yml

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6248]
By accident, I had an invalid config for `contenttypes.yml`.

However, the exception that was thrown was extremely vague, which basically gave me no information as to what I did wrong.

```
Twig_Error_Runtime in Template.php line 556:
Impossible to access an attribute ("all") on a null variable in "@bolt/exception/_request.twig" at line 46.
```

Used contenttype (notice the `type: image` is missing)

```
shields:
    name: Shields
    singular_name: Shield
    fields:
        title:
            type: text
        image:
            upload: shields
```

![exception](https://cloud.githubusercontent.com/assets/1776058/21895332/361d5c28-d8da-11e6-804b-56e4b723ab43.png)

Details
-------

 - Relevant Bolt Version: 3.2.5
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

1. Create an invalid contenttype
2. Attempt to load a page
3. Observe exception
