### ISSUE TITLE
[BUG] Repeater field with Array value, outputs encoded JSON, needs to be decoded to output.

### ISSUE THREAD

**Issue by bzerangue** [bolt/bolt#6251]
I am trying to retreive the "title of an image." Basically, I just want the file name. 

Here is my data... 

```
Content {#1809 ▼
  +id: "1"
  +values: array:13 [▼
    "datechanged" => "2017-01-10 14:34:50"
    "id" => "1"
    "slug" => "first-floor-elementary-desk"
    "datecreated" => "2017-01-10 11:48:51"
    "datepublish" => "2017-01-10 11:40:41"
    "datedepublish" => null
    "ownerid" => "1"
    "status" => "published"
    "location" => "First Floor Elementary Desk"
    "floor" => "first"
    "building" => "Main Building"
    "templatefields" => Content {#1814 ▶}
    "directions" => array:6 [▼
      0 => array:3 [▶]
      1 => array:3 [▼
        "room" => "1st-4th Grade"
        "arrow" => "[{"filename":"arrows\/icon-04-right.png","title":"arrows\/icon-04-right"}]"
        "room_floor" => "0"
      ]
      2 => array:3 [▶]
      3 => array:3 [▶]
      4 => array:3 [▶]
      5 => array:3 [▶]
    ]
  ]
  +taxonomy: []
  +relation: []
  +contenttype: array:14 [▶]
  +user: array:15 [▶]
  +sortorder: null
  +config: null
  +group: null
  #app: Application {#22 ▶}
  #lastWeight: 0
  #isRootType: true
}
```

Here is my template... 

```
{% for item in record.directions %}

	<div class="itemblock" data-block-item="mrss">
		<div data-item-type="title" class="title"><span class="icon-05-up-left"></span>{{ item.arrow.get('title') }}</div>
	</div>
{% endfor %}
```

It outputs nothing.

If I try... `{{ item.arrow.title }}`, again nothing outputs.  

If I do, `{{ item.arrow }}`, it outputs an array like this... `[{"filename":"arrows\/icon-01-up.png","title":"arrows\/icon-01-up"}]` which is JSON... I believe this should be decoded to work.

Per @sahassar on Slack, he gave me the following... and it allowed me to output the data that I needed output... 

`{{ item.arrow|json_decode|first.title }}`

---

Here's my only `contenttype`definition that i have for the small site. Make a wayfinding sign site to generate digital signage with direction arrows. 

```
# Wayfinding
signs:
  name: Signs
  singular_name: Sign
  fields:
    location: 
      type: text
      class: large
      group: detail
    slug:
      type: slug
      uses: location
    floor:
      type: select
      values: [first, second, third]
    building:
      type: select
      values: [Main Building, East Building, West Building]
    directions:
      type: repeater
      fields:
        room:
          type: text
        arrow:
          type: imagelist
          extensions: [ png ]
        room_floor:
          type: select
          values: [first, second, third]
      group: directions


```

---

Details
-------

 - Relevant Bolt Version: [ 3.2.5 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ] version [ 2.4 ]
