### ISSUE TITLE
Repeater sub-fields don't use the same field configuration as every other field

### ISSUE THREAD

**Issue by mrenigma** [bolt/bolt#6269]
Details
-------

 - Relevant Bolt Version: 3.2.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache 2
 - Extension being used: [multictselectfield.zip](https://github.com/bolt/bolt/files/713357/multictselectfield.zip)

Reproduction
------------  
 1. **Bug summary**: 
   Custom field extensions don't work as subfields of repeaters. The issue is caused by differing config usages.
 2. **Specifics**:
    Custom fields are added in the `ConfigTrait` using:
    ```php
         $app['config']->getFields()->addField($fieldClass);
    ```
    to map the field name to a class. Whereas it looks like Repeaters don't use this config for their sub-fields but use the field manager instead.
    The field manager uses `$app['storage.typemap']` to generate it's map of field names and classes and is created in `StorageServiceProvider.php`. However the `storage.typemap` is never updated after it's initially setup in the same class.

     This means that any new field extensions aren't added to the field manager and therefore aren't known by repeaters to generate their sub-fields.

     To fix this I've had to add in my extension `registerField` method: 
     ```php
         $app->offsetSet('storage.typemap', array_merge($app['storage.typemap'], [
             $field->getName() => get_class($field)
         ]));
      ```
      because the `SimpleExtension` methods are processed before the field manager, so overriding the app container injects my new field into repeaters.

      A snippet of our `contenttypes.yml` to help with reproduction:

      ```yml
      # Pages
      pages:
          name: Pages
          singular_name: Page
          fields:
          # Featured Content upcoming events
              ft_content_upcoming_events_cards:
                  group: "Featured content in upcoming events"
                  label: "Cards"
                  limit: 6
                  prefix: "<p>Please select up to a maximum of 6 cards.</p>"
                  type: repeater
                  fields:
                      upcoming_events_item_event:
                          label: "Event/Event series"
                          autocomplete: true
                          type: multictselect
                          values: (event,eventseries)/title
      ```
