### ISSUE TITLE
[BUG] Sortable select fields don't remain sorted.

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#6291]
Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 7.0.9
 - Used web server: Apache
 - For UX/UI issues: Chrome latest

Reproduction
------------
​
 1. **Bug summary**: 
 
Sortable select fields change to being alphabetically sorted on save. You can re-order the items after the page has been saved. 

 2. **Specifics**:

 3. **Steps to reproduce**:

Add a sortable select field to `contenttypes.yml`

```
        authors:
            group: "Meta"
            label: "Authors"
            multiple: true
            sortable: true
            autocomplete: true
            type: select
            values: people/title
```

Load up the contenttype your fields are on, add some items in a specific order. Press save. 

 4. **Expected result**: 
Expect to see the items saved in the order they appeared in the field. 

 5. **Actual result**: 
The items in the field become alphabetically sorted. 

It is however possible to sort the items once you have saved the page once and re-drag the items.
