### ISSUE TITLE
[BUG] Storage::saveContent() slug is mandatory but that's wrong

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#6295]
Hey,

I'm using the boltforms plugin and save the form input to the content type. **The content type has no slug field**. If I save the record (by filling the form correctly), I don't see any error, but find an exception in the system logs
```
[Bolt Forms] An exception occurred saving submission to ContentType table `feedbacks` 
URI: /add-feedback
Source: /var/www/vhosts/bolt/vendor/bolt/bolt/src/Legacy/Storage.php :: 412 
```

I already know the fix I think but wanted you to see the issue first.

Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Nginx

Reproduction
------------

Content type:
```
feedbacks:
    name: Feedbacks
    singular_name: Feedback
    fields:
        foo:
            type: integer
            group: main
        token:
            type: text
            group: security
    recordsperpage: 100
    searchable: false
    viewless: true
    default_status: held
```
Save the record with `Storage::saveContent()`.
