### ISSUE TITLE
[BUG] Relations between Content Types not persisting

### ISSUE THREAD

**Issue by kevinkhill** [bolt/bolt#6311]
Details
-------
 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache 2.4

Issue
-------
I have two contenttypes, **events** and **event_series**. I have defined the relations, as follows:
```
event_series:
    name: Concert Series
    singular_name: Concert Series
    show_in_menu: "Events & Venues"
    fields:
        title:
            type: text
            class: large
            variant: inline
            required: true
            group: content
        startdate:
            label: "Start date of the series"
            type: date
            variant: inline
            options:
                datepicker:
                    firstDay: 0
                    dateFormat: "mm/dd/yy"
            group: content
        enddate:
            label: "End date of the series"
            type: date
            variant: inline
            options:
                datepicker:
                    firstDay: 0
                    dateFormat: "mm/dd/yy"
            group: content
        teaser:
            type: text
            group: content
            postfix: "This will be shown in large text, below the banner"
        body:
            type: html
            height: 200px
            group: content
        moreInfo:
            label: "More Info"
            type: html
            height: 200px
            group: content
        image:
            label: "Banner Image"
            type: image
            group: media
        sideimage:
            label: "Side Image"
            type: image
            group: media
        slug:
            type: slug
            uses: title
            group: meta
    relations:
        events:
            multiple: true
            order: title
            label: Concerts in the Series
    taxonomy: [ sortable ]
    record_template: "content/concert/series.twig"
    recordsperpage: 100
    show_on_dashboard: true
    default_status: publish
    searchable: true
    icon_many: "fa:list"
    icon_one: "fa:list"

events:
    name: Events
    singular_name: Event
    show_in_menu: "Events & Venues"
    fields:
        title:
            type: text
            class: large
            group: content
            required: true
        datetime:
            label: "Event Date"
            type: datetime
            variant: inline
            required: true
            options:
                datepicker:
                    firstDay: 0
                    dateFormat: "mm/dd/yy"
        teaser:
            type: text
            variant: inline
        body:
            type: html
            height: 200px
        bannerimage:
            label: "Banner Image"
            type: image
            group: Media
        sideimage:
            label: "Side Image"
            type: image
            group: Media
        slug:
            type: slug
            uses: [ title, datetime ]
            group: meta
    relations:
        event_series:
            multiple: false
            order: title
            label: Select a Concert Series
        venues:
            multiple: false
            order: title
            label: Select a Venue
    record_template: "content/concert/single.twig"
    recordsperpage: 100
    show_on_dashboard: true
    default_status: publish
    icon_many: "fa:ticket"
    icon_one: "fa:ticket"
```
When editing a **series**, I go to the relations tab, select two events from the picker and press save. Success! (partially)

I can see in the database that the bolt_relations table did get two entries for what we just saved.

If I navigate elsewhere and come back to edit the same **series**, when I go to the relations tab, the two I picked previously are not shown. Even though they are defined in the database.

If I change any other field of the series and save it, the fact that the relations were missing, means that bolt happily wipes them out of the DB, assuming I meant that there are no more relations.

If more info, or files are needed, I am happy to provide more,

**Comment by bobdenotter** [comment]
Might be related to a lingering quirk with keys / slugs of contenttypes. Could you try make it explicit, like this: 

```
event_series:
    name: Concert Series
    slug: event_series
    singular_name: Concert Series
    singular_slug: event_series
```

after doing that, try again, and see if it makes a difference. :-)

**Comment by bobdenotter** [comment]
Might be related to a lingering quirk with keys / slugs of contenttypes. Could you try make it explicit, like this: 

```
event_series:
    name: Concert Series
    slug: event_series
    singular_name: Concert Series
    singular_slug: event_series
```

after doing that, try again, and see if it makes a difference. :-)
