### ISSUE TITLE
[BUG] Labels for templatefields are required to be in quotes, whereas in contenttypes.yml they're not

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6322]
Spotted an inconsistency between `theme.yml` and `contenttypes.yml` regarding labels for fields.

In `theme.yml`:

```
about-us/index.twig:
    video:
        type: text
        label: Vimeo video ID
```

Results in:

![buug](https://cloud.githubusercontent.com/assets/1776058/22419235/6dfada1e-e6d4-11e6-8db0-4ee93ec68bb5.png)

```
about-us/index.twig:
    video:
        type: text
        label: "Vimeo video ID"
```

Results in:

![bug](https://cloud.githubusercontent.com/assets/1776058/22419400/32eb7478-e6d5-11e6-907b-a835f2508fbf.png)

Details
-------

 - Relevant Bolt Version: 3.2.5
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome

Reproduction
------------

1. Set up a contenttype like above
2. Observe the field
3. Change the contenttype to have quotes
4. Observe the field again, with correct result.

**Comment by rossriley** [comment]
Can anyone else reproduce this? I get the label showing up either with or without the quotes and I can't spot any reason why the behaviour would be different unless the YAML itself didn't parse correctly since a normal text field and a Templatefields text field use the exact same twig template to render.

The behaviour in this issue is what happens when a label is parsed as empty, if so it defaults to  the field name with an uppercase first letter.

**Comment by bobdenotter** [comment]
I can't reproduce either, and according to the YML spec this shouldn't happen. Sounds more like a stale cache issie.

**Comment by Maelstromeous** [comment]
I think this is fixed as of 3.2.6. I'm no longer getting this issue using the following settings:

```
templatefields:
    homepage/index.twig:
        gallery:
            type: repeater
            fields:
                image:
                    type: image
            label: Gallery test
```
