### ISSUE TITLE
[BUG] Templatefield repeaters are broken

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6323]
Attempted to add a repeater field to a templatefields record. It appears that whenever I add it, the backend throws a notice exception stating something is undefined.

In `theme.yml`:
```
about-us/index.twig:
    clients:
        type: repeater
        fields:
            image:
                type: image
                upload: clients
            url:
                type: text
```

Results in the following exception when attempting to edit the page where the templatefield is set upon:

![templatefieldexception](https://cloud.githubusercontent.com/assets/1776058/22419882/5d502ae0-e6d7-11e6-9c69-3195198f0f3c.png)

## Workaround

There is a workaround, which is to set `debug_error_level: 8181` in your `config.yml` / `config_local.yml`. However this isn't an ideal solution, and the fact it's throwing a notice may be indicative of a wider problem.

Details
-------

 - Relevant Bolt Version: 3.2.5
 - Install type: Composer
 - PHP version: 5.6
 - Used web server: Apache

Reproduction
------------

1. Create a record which uses an entry in `theme.yml`
2. Use the above config to define the templatefields
3. Navigate to the record in particular in the backend
4. Observe error
