### ISSUE TITLE
[BUG] Repeater emits PHP Notice

### ISSUE THREAD

**Issue by mikegillis677** [bolt/bolt#6333]
I'm getting an error when I add a repeater to my template.
My template:
```
templatefields:
    pages/partnerships.twig:
        partners:
            type: repeater
            label: Partners
            fields:
                name:
                    type: text
                    label: Partner Name
                logo:
                    type: image
                    label: Partner Logo
                    upload: files://images/page/partnerships/
                url:
                    type: text
                    label: Partner URL
```

The error I am getting is:
```
## Uncaught Exception: ContextErrorException

_ContextErrorException in RepeaterType.php line 99:_ 
_**Notice: Undefined index: partners**_
```

I checked the source code for my install, and line 99 appears to be:
```
$vals = array_filter(explode(',', $data[$key]));
```

Details
-------

 - Relevant Bolt Version: 3.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: PHP Built-in web server (for development purposes)

Reproduction
------------
​
 1. Create a new template with a repeater in the fields
 2. Add a new page using that template
 3. At this point, I would expect the edit page to come back up again when the page refreshes.  However, what actually happens is a PHP Notice is emitted, and I get an error screen.
