### ISSUE TITLE
Validate ContentType table names don't match system ones

### ISSUE THREAD

**Issue by Rudedog9d** [bolt/bolt#6352]
EDIT: I pinpointed the problem to the slug value of 'users', rather than duplicate slugs. If a `slug`'s value is `users`, a backend exception is raised with no warning or hint to the problem. This is only for `slug`, not `singular slug`. Relevant configuration from `contenttypes.yml`:

```yml
userpages:
    name: User Pages
    slug: users
    singular_name: User Page
    singular_slug: users
```

![image](https://cloud.githubusercontent.com/assets/15984156/22614762/06245ef4-ea55-11e6-8aab-ba0cd10727f4.png)
![image](https://cloud.githubusercontent.com/assets/15984156/22614771/3ab12f3a-ea55-11e6-94d5-a62fec925b5b.png)

Details
-------

 - Relevant Bolt Version: [ 3.2.6 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 7.0.13 ]
 - Used web server: [ Apache ] version [ 2.4.18 ]

Reproduction
------------

* Edit `contenttypes.yml` and give two slugs (`slug` or `singular_slug`) the same value
* Try to load any page
