### ISSUE TITLE
Select fields don't accept a default value

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6370]
As suggested by the Bolt documentation https://docs.bolt.cm/3.2/fields/common#default-values you should in theory be able to apply a default to fields, such as a select.

However upon applying a default it doesn't appear to be applying to the select field. Rather than selecting the chosen default, it's showing up as `(none)`.

Contenttype:

```
selection:
    type: checkbox
    values: [Yes, No]
    default: No
```

Resulting in:

![screenshot 2017-02-09 17 25 05](https://cloud.githubusercontent.com/assets/1776058/22794957/bdf2cb06-eeec-11e6-9cd5-aa89f6a510b4.png)

In this case "No" value should be pre-selected.

Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer
 - PHP version: 7.0
 - Used web server: Nginx
 - For UX/UI issues: Chrome v56

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
1. Create a contenttype with the above config
2. Observe the default value not being applied

**Comment by jadwigo** [comment]
Ah, I've been there.

If you use a values like that you actually create a numbered index for the values
```yml
selection:
    type: checkbox
    values: 
       -: Yes
       -: No
```
So the _actual_ values are 
```php
[ 0 => 'Yes', 1 => 'No' ]
```

You probably expected want named values:
```php
[  'Yes' => 'Yes', 'No' => 'No' ]
```

This is unfortunately not easy to change, because the way this is handled is generalized by symfony so it 
 'just works'. Maybe there's a way to override or set a different default.. 

But there is a quick workaround:
```yml
selection:
    type: checkbox
    values: 
       Yes: Yes
       No: No
    default: No
```
