### ISSUE TITLE
[Bug] Slug creation for tags broken

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#6482]
In Bolt 3.2, the creation of slugs for taxonomies of type tag is broken. The generated slug is no longer passed to some kind of slugify function but stays identical to the name of the tag.

**Example**
We create a tag `München` when editing a contenttype in the backend.

The DB entry will then have the name `München` and the slug `München`.
It **should** have and had in Bolt 3.1- the slug `muenchen` (I also saw `m-nchen`, but that might have been an unrelated bug.)

```
tag:
    slug: tag
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    listing_template: taxonomy.twig #custom template
    listing_records: 20
```
-----------

Details
-------

 - Relevant Bolt Version: 3.2.8
 - Install type: Composer install
 - PHP version: 5.5
 - Used web server: Apache
 - For UX/UI issues: Chrome
