### ISSUE TITLE
[RFC] Unexpected behaviour: Tab 'relations' visible but should not

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#6499]
When you add a relation field to a contenttype and relations are set in the database, a "relations" tab appears in the editor (screenshot).

If one removes the relation field from contenttypes.yml, the 'relations' tab is still visible in the editor. 
IMHO the 'relations' tab should not be visible when a relation field is removed from contenttypes.yml

```
typen:
    name: Typen
    singular_name: type
    fields:
        title:
            type: text
            class: large
            label: Titel
            required: true
            group: Tekst
        slug:
            type: slug
            uses: title
            group: Tekst
        body:
            type: html
            height: 300px
            label: Uitgebreide tekst
            group: Tekst
    relations:
        verblijfopties:
            multiple: true
            label: Selecteer de verblijfoptie(s) waar dit type bij hoort
```

I did some testing:
When I removed the relations manually in the "bolt_relations" table, the tab dissapeared (obviously).

Bolt 3.2.9
