### ISSUE TITLE
[RFC] More dynamic routing fallbacks (multiple content types on root level)

### ISSUE THREAD

**Issue by Eiskis** [bolt/bolt#6527]
I use the following route to bind root URLs to my `page` content type:

```yml
# Pages on root level
pagebinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: page
    contenttype: pages
```

This works great. I can create a new page in the dashboard and it'll be available with a nice short URL for the end user.

However, my content type structure has a lot of dynamic content and many different content types. I have a `profile` object for each team member, and let's say blog `posts` as well.

What I'd like to do is have the URL of all of these available for the end user on the root level. So I have a few static pages, each team member profile and also each blog post, and each of them should be available under `mydomain.com/`, like so:

```
mydomain.io                                         # index
mydomain.io/about-us                                # page
mydomain.io/contact                                 # page
mydomain.io/team                                    # page or listing
mydomain.io/jerry                                   # profile
mydomain.io/tom                                     # profile
mydomain.io/donald-duck                             # profile
mydomain.io/roger-rabbit                            # profile
mydomain.io/10-reasons-why-i-hate-wordpress         # post
mydomain.io/10-reasons-why-bolt-rules               # post
```

I have a fairly controlled environment, so I can make sure the slugs don't overlap on my end. If they did, I'd expect the order I set the routes to determine which content type gets matched first. I'd expect to be able to set the routes like this:

```yml
# Pages on root level
pagebinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: page
    contenttype: pages

# Profiles on root level
profilebinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: profile
    contenttype: profiles

# Posts on root level
postbinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: post
    contenttype: posts
```

However unfortunately this doesn't work as of 3.2. When I load up `mydomain.io/roger-rabbit`, Bolt directs the end user to 404 instead of trying to match the profile. I need to add the `profile/` prefix to the route in order for this to work.

I guess I could work around this by adding a corresponding page per each record, do some mapping wizardry somewhere and then loading up corresponding profiles/posts via the intermediary page record, but this is a lot of busy work and a lot of room for errors. I think the developer user expectation here is that the URLs should work out of the box if that's how I intentionally set up my routes.

Another way to phrase this more generically: I'd like to be able to use more than one different type of page in the CMS instead of being confined to one `page` content type, which has to serve all purposes I might have for anything that's on the root level. I've faced this in another scenario, where I've added a ton of fields to the generic `page` content type definition to satisfy all my use cases on the site. Template fields are part of the answer to this but it's not great for recurring content, and kinda breaks if you want to still use different templates.

I'm not sure how the internals of Bolt work here, so I don't know exactly what the implications of changing this behavior would be. Is it simply a matter of trying to match all routes before calling it a _not found_ when matching routes, or is it more complicated than that? Or is there another way to do this already?

**Comment by rossriley** [comment]
It would be doable, it's something that I've implemented before as a simple extension, but whether it would make sense as part of core would be open to discussion since the main downside of doing this is that you introduce database lookups to the routing process.

First of all you can't do what you suggested because the routing is regex based and thus whether a url matches a route or not is a binary choice. If a route matches multiple routing definitions then the first one wins and the rest in the file are ignored.

So the way to implement this is something like this...

```yml
# any content on root level
multicontentbinding:
    path: /{slug}
    defaults:
        _controller: controller.mycontroller:multirecord

```

Then you implement a controller that takes the slug, iterates through all your contenttypes and sees if we have a record that matches that slug. If we find one, we render it, if we don't then throw a 404.

So, the easiest way to get this working would be to put together an extension that did the above. If an extension is particularly popular with users then the case to make it part of core would be enhanced.

One concern if it did become part of core would be that more work may be needed to manage multiple contenttype slugs and avoid clashes, as in your case you can manage the slugs yourself and manually avoid clashes, but this probably wouldn't be sufficient for general usage.
