### ISSUE TITLE
Repeater fields are omitted when viewing the "preview" link of a record

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#6605]
This one is pretty straight forward, when you have a repeater in your content type and try to use the preview link for a record on the backend, you're taken to the preview page but all fields that are part of the repeater are omitted.

Details
-------
 - Relevant Bolt Version: [ 3.2.11 ]
 - Install type: [ Zip/tarball install | Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ]
 - For UX/UI issues: [ Safari 10.  ]

**Comment by bobdenotter** [comment]
This seems to be a tricky one to solve. Let's say we have this: 

```
foobar:
    name: Foobars
    singular_name: Foobar
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        foo:
            type: repeater
            fields:
                repeattitle:
                    type: text
                foobar:
                    type: html
```

And in the foobar.twig we use:

```
        {% for repeater in record.foo %}
             {{ dump(repeater)}}
        {% endfor %}
```

When "previewing" a record with this, the repeater fields are passed in to the template as plain arrays: 

![screen shot 2017-05-01 at 22 12 33](https://cloud.githubusercontent.com/assets/1833361/25593011/57001b24-2ebb-11e7-80ff-642fc11e8e39.png)

When viewing the actual saved page, the repeaters work as expected: 

![screen shot 2017-05-01 at 22 12 48](https://cloud.githubusercontent.com/assets/1833361/25593052/67046bec-2ebb-11e7-9f07-1ff3d6214303.png)

I don't know if it's feasible to fix this.
