### ISSUE TITLE
"datetime" fields in Repeaters throw exception.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6607]
To reproduce, use: 

```
bars:
    name: Bars
    slug: bars
    singular_name: Bar
    singular_slug: bar
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: [ title ]
        body:
            type: html
            height: 300px
        activity_programma:
            type: repeater
            fields:
                repeattitle:
                    type: datetime
    record_template: record.twig
```

See screenshot below. Fix incoming. 

![screen shot 2017-05-01 at 16 24 07](https://cloud.githubusercontent.com/assets/1833361/25581961/157ee9bc-2e8b-11e7-9433-a919f828c1d1.png)
