### ISSUE TITLE
[BUG] singular_name only partially obeyed for new content types MINOR SEVERITY

### ISSUE THREAD

**Issue by sebtombs** [bolt/bolt#6621]
Issue
------

When new content types are created, and given a singular name, the name given is used in the menu.
e.g. for

recurring_activities:
    name: Recurring Activities
    singular_name: Activity
    ...

The side menu shows:

Recurring Activities->View Recurring Activities
                                  New Activity

All good.

However, on the form for a new recurring activity, I get:

Heading: "New Recurring-activities" (should be New Activity)
Save button: "Save Recurring-activities" (should be Save Activity)

This issue is not present for the built-in content types of Pages and Entries (and I don't think it was for Showcases - can't confirm that as I've removed the Showcases type). I correctly get "Page" and "Entry".

Obviously this isn't a big deal but probably worth fixing if that piece of code is touched for other reasons.

Installation Details
-----------------------

 - Bolt Version: 3.2.11
 - Install type: Zip/tarball install followed by Composer update
 - PHP version: 5.6
 - Used web server: Apache

**Comment by sebtombs** [comment]
This may possibly be due to the underscore in the content type - I've created a different new type which doesn't contain the underscore and this seems to be properly obeying the rules.

**Comment by bobdenotter** [comment]
We should have resolved the issues with underscores in contenttypes. Are you sure you're on 3.2.11? 

I tried this, and it works as expected: 

```
recurring_activities:
    name: Recurring Activities
    singular_name: Activity
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        body:
            type: markdown
            height: 300px
```

Screenshot: 

![screen shot 2017-05-07 at 12 52 27](https://cloud.githubusercontent.com/assets/1833361/25780232/3c848600-3324-11e7-910a-173c9af87908.png)
