### ISSUE TITLE
[BUG] Selectfield populated from contenttypes behaves unexpected when NULL or empty

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#6693]
## Situation

In my contenttypes.yml, in my contenttype 'posts' I use a selectfield to select an author ( from the contenttype 'author')

```
        author:
            label: "Author(s)"
            type: select
            values: persons/last_name,first_name
            keys: id
            multiple: true
```

The post does not have an author yet, `NULL` (or empty, same result) in db.
However, the post shows it has an author... 

![screen shot 2017-05-19 at 13 54 04](https://cloud.githubusercontent.com/assets/5583671/26246690/b1dcc744-3c9a-11e7-9525-231db4c5ab09.png)

Apparently, it attemps to find the author that has `NULL` or empty as a last_name and , if that indeed exists, returns that one.

Saving this / anything on the page, puts the `id` of this author in the DB instead of `NULL`.

## Expected behaviour

I would expect a post that has `NULL` as an author, not to return an author.

Since I use the `id` as key, I would expect that Bolt tries to find the `id` that is `NULL`, and return no result.

## Reproduction

Reproduced on a clean new Bolt install (3.2.13), with an author that has an empty `first_name` and `last_name`, and the post having `NULL` for the 'author'.

## Temporary fix
I can temporary fix it by adding the `id` to the values in the first place, but this is not the solution.
This is also not preferred when asking an editor to find an author within 200 names, if they are not ordered alphabetically ( `last_name`).

Thanks!
A
