### ISSUE TITLE
Ajaxify content type select fields in back-end

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#6725]
The problem
-------

At the moment the select field will not allow you to select from all available records in a site if there are more than the default limit (or more than a custom limit)

Suppose you have a bolt website with two contenttypes, pages and records.
There are some page records, and there are a lot (more than 500) entry records

And in the pages content type you have a select field where a user can select a related entry

```yml
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        entryselect:
            type: select
            values: entries/id,title
            sort: id
            autocomplete: true
    listing_records: 10
    recordsperpage: 10

entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
    listing_records: 10
    default_status: publish
```
The query that is done in the backend is:

```sql
SELECT bolt_entries.* FROM bolt_entries ORDER BY "id" LIMIT 500 
```
Which will only returns 500 records - and if there happen to me more the editor cannot choose those.

It it possible to increase the limit. But that is not practical for sites with really large amounts of records  (think 100.000 entries and more) because you will run into server memory limits, server timeouts and clientside slowdown and memory limits. _And you will get there sooner than you think, I can provide working examples._

Related problems
--------
If that select box is in a repeater, 500 records per repeated instance will be loaded, and they are not cached

```yml
repeaters:
    name: Repeaters
    singular_name: Repeater
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        relationrepeater:
            type: repeater
            fields:
                sub:
                    type: text
                    variant: inline
                entryselect:
                    type: select
                    values: entries/id,title
                    sort: id
                    autocomplete: true
```

Proposed solution
--------
A solution would be to use the ajax autocomplete from the select2 component and make it fetch results on the fly from an async path when the `autocomplete: true` option is used.

Bonus solution
--------
Because in the back-end all records in related content types are also fetched, those might also use the same select2 component and async route to speed up the back-end even more.

Details
-------

 - Relevant Bolt Version: 3.x 
 - Install type: any
 - PHP version: any?
 - Used web server: Nginx
 - For UX/UI issues: any
