### ISSUE TITLE
[Bug] Custom Field Types Throw A Warning

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#6782]
An extension providing a custom field type following [Providing New Field Types](https://docs.bolt.cm/3.2/extensions/advanced/fieldtypes) docs example will throw an alert with the warning:  

>In the ContentType for 'yourContentType', the field 'yourField' has 'type: yourType', which is not a proper field type. Please edit contenttypes.yml, and correct this.  

Details
-------

 - Relevant Bolt Version: [ 3.2.14+ ]
 - Install type: [ Zip Install & Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache [2.4.18] | Nginx [1.10.2] ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

 1. **Bug summary**:  
  Custom field types throw a warning about not being a proper field type
 2. **Specifics**:
    * URL:  any backend page while logged in will have the alert
    * Bolt 3.2.14
    * Composer and Zip Installs
    * Browsers: Chrome/Firefox/Edge all of em :)
    * Error Message:  
      * >In the ContentType for 'yourContentType', the field 'yourField' has 'type: yourType', which is not a proper field type. Please edit contenttypes.yml, and correct this.  
      * ![bolt-custom-field-error](https://user-images.githubusercontent.com/5969974/27691299-99859cb6-5cb1-11e7-877a-fcf39d31a30c.png)

 3. **Steps to reproduce**:
    *   install bolt, create lorem ipsum records, install locally @rossriley 's URL field extension (https://github.com/rossriley/bolt-url-field)  
    * create or edit a contentType with the URL field and type  
    ```yaml  
    testField:
    name: TestFields
    singular_name: testField
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        web: # our field using custom type
            type: url # the custom type from Ross' example
            label: Enter a web address
    relations:
        pages:
          multiple: false
          order: title
          label: Select a page
    taxonomy: [ categories, tags ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    ```
 4. **Expected result**: 
    * No warning to be thrown since everything functions "normally"
 5. **Actual result**: 
    * a warning flashbag is thrown
