### ISSUE TITLE
PostgreSQL ORDER BY bug

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6796]
@rossriley I am not sure why this is happening, it is on latest 3.4-HEAD but I would hazard a guess that it is hitting 3.3 as well.

```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "ASC"
LINE 1: ...rticles.id, articles.id ORDER BY datepublish DESC ASC LIMIT ...
```

Full query:
```
An exception occurred while executing 
'SELECT articles.*, string_agg(relatedarticles.id::character varying, ',') as _relatedarticles_id, 
string_agg(relatedarticles.to_id::character varying, ',') as _relatedarticles_toid, 
string_agg(incomingrelation.id::character varying, ',') as _incomingrelation_id, 
string_agg(incomingrelation.from_id::character varying, ',') as _incomingrelation_fromid, 
string_agg(incomingrelation.from_contenttype::character varying, ',') as 
_incomingrelation_fromcontenttype, string_agg(sections.id::character varying, ',' ORDER BY sections.id) 
as _sections_id, string_agg(sections.slug::character varying, ',' ORDER BY sections.id) as 
_sections_slug, string_agg(sections.name::character varying, ',' ORDER BY sections.id) as 
_sections_name, string_agg(sections.taxonomytype::character varying, ',' ORDER BY sections.id) as 
_sections_taxonomytype, string_agg(tags.id::character varying, ',' ORDER BY tags.id) as _tags_id, 
string_agg(tags.slug::character varying, ',' ORDER BY tags.id) as _tags_slug, 
string_agg(tags.name::character varying, ',' ORDER BY tags.id) as _tags_name, 
string_agg(tags.taxonomytype::character varying, ',' ORDER BY tags.id) as _tags_taxonomytype FROM 
bolt_articles articles LEFT JOIN bolt_relations relatedarticles ON articles.id = relatedarticles.from_id 
AND relatedarticles.from_contenttype='articles' AND relatedarticles.to_contenttype='relatedarticles' 
LEFT JOIN bolt_relations incomingrelation ON articles.id = incomingrelation.to_id AND 
incomingrelation.to_contenttype='articles' LEFT JOIN bolt_taxonomy sections ON articles.id = 
sections.content_id AND sections.contenttype='articles' AND sections.taxonomytype='sections' LEFT 
JOIN bolt_taxonomy tags ON articles.id = tags.content_id AND tags.contenttype='articles' AND 
tags.taxonomytype='tags' GROUP BY articles.id, articles.id, articles.id, articles.id ORDER BY 
datepublish DESC ASC LIMIT 10':
```

**Edit:** In can it isn't obvious, the problem is around this being generated: `ORDER BY datepublish DESC ASC`

**Comment by rossriley** [comment]
I think there must be something a bit more subtle to this bug, here's what I've done to try and reproduce...

1. Install from tip of release/3.4
2. Prefill some entries content from the following configuration:

```yml
entries:
    name: Entries
    slug: entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            group: content
            default: A default title
        slug:
            type: slug
            uses: title
        teaser:
            type: textarea
            default: A default teaser
        body:
            type: html
            height: 300px
            default: Some default content
        image:
            type: image
            group: media
            upload: uploads
    relations:
        pages:
          multiple: false
          order: title
          label: Select a page
    taxonomy: [ categories ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    recordsperpage: 10
```

3. Tried adding some varying options for sort, eg: `sort: -datepublish`, `sort: id`, `sort: -id` and I seem to get both the backend list and the frontend list `/entries` working ok.

On the frontend Bolt generates the following query (this uses the legacy storage)

`SELECT bolt_entries.* FROM bolt_entries WHERE ("bolt_entries"."status" = 'published') ORDER BY "id" LIMIT 10 OFFSET 0`

In the backend which uses the new engine we get:

`SELECT _entries.*, string_agg(pages.id::character varying, ',') as _pages_id, string_agg(pages.to_id::character varying, ',') as _pages_toid, string_agg(incomingrelation.id::character varying, ',') as _incomingrelation_id, string_agg(incomingrelation.from_id::character varying, ',') as _incomingrelation_fromid, string_agg(incomingrelation.from_contenttype::character varying, ',') as _incomingrelation_fromcontenttype, string_agg(categories.id::character varying, ',' ORDER BY categories.id) as _categories_id, string_agg(categories.slug::character varying, ',' ORDER BY categories.id) as _categories_slug, string_agg(categories.name::character varying, ',' ORDER BY categories.id) as _categories_name, string_agg(categories.taxonomytype::character varying, ',' ORDER BY categories.id) as _categories_taxonomytype FROM bolt_entries _entries LEFT JOIN bolt_relations pages ON _entries.id = pages.from_id AND pages.from_contenttype='entries' AND pages.to_contenttype='pages' LEFT JOIN bolt_relations incomingrelation ON _entries.id = incomingrelation.to_id AND incomingrelation.to_contenttype='entries' LEFT JOIN bolt_taxonomy categories ON _entries.id = categories.content_id AND categories.contenttype='entries' AND categories.taxonomytype='categories' GROUP BY _entries.id, _entries.id, _entries.id ORDER BY id ASC LIMIT 10`

So I'm obviously missing some difference between our setups to get the error.
