### ISSUE TITLE
if a link field is added to a content type the slug is overridden

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#680]
If you add a link field to a content type like:

```
foos:
    name: Foos
    singular_name: Foo
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        link:
            type: text
```

The generated links in the default templates will be the value of the link field, instead of a nicely generated slug.
