### ISSUE TITLE
[BUG] edit item with a field templateselect  generate an error

### ISSUE THREAD

**Issue by kouz75** [bolt/bolt#6809]
Hi,
with the last beta.

Add a field of type templateselect to one of the content class.
ex :

```
        template:
            type: templateselect
            group: Présentation
            filter: 'template_*.twig'
```

In the backoffice try to add a item. 
bolt will return an error 

```
Twig_Error_Loader in Environment.php line 576: Unable to find one of the following templates: "MYCLASSNAME.twig", "record.twig", "record.twig".
```

if we remove the field from the class, everythings works fine.

With the previous release (3.2),  the field type templateselect works fine.

Details
-------

 - Relevant Bolt Version: [ 3.3.0 beta 12 ]
