### ISSUE TITLE
[BUG?] I need to clear the cache to make source code changes visible

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6815]
After installing Bolt 3.2.14 that was released yesterday I noticed a strange behavior. Changes to the source code aren't visible immediately when I reload the page. Before the update nothing was wrong. Now I have to clear the cache all the time and reload again to make changes visible.

**Comment by GawainLynch** [comment]
Is this a new install? It sounds (potentially) like the opcache.

**Comment by bobdenotter** [comment]
@gwbonline Which source code do you mean? Twig files or PHP?

**Comment by gwbonline** [comment]
Twig files from the theme folder.

**Comment by bobdenotter** [comment]
@gwbonline Make sure you've cleared the cache, and review the settings under `cache:` in `config.yml` and `config_local.yml` (if you have that one)

**Comment by gwbonline** [comment]
I already cleared the cache folder several times. Cache settings are as following. These are the same as before the update.

caching:
    config: true
    templates: true
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true

**Comment by bobdenotter** [comment]
could you try setting `templates: false` ? Also, make sure the indentation is correct: 

```
caching:
    config: true
    templates: true
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true
```
