### ISSUE TITLE
[3.3] Custom fields modified in Event Listener don't get saved.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6840]
To reproduce, you can use the following. If you set up the Translate extension, you'll be asked to add a few fields to any contenttype that should get translated. Edit`app/config/extensions/translate.animal.yml`:

```
locales:
    en_GB:
        label: English
        slug: en
    nl_NL:
        label: Nederlands
        slug: nl
```

Contenttypes.yml: (added a few fields, and the `is_translateable` to a few others)

```
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
            is_translateable: true
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
            is_translateable: true
        body:
            type: html
            height: 300px
            is_translateable: true
        locale:
            type: locale
            group: content
        nldata:
            type: hidden
        nlslug:
            type: locale_data
            index: true
        endata:
            type: hidden
        enslug:
            type: locale_data
            index: true
    taxonomy: [ groups ]
    recordsperpage: 100
```

Next, create a page as usual. After saving it for the first time, you can switch to Nederlands to provide the translation. 

Adding the translation and saving it, will cause the preSave ([here](https://github.com/AnimalDesign/bolt-translate/blob/master/src/EventListener/StorageListener.php#L165)) handler to modify the record. We can see this if we dump it, just before it returns: 

![screen_shot_2017-07-20_at_13_14_42](https://user-images.githubusercontent.com/1833361/28415248-28a75d14-6d4f-11e7-84e5-a4f06f951e97.png)

Also of note is that `nlslug` was not present _before_ it was set. Similarly, the other custom field `enslug` is missing too. This can also be seen if we debug `$record`, right after [this line](https://github.com/AnimalDesign/bolt-translate/blob/master/src/EventListener/StorageListener.php#L175).

After saving, we can see that `nldata` is saved in the DB, but `nlslug` isn't:

![screen_shot_2017-07-20_at_13_28_34](https://user-images.githubusercontent.com/1833361/28415310-61b7ef4c-6d4f-11e7-89f5-b4228d86382c.png)
