### ISSUE TITLE
[BUG?] info sign after each field title in 3.3.0 RC1 release

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6848]
I installed the 3.3.0 RC1 release and I notice an info sign (gray circle with a white i in it) after each field title. Not every field needs an explanation. Most of them contain no text. Is this a bug or can I disable them?

**Comment by bobdenotter** [comment]
Hey @gwbonline, 

Could you post a screenshot of this, along with the contenttype used? I think i know what you're saying, but i'm not seeing this behaviour myself.

**Comment by gwbonline** [comment]
Contentype code is an example. All contenttypes show this behaviour.

```
evenementen:
    name: Evenementen
    singular_name: Evenement
    fields:
        titel:
            type: text
            postfix: "Omschrijf met één of maximaal drie woorden het evenement"
            required: true
            class: large
            group: tekst      
        datum:
            type: text
            postfix: "Voorbeeld: 1 april 2017"
        tijd:
            type: text
            postfix: "Voorbeeld: 10.00"
        locatie:
            type: text
            postfix: "Naam locatie en adres. Voorbeeld: Roskam, Dorpsstraat 95, 6681 BM, Bemmel"            
        omschrijving:
            type: html
            height: 150px
            postfix: "Omschrijf het evenement zo volledig mogelijk"            
            required: true
        slug:
            type: slug
            uses: titel
        afbeelding:
            type: image
            postfix: "Let op: alleen liggende foto uploaden, staande foto wordt niet goed weergegeven"
            required: true
            group: media
    taxonomy: [ categorie ]
    record_template: evenement.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
```

![2017-07-23](https://user-images.githubusercontent.com/9332608/28499431-2c429da8-6fb6-11e7-803b-33b370fc1a0a.png)

**Comment by bobdenotter** [comment]
Have you cleared the cache? Both in your browser, and the one in Bolt?

**Comment by jackiboy** [comment]
Having the same issue as @gwbonline. it's appearing on all content types. Here is my Project content type
```
projects:
    name: Projects
    singular_name: Project
    fields:
        title:
            label: Project Name
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
            postfix: "<p>This is the url the project is located (You do not need to change this).</p>"
        location:
            label: Location
            type: text
            variant: inline
            postfix: "<p>Set Project Location (e.g. Wellington).</p>"
        type:
            label: Project Type
            type: select
            variant: inline
            values: { 'maintenance': "Maintenance", 'residential': "Residential", 'commercial': "Commercial", 'commercial interiors': "Commercial Interiors"}
            postfix: "<p>Select Project Type.</p>"
        image:
            label: Project Image
            type: image
            upload: projects
            postfix: "<p>The main project image that is used on the Home and Projects pages.</p>"
        introbody:
            label: Intro Project Body
            type: html
            height: 150px
            postfix: "<p>The introduction text that sits under the heading.</p>"
        projectimage:
            label: Project Body Image
            type: image
            upload: projects/body
            postfix: "<p>The secondary image thar sits under the introduction body text.</p>"
        decriptionheading:
            label: Description Heading
            type: text
            variant: inline
            postfix: "<p>The heading of the main content (This is optional).</p>"
        description:
            label: Project Body
            type: html
            height: 250px
            postfix: "<p>The main content for the project.</p>"
        gallery:
            type: imagelist
            upload: projects/gallery
            postfix: "<p>If you have multiple images and would like to display them in a gallery upload the images here.<br> The gallery will be displayed under the main content text.</p>"
    taxonomy: [ groups ]
    record_template: project.twig
    recordsperpage: 100
    default_status: publish
    description: '<p style="font-size: 1.5rem; line-height: 1.15em">Edit and create new Projects.</p>'
    icon_many: "fa:wrench"
    icon_one: "fa:wrench"
```
and what shows on the front end.

![screen shot 2017-07-23 at 11 45 14](https://user-images.githubusercontent.com/16835243/28500802-0073353e-6f9d-11e7-8ff4-eac721e0c780.png)
