### ISSUE TITLE
[Regression] Matched routes aren't identical between routing.yml and record.link()

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#6863]
I've tracked this back to this particular change here:

https://github.com/bolt/bolt/commit/7f2388492671b9d295100076d198d1a2555c3d98#diff-db653fc2f3af665e57b03efa4ea3b56dL182

The problem we're running into is that this change writes back a less accurate route match to the `_route` parameters in the request.

There's no problem with the route matching itself but two things happen, the Bolt debug bar incorrectly reports a `@contentlink` route when a more specific one is available and secondly if you did anything in your templates that depend on the correct value of `app.request.get('_route')` then that is obviously breaking.

Thanks to jives in Slack for the reproduction:

```yml
amp:
    path: /{contenttypeslug}/{slug}/amp
    defaults:
        _controller: controller.frontend:record
        pagetype: amp
    requirements:
        contenttypeslug: controller.requirement:anyContentType
```

Then visit a page with `/page/an-example-page/amp`
