### ISSUE TITLE
[BUG] Select fields inside repeaters are not displaying results

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#6864]
When using a select field that populates from a  content type inside a repeater it shows no results.

Details
-------

 - Relevant Bolt Version: 3.2.17
 - Install type: Composer install
 - PHP version:  7.1
 - Used web server: Apache 2.4 
 - For UX/UI issues: Chrome 59.0.3071.115

Reproduction
------------

```yaml
normalselect:
    type: select
    values: menus/id,title
menus:
    type: repeater
    fields:
        repeaterselect:
            type: select
            values: menus/id,title
```

Result
------------
![untitled](https://user-images.githubusercontent.com/3504472/28696469-fb3af882-72f2-11e7-80bc-c44ae9a54707.gif)
