### ISSUE TITLE
[BUG] Template tab showing regardless of whether selected template has any specific fields

### ISSUE THREAD

**Issue by tompato** [bolt/bolt#6868]
Details
-------

When you add a field to a content type of `type: templateselect` and then add a template specific field to one of your templates using the theme.yml file in your theme, regardless of whether you have selected this template, it will display the 'template' tab as an empty tab with no fields.

 - Bolt 3.3.1
 - Composer install
 - PHP 5.6
 - Apache 2.4

Reproduction
------------

Add a template select field to a content type.yml as below and then add a template specific field config in the theme.yml as below. When adding/editing a page that does not have the 'contact.twig' template (in this example) selected it still displays a 'Template' tab with no fields within it, whereas before (possibly prior to v3.3?) it would simply not display.

### contenttypes.yml

``` yaml
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
            required: true
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
            required: true
        template:
            type: templateselect
            filter: '*.twig'
    record_template: record.twig
    default_status: draft
    show_on_dashboard: true
    searchable: true
    sort: -datepublish
    recordsperpage: 10
    icon_many: "fa:file"
    icon_one: "fa:file"
```

### theme.yml

``` yaml
templatefields:
    contact.twig:
        location:
            type: geolocation
```

### Screenshots

<img width="825" alt="screen shot 2017-07-31 at 15 22 08" src="https://user-images.githubusercontent.com/1638465/28782090-1ad3e5e6-7604-11e7-9747-cae4345e7275.png">

------------

<img width="369" alt="screen shot 2017-07-31 at 15 22 21" src="https://user-images.githubusercontent.com/1638465/28782109-1f56ad60-7604-11e7-93f3-6914ff1fda32.png">
