### ISSUE TITLE
Multiple "grouping" taxonomies can't be saved

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#6880]
In my bolt configuration, I have a "member" contenttype that describes people. Each one can have one or multiple roles : technical or administrative.
The natural way to deal with that is to use a "role" taxonomy with "multiple" set to true. But I need sortorder, either for technical roles or administrative roles : I mean two different sort orders.

So I decided to create two taxonomies, using "grouping" in order to use sortorder : "administrative_role" and "technical_role". This seems to be allowed and displays well. But when you save a record, these taxonomies do not seem to be saved : they stay empy with order set to 0.

The point is : can we use multiple taxonomies of type "grouping" for one contenttype ? If the answer is yes, this is a bug. If the answer is no, perhaps would it be useful to clarify this point in documentation ?

Details
-------

 - Relevant Bolt Version: [ 3.3 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ] version [ 2.4.25]
 - For UX/UI issues: [ Firefox 54.0 ]

Reproduction
------------

 1. **Bug summary**: 
    * multiple taxonomies of type "grouping" display well in record, but are not saved, without any error message
 3. **Steps to reproduce**:
    * create two taxonomies of type "grouping"
    * assign them to on contenttype
    * create a new record of this contenttype, set taxonomy values and save
 4. **Expected result**: 
    * Taxonomies shall be saved
    * Or an error message shall be displayed

**Comment by xiaohutai** [comment]
See https://docs.bolt.cm/3.3/contenttypes/taxonomies

> Grouping is like categories but it is - by definition - more strict. When a grouping applies to a certain record, that record should be viewed as a part of the other records with the same grouping. As such, **a record can have only one 'grouping' at most**.

So yeah, a record can only have one grouping.

But there's an alternative, you can use the `select` field, and allow `multiple` and `sortable`.

```
            type: select
            multiple: true
            sortable: true
```

This is nice, but you'll lose the automatic listings with taxonomies (usually not that big of a deal).

More info on the select fieldtype: https://docs.bolt.cm/3.3/fields/select

**Comment by SahAssar** [comment]
Tagging this as a UX/UI issue since we should warn the dev/user in these cases.

**Comment by bobdenotter** [comment]
Actually, I don't think this is a bug at all. If you have a contenttype like this: 

```
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
    taxonomy: [ groups, alsogroups ]
```

It works as well as can be expected: The backend overview is sorted (and grouped) based on the _first_ `grouping` taxonomy that's encountered. 

Editing (and saving and reloading) of records works too: 

![screen shot 2017-10-13 at 19 35 00](https://user-images.githubusercontent.com/1833361/31558558-a6938108-b04d-11e7-89a9-7927cf607006.png)

I'll close this for now. If somebody has a reproducible case, or wants to discuss it more, feel free to re-open.
