### ISSUE TITLE
[3.3] Having empty or non-existing taxonomies shows an empty tab when editing content.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6930]
If you have this: 

```
dummy:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
    taxonomy: [ foo ]
```

or this: 

```
dummy:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
    taxonomy: [ ]
```

You'll get an empty tab when editing content:

![screen shot 2017-08-22 at 17 54 36](https://user-images.githubusercontent.com/1833361/29574819-fdf9e932-8762-11e7-8ac0-aefb8c35a207.png)

In these cases, the tab shouldn't be shown.
