### ISSUE TITLE
[BUG] underscores in contenttype names

### ISSUE THREAD

**Issue by jewe** [bolt/bolt#6957]
I have a contenttype called 'pages_de'. If i try to fetch content like this

`
setcontent pages = 'pages_de' where { groups: 'x' }
`

the resulting query is

`
... SELECT content_id AS id FROM bolt_taxonomy where "bolt_taxonomy"."taxonomytype" = 'groups' AND ( ... ) AND "bolt_taxonomy"."contenttype" = 'pages-de' ...
`

In the query-code 'pages_de' is transformed to 'pages-de', but the value in the database for the 'contenttype'-column is 'pages_de'.

Details
-------
 - Relevant Bolt Version: 3.3.1
 - Install type: Composer install
 - PHP version: 5.5
 - Used web server: Apache

**Comment by bobdenotter** [comment]
This is a known "quirk", and not something that's feasible to "solve" without breaking other stuff. 

That said, it _should_ work, if you use it consistently, like so: 

```
pages_de:
    name: Pages-de
    singular_name: Page-de
    slug: pages_de
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
```

Note how the "key" matches the `slug`. I'm closing this for now, but feel free to re-open it, if it's not working for you.
