### ISSUE TITLE
Cannot have case sensitive slugs

### ISSUE THREAD

**Issue by severak** [bolt/bolt#6965]
My [new site](http://tee.svita.cz/) works as catalogue of YouTube videos.

So I decided to use YoutTube ID as content slug, defined in `contenttypes.yml` like this:

```yaml
    youtube_id:
      label: ID videa
      type: text
      required: true
    slug:
      type: slug
      uses: youtube_id
```
However there is a caveat - slugs are lowecase while YouTube IDs are case-sensitive (Base64), so Bolt generates bad URLs. Is there any way how to fix it?

Details
-------

 - Relevant Bolt Version:3.3
 - Install type: Zip/tarball install
 - PHP version: 5.6
 - Used web server: Nginx
