### ISSUE TITLE
Taxonomies get saved as 'slugs', but not checked as such in the editor.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6973]
Details
-------

 - Relevant Bolt Version: 3.2 and up
 - Install type: N/A
 - PHP version: N/A
 - Used web server: N/A
 - For UX/UI issues: N/A

Reproduction
------------

As discovered by Nestor today. If you have a taxonomy like: 

```
groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options:
        main: "Main"
        the_meta_group: "Meta group"
        other: "Other"
    has_sortorder: true
```

And the user selects "Meta group", the value in the editor will be `the_meta_group`, but this will be saved slugified as `the-meta-group`. 
When the page gets edited again, the code to mark items as selected, will compare the taxonomy 
 value `the_meta_group` to the saved `the-meta-group`. This happens in `app/view/twig/editcontent/fields/_grouping.twig`: 

```twig
{% set attr_opt = {
    value:     slug,
    selected:  context.content.taxonomy.containsKeyValue(taxonomy.slug, slug),
} %}
```

and `src/Storage/Collection/Taxonomy.php`

```php
    public function containsKeyValue($field, $value)
    {
        foreach ($this->getField($field) as $element) {
            if ($element->getSlug() == $value) {
                return true;
            }
        }

        return false;
    }
```

Since `element->getSlug()` will always return a slugified version, I propose we change it to: 

```
if ($element->getSlug() == Slugify::create()->slugify($value)) {
```

Either that, or slugify the keys when the taxonomies get read and initialised.
