### ISSUE TITLE
Error editing record with imagelist within repeater field

### ISSUE THREAD

**Issue by billytd** [bolt/bolt#6979]
When editing a record in the bolt (3.3.3) admin for a contenttype that has an imagelist within a repeater field, I receive an error.

Details
-------

 - Relevant Bolt Version: 3.3.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache 2.4

Reproduction
------------

- Create a new contenttype
- include a repeater field
- add a imagelist field to the repeater
- open admin, create new record in the above content type
- add one or more images to the imagelist field within the repeater
- save the record
- reload the editcontent page for the record you just created.

At this point, I get an error page (see attached) with the following message:
```
Uncaught Exception: Twig_Error_Runtime .

Twig_Error_Runtime in Template.php line 556: 
Key "file_matcher" for array with keys "content, can" does not exist in "@bolt/editcontent/fields/_imagelist.twig" at line 69.
```

![image](https://user-images.githubusercontent.com/4671618/30083559-eba42f54-925c-11e7-98f3-8b7d1bc21e84.png)

Here is a simple conttenttype I created to reproduce the issue:
```
fakepage:
    name: Fake Pages
    singular_name: Fake Page
    fields:
        title:
            type: text
            group: content
        slug:
            type: slug
            uses: title
        sections:
            label: Section
            type: repeater
            group: content
            limit: 10
            fields:
                sectiontitle:
                    type: text
                    label: Header
                sectionimages:
                    type: imagelist
                    label: Images (optional)
                    postfix: "Used to create simple, inline slideshow"
                    extensions: [ gif, jpg, png, jpeg ]
```
