### ISSUE TITLE
[BUG] Select populated with contenttype loses sorting when filtering

### ISSUE THREAD

**Issue by cyanonoob** [bolt/bolt#7006]
Details
-------

 - Relevant Bolt Version: 3.3.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache version [2.x, my hosting doesn't expose this, though I could probably retrieve it if it is crucial]

Reproduction
------------

### Bug summary

When adding a select field to a contenttype, populating it with another contenttype's data, filtering it, and then setting sort to something, the sorting isn't (apparently) done.

### Steps to reproduce
Add these two contenttypes:

```
events:
    fields:
        title:
            type: text
            required: true
        location:
            type: text
        slug:
            type: slug
            uses: title
        date:
            type: date
        time:
            type: text
        description:
            type: html
        ext_url:
            type: text

newsletters:
    fields:
        subject:
            type: text
            required: true
        slug:
            type: slug
            uses: subject
        body:
            type: html
            required: true
        senddate:
            type: date
            required: false
        events:
            type: select
            values: events/date,title
            filter: { date: '>yesterday' }
            sort: date
            multiple: true
```

### Expected result

Find a select field for Newsletters, which is populated with Events with a 'date'-valuedated in the future, ordered by the same date field.

### Actual result
![image](https://user-images.githubusercontent.com/18364816/30522518-8a386f18-9bd1-11e7-8415-6ba683d4ec18.png)
The field isn't ordered by the date-field. However it does get sorted when you comment out the filter.
