### ISSUE TITLE
Adding label to select field causes error

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#7009]
Twig_Error_Runtime in Template.php line 447:
An exception has been thrown during the rendering of a template ("Warning: Illegal offset type in isset or empty") in "@bolt/editcontent/fields/_select.twig" at line 35.

**Comment by GawainLynch** [comment]
Bolt version?

**Comment by lenvanessen** [comment]
3.3.3

```
    contenttype:
            type: select
            label: Type of content
            values: [ none, Image switching sides, Small icons left ]
```
