### ISSUE TITLE
Exception setting up ContentType

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7040]
I tried using the example in the [3.4 docs](url=https://docs.bolt.cm/3.4/howto/singleton-contenttype#):
```
settings:
    name: Site Settings
    singular_name: Site Settings
    fields:
        headers:
            type: repeater
            group: headers
            fields:
                header_title:
                    type: text
                    label: Title text
        footer_text:
            type: html
            group: footer
        footer_copyright:
            type: text
        company_address:
            type: geolocation
            group: common
    viewless: true
    singleton: true
    default_status: published
    sort: -id
    icon_many: "fa:cogs"
    icon_one: "fa:cog"
```

Saved and right after, anything in the backend will display this:

![2017-09-30 14-18-56](https://user-images.githubusercontent.com/1833020/31049571-a19652d8-a5ea-11e7-9ce0-c6c6f82f349c.png)

Details
-------

 - Relevant Bolt Version: [ 3.4 beta 1 ]
 - PHP version: [ 7.1 ]
 - Used web server: [ Apache ]
