### ISSUE TITLE
Bolt contenttype field 'imagelist' not working as child of 'block' type field

### ISSUE THREAD

**Issue by nout-kleef** [bolt/bolt#7063]
Bolt back end shows Twig_Error_Runtime when an imagelist type field is nested in a block type field.

 

Details
-------

 - Relevant Bolt Version: **3.4.0 beta 2**
 - Install type: **Composer install**
 - PHP version: **7.0.20**
 - Used web server: **Bolt built-in web server**
 - Database driver: **sqlite**

Reproduction
------------
### Bug summary

When a 
```yml
field:
    type: imagelist
```
is nested in a
```yml
field:
    type: block
```
, the Bolt back end shows the following exception:
![screen shot 2017-10-09 at 16 10 41](https://user-images.githubusercontent.com/30589554/31342339-c02ec526-ad0c-11e7-8282-993fb648a5b5.png)

this only occurs when the imagelist field is nested in a block field (part of the _named repeaters_ functionality, linked below), and therefore most likely happens as a result of a bug in the _named repeaters_ module.

### Specifics

url: http://0.0.0.0:8000/bolt/editcontent/cases/1
the exception is thrown across all common browsers (safari, chrome, firefox)
there are no hard error messages, the only way to notice the bug is when trying to pick an option.

### Steps to reproduce

Using the relatively new _named repeaters_ functionality as described [here](https://github.com/bolt/bolt/pull/6215),
with 
```yml
cases:
    name: Cases
    singular_name: Case
    fields:
        contentblocks:
            type: block
            fields:
                sliderblock:
                    fields:
                        images:
                            type: imagelist
```
as (relevant part of) contenttypes.yml, the bug occurs on multiple browsers (safari, chrome, firefox).

### Expected result

I expected to be able to upload a few images to serve as a gallery. This happens correctly when the field is not nested in a block field.

### Actual result

, instead, the Bolt back end showed me the Twig_Error_Runtime, as shown in the uploaded screenshot.
