### ISSUE TITLE
[3.4] `title_format` doesn't work.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7064]
The `title_format` doesn't work anymore on 3.4.

Details
-------

 - Relevant Bolt Version: [  3.4  ]

Reproduction
------------
Set up a content type like: 

```yml
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        foo:
            type: text
        selector:
            type: select
            values: [ A-tuin, Donatello, Rafael, Leonardo, Michelangelo, Koopa, Squirtle ]
            multiple: false
            postfix: "Select your favourite turtle(s)."
    title_format: [ foo, selector ]
```

On 3.3 it shows: 

![screen shot 2017-10-09 at 19 47 07](https://user-images.githubusercontent.com/1833361/31351247-a70c49d8-ad2a-11e7-8a62-21b29157e35e.png)

(with 'foo' set to 'Bar', and selector set to 'Donatello')

Bumping it to 3.4 gives: 

![screen shot 2017-10-09 at 19 46 18](https://user-images.githubusercontent.com/1833361/31351282-c3e26376-ad2a-11e7-8c7f-df1cf4573973.png)
