### ISSUE TITLE
[3.4b3] Not setting a 'title' breaks backend, instead of displaying an error

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7095]
This is my test CT:

```
productions:
    name: Productions
    singular_name: Production
    fields:
        title:
            type: text
            group: General
            variant: inline
            class: large
        dates:
            type: repeater
            group: Calendar
            fields:
                performancedate: 
                    type: datetime
```

I tried to create  'New Production' and added dates but no 'title', hit save and backend breaks, like this:
![2017-10-16 23-43-54](https://user-images.githubusercontent.com/1833020/31650718-7e7a09da-b2cd-11e7-9fd9-a53474ae2e31.png)

And it seems that the only way to get past this error once it happens is to delete the content type definition...

=========
3.4 Beta 3
PHP 7
