### ISSUE TITLE
[3.4] Using a contenttype with dash throws exception, instead of the notice to fix it on the dashboard.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7123]
If you have a contenttype like this: 

```yml
dummies-foo:
    slug: dummies-foo
    name: Dummies
    singular_name: Dummy
    singular-slug: dummy-foo
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
```

The dashboard throws an exception: 

![screen shot 2017-10-26 at 12 22 19](https://user-images.githubusercontent.com/1833361/32048051-57c0cb44-ba48-11e7-9db4-bd26ccc38dd6.png)

In 3.3 it showed the notice how to fix it: 

![screen shot 2017-10-26 at 12 25 12](https://user-images.githubusercontent.com/1833361/32048148-c55db342-ba48-11e7-9d30-62a5e029a8c8.png)
