### ISSUE TITLE
[3.4] Block fields escape HTML content

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7137]
For example, this field def: 

```yml
        contentblocks:
            type: block
            label: Content Blocks
            group: Blocks
            fields:
                textsection:
                    label: Paragraph of text
                    fields:
                        heading:
                            type: text
                        content:
                            type: html
                            height: 100px
                imagesection:
                    label: Image with description
                    fields:
                        heading:
                            type: text
                        image:
                            type: image
                        description:
                            type: html
                            height: 70px
```

![screen shot 2017-11-01 at 14 42 07](https://user-images.githubusercontent.com/1833361/32277476-dc605c24-bf12-11e7-9c61-1f2ece4785b2.png)

With this in the template: 

```
    <hr><hr>

    {% for group in record.contentblocks %}
        {% if group.block == 'textsection' %}
            <h2>{{ group.heading }}</h2>
            {{ group.content }}
        {% endif %}
        {% if group.block == 'imagesection' %}
            <h2>{{ group.heading }}</h2>
            {{ group.image|showimage() }}
            {{ group.description }}
        {% endif %}
    {% endfor %}

    <hr><hr>
```

Shows this in-browser: 

![screen shot 2017-11-01 at 14 41 32](https://user-images.githubusercontent.com/1833361/32277449-c9794a4e-bf12-11e7-9975-ba96f8cd3a1b.png)

This can be "fixed" by adding `|raw`, but it should behave the same as a "normal" html field.
