### ISSUE TITLE
Slug incorrectly set when listing a Taxonomy 

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#7167]
Slug incorrectly set when listing a Taxonomy that has options mapped.

Details
-------

 - Relevant Bolt Version: [3.3.6 ]
 - Install type: [ tarball install  ]
 - PHP version: [ 5.6]
 - Used web server: [ Apache  ] version [ 2 ]

Reproduction
------------

- define a taxonomy as follows, using mapping

```
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options:   
         y2018: "2018"
```

- add a dump(slug) to your listing template
- visit /categories/y2008

I expected to see slug = y2018

The actual result is 2018
