### ISSUE TITLE
Back-end listing is cached unwillingly or not cleared when it should 

### ISSUE THREAD

**Issue by lenvanessen** [bolt/bolt#7168]
PHP 7
Bolt 3.3.6

The following is happening:
When you create a new entry, it does not show up in the back-end listing (the main one on the page, it does show up on the "recently edited" and "in the list in the left-hand menu"

Only if you do `php app/nut cache:clear` it fixes it. The cache clear from the back-end doesn't. 

If you delete the message, same issue but other way around (the message remains in the overview, with a link to a dead end).

**Comment by lenvanessen** [comment]
```caching:
    config: false
    templates: false
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true```

**Comment by lenvanessen** [comment]
```
caching:
    config: true
    templates: false
    request: true
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true

performance:
    http_cache:
        options:
            default_ttl: 604800
            #private_headers: [ Authorization, Cookie ]
            private_headers: [ Authorization ]
            allow_reload: false
            allow_revalidate: false
            stale_while_revalidate: 2
            stale_if_error: 60
```
