### ISSUE TITLE
[3.4][RFC] Fields, fields, fields. And blocks.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7171]
In 3.4 we have the new amazing Block field type. It uses the word 'field' a bit too much, though.. For example: 

```yaml
pages:
    name: Pages
    singular_name: Page
    fields:
        contentblocks:
            type: block
            label: Content Blocks
            group: Blocks
            fields:
                imagesection:
                    label: Heading
                    fields:
                        heading:
                            type: text
                textsection:
                    label: Paragraph
                    fields:
                        content:
                            type: html
                            height: 100px
```

So, yeah, we have `$app['config']->get('contenttypes/pages/fields/contentblocks/fields/imagesection/fields/heading')`. The multitude of `fields` makes it too complex, I think. 

Should we change the `fields:` used for Blocks definition to `blocks:` instead? It's a bit late in the release cycle, but i think we might just want to change it, before we have to deal with this confusing thing in a stable release. 

That way, our example would become: 

```yaml
pages:
    name: Pages
    singular_name: Page
    fields:
        contentblocks:
            type: block
            label: Content Blocks
            group: Blocks
            blocks:
                imagesection:
                    label: Heading
                    fields:
                        heading:
                            type: text
                textsection:
                    label: Paragraph
                    fields:
                        content:
                            type: html
                            height: 100px
```
