### ISSUE TITLE
Video field not fetching data inside Blocks

### ISSUE THREAD

**Issue by Mikescops** [bolt/bolt#7182]
Following https://github.com/bolt/bolt/issues/5471, here is a new issue concerning video field inside blocks.
It appears that the video field is not fetching video data from external services such as Youtube when the url is inserted in the input (same behavior when clicking on the refresh button).

It results that when group.video is dumped, all fields expect "url" are empty.

**Comment by bobdenotter** [comment]
I think this issue is less severe than we initially thought.. For example, I have this contenttype: 

```yaml
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        video:
            type: video
        repeater:
            type: repeater
            fields:
                repeatvideo:
                    type: video
    recordsperpage: 100
    template: page.twig
```

In the bolt backend, both the "regular" video and the "repeater" work: 

![screen shot 2017-12-08 at 12 10 33](https://user-images.githubusercontent.com/1833361/33763457-deee7a8c-dc10-11e7-8910-dd8812d22e1b.png)

If I use the following template: 

```twig
{{ record.video.html }}

{% for rep in record.repeater %}
    {{ rep.repeatvideo.html|raw }}
{% endfor %}
```

It also shows up: 

![screen shot 2017-12-08 at 12 12 28](https://user-images.githubusercontent.com/1833361/33763531-22266558-dc11-11e7-89cd-ee327fa95c3c.png)

@Mikescops Can you confirm this works for you? 

That said, the `responsive` attribute isn't set. just the `html` and other fields. I'll look into that.
