### ISSUE TITLE
[3.4] The "magic" image doesn't work anymore.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7194]
If you have a contenttype like this: 

```
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        picture:
            type: image
        teaser:
            type: html
            height: 150px
```

The 'picture' is not used as default thumbnail, see screenshot: 

![screen shot 2017-11-21 at 17 27 15](https://user-images.githubusercontent.com/1833361/33084061-3e4d84c4-cee1-11e7-8d1e-e8e474b06dc9.png)

Up until 3.4, the `content.getImage` was "magic", as it would return the first found image. Now it only returns a field named actually 'image'. 

This is the exact same issue as what happened here: #7067 (only there it was for the magic `getTitle`. 

I see two ways to fix it: 

 - We implement the `getImage` as a trait, like the deprecated `getTitle`
 - We get a head start on #6985, and implement a `findImage()` filter, so we can use `{{ content|findImage() }}`. 

Either way would get the listing to show "an image" again. 

Suggestions?
