### ISSUE TITLE
[RFC] Add ability to group contenttypes in the backend sidebar

### ISSUE THREAD

**Issue by panda-madness** [bolt/bolt#7224]
## Problem

Currently when there are a lot of contenttypes defined the backend sidebar gets swamped with links, and it looks untidy. [Example](https://imgur.com/aw21quN). The issue is further exacerbated with the introduction of singletons.

## Solution

It'd be nice to be able to define groups of related contenttypes that would collapse together into a single link in the sidebar, and reveal on click/hover as an accordion/popup (I suggest an accordion, because nested popup windows are a pain).

## Suggested syntax

Pretty simple, really.

```
ct_A:
    name: A content type
    slug: ct_a
    group: A single compact group
    fields:
        ...
ct_B:
    name: B content type
    slug: ct_b
    group: A single compact group
    fields:
        ...
```
