### ISSUE TITLE
Unable to save content, when content type field name consists __

### ISSUE THREAD

**Issue by rainpoiss** [bolt/bolt#7225]
I have a content type defined like this:

  ```
  variables: &variables
        str_emergency_telephone:
            type: text
            class: narrow
            variant: inline
            pattern: ^.{1,400}$
            group: grupname
        str__info_telephone:
            type: text
            class: narrow
            variant: inline
            pattern: ^.{1,400}$
```

Details
-------

 - Relevant Bolt Version:  3.3 and  3.4 
 - Install type: [Composer install  and GitHub checkout 
 - PHP version:  7.0
 - Used web server:  Apache | Nginx 

Reproduction
------------

Save the content type and create content.

### Bug summary

 only: str_emergency_telephone content will be saved. 
str__info_telephone content will not be saved. No errors appear in browser. POST status is 200

### Specifics

Using Bolt 3.3.1 and 4.4.2
database is postgres 9.6

### Steps to reproduce

Save the content type and create content.

### Expected result

Inserted content is saved to database

### Actual result

Database row is empty
