### ISSUE TITLE
[3.4] backend breaks on 'dashboardnews' if people are not paying attention very well to what they're doing. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7229]
If you're not paying attention, it's pretty easy to break the bolt backend. 

To reproduce: 

1) Set up a default Bolt instance, using your preferred method. 

2) Think to yourself "I'd like to set the branding options!"

3) Edit config.yml, and uncomment the following section from the default configuration: 

```yaml
branding:
    name: SuperCMS
    path: /admin
    provided_by: [ supercool@example.org, "Supercool Webdesign Co." ]
    news_source: http://news.bolt.cm
    news_variable: news
```

4) Visit the bolt backend: 

![screen shot 2017-12-03 at 17 28 59](https://user-images.githubusercontent.com/1833361/33527360-7e715888-d84f-11e7-9ebd-9b63350fbc7d.png)
