### ISSUE TITLE
[3.4.2] Blocks in back-end don't respect grouping order

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7232]
If you have a bunch of blocks, then re-order and save... and then refresh, the order in the back-end is not the same as in the database. It seems it _is_ correct when they are iterated (for-loop) in Twig / front-end.

Details
-------

 - Relevant Bolt Version: [ 3.4 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache ] version [ Apache/2.2.22 (Debian) ]

Reproduction
------------

1. Use Contenttype + Blocks
2. Create a record of that Contenttype
3. Shuffle some blocks up and down
4. Save and refresh

See this image:

![blocks-order](https://user-images.githubusercontent.com/4630335/33553268-4fa5dda4-d8f8-11e7-8313-3e0541ea7740.png)

**Comment by bobdenotter** [comment]
I think that's a duplicate of this one: https://github.com/BoltTranslate/Translate/issues/157

**Comment by xiaohutai** [comment]
@bobdenotter Oh yes, it is! It doesn't seem like a Translate issue to me 🤔

**Comment by bobdenotter** [comment]
In my brief testing, it went away when I disabled Translate, and came back when I re-installed it.

**Comment by xiaohutai** [comment]
Hmmm! The case I did above is without any extensions installed.

**Comment by xiaohutai** [comment]
Ohai! This issue results in **data loss** if the blocks don't have the same fields!

**Comment by xiaohutai** [comment]
```
__nodes:
        field_page__type: &field_page__type
            pagetype:
                label: Type Pagina
                type: block
                group: Type
                # limit: 1
                fields:
                    one:
                        label: One
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    two:
                        label: Two
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    three:
                        label: Three
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    four:
                        label: Four
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    five:
                        label: Five
                        fields:
                            title:
                                type: text


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        <<: *field_page__type
    taxonomy: [ groups ]
    recordsperpage: 100
    template: page.twig
```
