### ISSUE TITLE
[3.4.x] Ordering of blocks not explicit

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7248]
Related to #7232 and #7242 which fixed the data loss issue with several blocks.

There still is an issue with the ordering of the blocks in the back-end.

Details
-------

 - Relevant Bolt Version: [ 3.4 ]
 - Install type: [ GitHub checkout ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache]

Reproduction
------------

<details>
<summary>
Use this <code>page</code> in <code>contenttypes.yml</code> (click me to expand)
</summary>

```
__nodes:
        field_page__type: &field_page__type
            pagetype:
                label: Type Pagina
                type: block
                group: Type
                # limit: 1
                fields:
                    one:
                        label: One
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    two:
                        label: Two
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    three:
                        label: Three
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    four:
                        label: Four
                        fields:
                            title:
                                type: text
                            text:
                                type: text
                    five:
                        label: Five
                        fields:
                            title:
                                type: text


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        <<: *field_page__type
    taxonomy: [ groups ]
    recordsperpage: 100
    template: page.twig
```

</details>

### Steps

* New Page
* Add blocks "One", "Two", "Three", "Four", "Five"
* Fill in "1" in fields of "One", "2" in "Two", etc.
* Save, refresh, confirm: 1,2,3,4,5 ordering
* Now, re-sort by moving up and down, so that it becomes 5,4,3,2,1
* Save, refresh, I get: 3,5,4,2,1

### Expectation

I expect the ordering of 54321 instead of 35421.

### Observation / Interpretation

My observation is that, going from 12345 to 54321, the ordering does not change for item 3 (middle), which probably keeps the row intact. While others get deleted and then re-added.

MySQL show this:

![ordering-in-mysql](https://user-images.githubusercontent.com/4630335/33763051-3c859fd8-dc0f-11e7-8dbe-557ac172351b.png)
