### ISSUE TITLE
Select field: Wrong output when using numbers as presets

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#7295]
Values in a select field do not give expected results.

Example field in contenttypes.yml:
```
        year:
            type: select
            values: [ 2016, 2017, 2018 ]
            label: Year
```

Bolt backend shows the right presets (2016 | 2017 |2018).

Using {{ record.year }} in a template, the output should be a given value like '2018' but Bolt saves it in the database as 0, 1 or 2. So the actual output is 0, 1 or 2 instead of the expected 'year'.

Bolt 3.4.6
Tested on production site + clean installed site
