### ISSUE TITLE
Select field in repeater: Using multiple ContentTypes stores not contenttype/id

### ISSUE THREAD

**Issue by twwd** [bolt/bolt#7303]
When populating the values of a Select field with multiple ContentTypes (as stated [here](https://docs.bolt.cm/3.4/fields/select#populating-the-values-from-multiple-contenttypes)), only the `id` of the selected record is saved and not `contenttype/id`.

 

Details
-------

 - Relevant Bolt Version: 3.4.6
 - Install type: Composer install
 - PHP version: 7.2
 - Used web server: php built-in development server

Reproduction
------------

### Steps to reproduce

1. Add the following to an arbitrary ContentType (assuming that the ContentTypes `entries` and `pages` exist).
    ```yaml
            repeaterfield:
                type: repeater
                fields:
                    selectfield:
                         type: select
                         values: (entries,pages)/title
    ```
2. Create a new record of this type.
3. Create a repeated field set in this new record and select a value for the selectfield (e.g. the Page with id `1`).
4. Save the record.

### Expected result

I expect that `contenttype/id` is stored in the database, for instance `pages/1`.

### Actual result

The actual data that is stored in the database is just `1`.
