### ISSUE TITLE
Select Field - Using multiple ContentTypes doesn't store contenttype/id

### ISSUE THREAD

**Issue by Jabolek** [bolt/bolt#7339]
When trying to add select field (both _single_ and _multiple_ don't work) as below the stored keys should be in form of _contenttype/id_. ( according to [this](https://docs.bolt.cm/3.4/fields/select#populating-the-values-from-multiple-contenttypes) ) Instead, only id's are saved. The issue is really similar to the https://github.com/bolt/bolt/issues/7303 issue, the difference in select field not being inside repeater field.

 

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 7.2
 - Used web server: Nginx

Reproduction
------------

Define field like below in one of your content types (assuming you have _firstcontenttype_ and _secondcontenttype_ )

```
featured_resources:
    label: "Featured Resources"
    type: select
    values: (firstcontenttype,secondcontenttype)/title
    multiple: true
```
Next, add some entries to the select box and try to dump the value

```
{% dump(record.featured_resources) %}
```

### Expected result

```
array:2 [▼
  0 => "firstcontenttype/2"
  1 => "secondcontenttype/1"
]
```

### Dump result

```
array:2 [▼
  0 => "2"
  1 => "1"
]
```
