### ISSUE TITLE
Taxonomies: ContextErrorException

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#7362]
There seems to be something wrong with 'group' type taxonomies. 
When I create a new taxonomy 'hoofdstukken' and add a value to a record with that taxonomy, I get this error:

```
ContextErrorException in Listing.php line 179:
Notice: Undefined offset: 1

            return $results;
        }
        if (isset($taxGroup) && $taxGroup !== null) {
            foreach ($grouped as &$group) {
                usort($group, function ($a, $b) use ($resultTaxOrders) {
                    return $resultTaxOrders[$a->getId()] - $resultTaxOrders[$b->getId()];
                });
            }
        }

        return call_user_func_array('array_merge', $grouped);

```
Bolt 3.4.9
PHP 7.1.12 / Apache
This is a new website (first version 3.4.6, updated to 3.4.9)

This is my contenttype:

```
paginas:
    name: Paginas
    singular_name: Pagina
    fields:
        locale:
            type: locale
            group: content
        slug:
            type: slug
            uses: title
        title:
            type: text
            class: large
            label: Titel
            translatable: true
	(...)
        seo:
            type: seo
            group: SEO
        nldata:
            type: hidden
        nlslug:
            type: locale_data
            index: true
        endata:
            type: hidden
        enslug:
            type: locale_data
            index: true
    recordsperpage: 100
    taxonomy: [ hoofdstukken ]
```
My taxonomy:

```
hoofdstukken:
    slug: hoofdstukken
    singular_slug: hoofdstuk
    behaves_like: grouping
    options:
        overzichtspaginas: Overzichtspagina's
        overig: Overige pagina's
    has_sortorder: true
```
