### ISSUE TITLE
Invalid datetime format: 1292

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#7375]
I'm getting an error when trying to save a page with template fields:

```
An exception occurred while executing 'UPDATE bolt_pages SET id = ?, slug = ?, 
datecreated = ?, datechanged = ?, datepublish = ?, datedepublish = ?, ownerid = ?, 
status = ?, templatefields = ?, title = ?, image = ?, teaser = ?, body = ?, template = ? 
WHERE id = ?' with params ["12", "dinner", "2017-01-11 08:17:10", "2018-03-13 17:16:57", 
"2017-01-11 08:16:33", "-0001-11-30 00:00:00", "1", "published", 
"{\"section_1_imagelist\":\"[{\\\"filename\\\":\\\"2018-dinner-sponsor-logos\/150_CC_SponsorLogos_B2C2.png\\\",\\\"title\\\":\\\"2018-dinner-sponsor-logos\/150_CC_SponsorLogos_B2C2\\\"},{\\\"filename\\\":\\\"2018-dinner-sponsor-logos\/150_CC_SponsorLogos_Fidelity Labs.png\\\",\\\"title\\\":\\\"2018-dinner-sponsor-logos\/150_CC_SponsorLogos_Fidelity Labs\\\"}]\",\"section_2_imagelist\":\"[]\",\"section_3_imagelist\":\"[]\"}", "Coin Center Annual Dinner 2018", "{\"file\":\"2018-02\/1519849965_fred-dinner.png\"}", 
null, null, "page-dinner.twig", "12"]: SQLSTATE[22007]: 
Invalid datetime format: 1292 Incorrect datetime value: '-0001-11-30 00:00:00' for column 
'datedepublish' at row 1
```

Details
-------

 - Relevant Bolt Version:3.4.9
 - Install type: Composer install
 - PHP version: 7.1
 - Used web server: Apache version 2.4

Reproduction
------------

### Steps to reproduce

~1. Add template fields to the `theme.yml`file:~

```yaml
templatefields:
  page-dinner.twig:
    section_1_heading:
      type: text
    section_1_imagelist:
      type: imagelist
    section_2_heading:
      type: text
    section_2_imagelist:
      type: imagelist
    section_3_heading:
      type: text
    section_3_imagelist:
      type: imagelist
```
2. Go to the backend and try to save

### Expected result

To save normally.

### Actual result

The error mentioned previously.
