### ISSUE TITLE
Uploading big file problems

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7408]
Big size files upload problems
---
**(or maybe i haven't found something?)**
1. improper messages about big filesize in file manager (see below). 
2. No maximum filesize control in backend. All relies on [php ini](https://github.com/bolt/bolt/blob/3.4/src/Filesystem/FilePermissions.php#L132) or [undocumented options](https://github.com/bolt/bolt/blob/3.4/app/src/js/widgets/buic/buicUpload.js#L40))
3. (?) no limits on upload in file manager. At least i don't see it [in app/src/js/modules/filemanager.js] (https://github.com/bolt/bolt/blob/3.4/app/src/js/modules/filemanager.js#L152-L168) . 
4. No **unified** configuration for maximum filesize, which is set in backend and translated to frontend. I mean in `config.yml` or somewhere else. Which also should be limited by php internal limits.

---

#### 1. Improper messages
I'm trying to upload big file size in filemanager. I'm dropping 2 files, one - 4Mb, another one - 661kb. 
![2018-03-27_22-07-08](https://user-images.githubusercontent.com/2145313/37976294-61a69716-320b-11e8-8a28-679d13b58912.gif)
- I see that `SiriusPhp` (as UploadHandler) gives incorrect message about file extension instead of size
  ![image](https://user-images.githubusercontent.com/2145313/37976740-5e62f0e4-320c-11e8-8f50-363ef5c5af06.png)

- also success message uses incorrect slugified file name
   ![image](https://user-images.githubusercontent.com/2145313/37976703-48583048-320c-11e8-8bf1-2a13feb1062b.png)
   while uploaded filename is:
   ![image](https://user-images.githubusercontent.com/2145313/37976834-9654c874-320c-11e8-9d16-176153939a1a.png)

#### 2. no limits in backend
As i mentioned in [this comment](https://github.com/bolt/bolt/issues/7401#issuecomment-376539770) — fileUpload configuration relies on `ini_get('...')`. And i haven't found any file size related options in config.
Also Sirius PHP (as upload handler) could also get that option from Bolt.

#### 3. no limits in frontend
I haven't found any file size limit in `filemanager.js`. There _is_ one in `buicUpload.js`, but as i said in p2 - it relies on _php_ options, not _Bolt's_

#### 4. no single config
For me it seems that Bolt heavily lacks this option, which will configure all possible file uploads. Like
```yml
upload:
  pattern: '[^A-Za-z0-9\.]+'
  replacement: '-'
  lowercase: true

  max_filesize :  # in bytes
  max_image_filesize : # separate value if you plan to allow users upload 20mb PDFs and <2mb images
  accept_file_types: [ txt, md, pdf, epub, mp3 ]
  accepted_image_extensions: [gif, jpg, jpeg, png, svg]
```

It will make config more neat, collect all separated upload options to one bunch. Also this config could be passed to frontend (to use in filemanager and buicUpload).
