### ISSUE TITLE
field.slug.label:'foo' doesn't work for slug

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7424]
If i make this config 
```yml
# contenttypes.yml
fieldname:
    slug:
        label  : 'Постоянная ссылка'
        type   : slug
        uses   : title
        postfix : "Постоянная ссылка"
```
postfix works, label - doesn't.

![image](https://user-images.githubusercontent.com/2145313/38141681-7b873294-3463-11e8-984f-8624c7fa9b22.png)

Maybe we should take label from contenttype config, and fallback to default only if it's missing?
