### ISSUE TITLE
Bug with filtering when contenttype has own slug

### ISSUE THREAD

**Issue by otrelin** [bolt/bolt#7439]
I have contenttype:
```
products_de:
    name: Products [de]
    singular_name: Product [de]
    slug: produkte
    singular_slug: produkt
    tablename: products_de
    fields:
        ...
    taxonomy: [ productcategories ]
```
I set slug to have german url for german site version, but for contenttype and table I want to have name `products_de`. For english site version I want to create other contenttype `products_en` with the same structure, but with slug `products`. Table name will be also `products_en`.

Taxonomy `productcategories` is:
```
productcategories:
    name: Product category
    slug: productcategories
    singular_name: Product category
    singular_slug: productcategory
    behaves_like: categories
    options: { oxid-modules: "OXID Modules", shopware-modules: "Shopware Modules", magento-extensions: "Magento Extensions" }
    listing_template: product-listing.twig
```

I have one product with category "OXID Modules" and one product with category "Shopware Modules".

When I want to filter my products in frontend by 
```
{% setcontent products = 'products_de' orderby 'datepublish' where { productcategories: 'oxid-modules' } %}
```
the variable `products` is empty.

Here is taxonomy table:
![1523537040408](https://user-images.githubusercontent.com/15085327/38677958-69862618-3e68-11e8-98eb-7aa2c4643944.jpg)

I was interested in why the field `contenttype` contains values `products_de` instead of `produkte` (as slug set)?
When I manually edit one field to
![1523537579690](https://user-images.githubusercontent.com/15085327/38678435-aa7fc204-3e69-11e8-96a2-eca4f267e5e7.jpg)
in frontend filter is working. But after that filters in the backend stopped working
![1523537786451](https://user-images.githubusercontent.com/15085327/38678595-2c13aed4-3e6a-11e8-8ddc-1f101b46866d.jpg)
and in Taxonomy tab of changed product (id 1) category is not set
![1523538060548](https://user-images.githubusercontent.com/15085327/38678867-effa1716-3e6a-11e8-972a-4dec89dd97a3.jpg)

Details
-------

 - Relevant Bolt Version: 3.4.8
 - Install type: Composer install
 - PHP version: 7.1.16
 - Used web server: Apache 2.4

### Expected result
In table `bolt_taxonomy` field `contenttype` use only slug but not contenttype name. And this should work fine both in frontend and backend.

### Actual result
In table `bolt_taxonomy` field `contenttype` use contenttype name. And this causes a problem with filtering in frontend.
Now the only variant is when name and slug are the same. But in this case parameter `slug` in contenttype will never be used.

**Comment by bobdenotter** [comment]
Hi, 

We're aware that there's some discrepancy in how the 'key' and the 'slug' are used. This is why we strongly advise to keep the slug the same as the "key" of the contenttype: 

```yaml
produkte:  # <- like this.
    name: Products [de]
    singular_name: Product [de]
    slug: produkte
    singular_slug: produkt
    tablename: products_de
```
