### ISSUE TITLE
[BUG] Uncaught Exception: ConversionException in singleton with select field

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#7448]
I couldn't find anything about this in the docs so.. Here it is, in my contenttypes.yml I've got:

```yaml

settings:
    name: Site Settings
    singular_name: Site Settings
    fields:
        featured:
            type: select
            values: entries/id
            multiple: true
            autocomplete: true
            sortable: true
    viewless: true
    singleton: true
    default_status: published
    sort: -id
    icon_many: "fa:cogs"
    icon_one: "fa:cog"
```

And I get this:

`Could not convert database value "{"url":"https:\/\/ww..." to Doctrine Type json`

Details
-------

 - Relevant Bolt Version: 3.5
 - Install type: Composer install
 - PHP version: 7.1
 - Used web server: Apache 2.4.33
