### ISSUE TITLE
Bolt crashes when a contentblock-field contains a child field with the same name

### ISSUE THREAD

**Issue by blaues0cke** [bolt/bolt#7461]
So I recently used this definition in my `contenttypes.yml`:

```
pages:
    name: Seiten
    singular_name: Seite
    fields:
        title:
            type: text
            class: large
            group: content
            label: Titel
        slug:
            type: slug
            uses: title
        contentblocks:
            type: block
            label: Blöcke
            group: content
            fields:
                button_link:
                    label: Button-Link-Block
                    fields:
                        heading:
                            type: text
                            label: Überschrift
                        sub_heading:
                            type: text
                            label: Unter-Überschrift
                        button_headline:
                            type: text
                            label: Button-Überschrift
                        button_link:
                            type: text
                            label: Button-URL
                        button_text:
                            type: text
                            label: Button-Überschrift
        seo:
            type: seo
            group: SEO-Einstellungen
        template:
            type: templateselect
            filter: '*.twig'
            group: content
    taxonomy: [ groups ]
    recordsperpage: 20
    default_status: published
    record_template: page.twig
    listing_template: pages.twig
```

This will make bolt to display everything correctly until I save a new block using the generated backend. After this initial save, something - I think the cache - is broken with the following error (`FatalThrowableError in FieldManager.php line 69: Class name must be a valid object or a string`):

![image](https://user-images.githubusercontent.com/5159398/39573103-0e492d34-4ed2-11e8-8a62-8d16d3ec0bac.png)

To workaround this, I have to rename the inner `button_link` to something that does not match a name of the `contentblocks`s `fields`. I would at least expect a earlier error message that reminds to to prevent duplicated field names inside a `contentblocks` since the error message is very difficult to read and has no hint to the actual problem.
