### ISSUE TITLE
[BUG] Field with same name as other one inside repeater overwrites config of the first one

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7496]
Bug summary
---

If field in repeater has the same name as other field outside of this repeater, then the first one takes configuration from the second. Configuration of field in repeater is overwritten.

Details
-------

 - Relevant Bolt Version: 3.5.1

Reproduction
------------

Content type config:
```
articles:
    name: Articles
    fields:
        details:
            type: repeater
            label: Details
            fields:
                value:
                    type: html
                    label: Details information
                type:
                    type: select
                    label: Detail type
                    values:
                        important: Important!
                        normal: Normal one
        type:
            label: Article type
            type: select
            values: 
                news: News
                other: Other article
```
With this config, enter Article edit page and you can notice that `Detail type` select has values taken from `Article type`.

Expected result
----

`Detail type` select should have options: `Important!`, `Normal one`.

Actual result
----

`Detail type` select has options: `News`, `Other article`.
