### ISSUE TITLE
Unable to add a relation with setRelation()

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#7497]
When I import records in a custom bundle, I can't add a relation between entities.

There seems to be a mismatch between `setRelation()` in `Storage/Entity/Content` 
https://github.com/bolt/bolt/blob/3.5/src/Storage/Entity/Content.php#L256-L259
and  `setRelation()` in `Storage/Entity/ContentRelationTrait`
https://github.com/bolt/bolt/blob/3.5/src/Storage/Entity/ContentRelationTrait.php#L104-L109

As usual I don't even know if I'm doing it the right way. Is there a normal way to add entity relations that I can use?

Details
-------

 - Relevant Bolt Version:  3.5
 - Install type: Composer install | GitHub checkout

Reproduction
-------
The page 15 exists and the persons [5016, 5017, 5004, 4903] also exist.
There is a relation set in `contenttypes.yml`
```yml
pages:
  name: Pages
  singular_name: Page
  fields:
    [.. some fields ..]
  relation_persons: &relation_persons
    persons:
      label: "Contacts"
      multiple: true
      order: last_name
      format: "{{ item.last_name }}, {{ item.first_name }}"

persons:
  name: Persons
  singular_name: Person
  fields:
    [.. some fields ..]
```
When you run the following code:
```php
        $parent_type = 'pages';
        $target_type = 'persons';
        $repo = $this->app['storage']->getRepository($parent_type);

        $currentrecord = $repo->find(15);

        $currentrecord->clearRelation($target_type);

        foreach ([5016, 5017, 5004, 4903] as $target_record_id) {
          $currentrecord->setRelation($target_type, $target_record_id);
        }
        $repo->save($currentrecord);

        dump($currentrecord);

```
Result
-------
```
FatalThrowableError in Content.php line 256:
Type error: Argument 1 passed to Bolt\Storage\Entity\Content::setRelation() must be an instance of Bolt\Storage\Collection\Relations, string given, called in /[..]/extensions/bundles/myvendor/mybundle/src/Controller/Backend.php on line 102
```
