### ISSUE TITLE
Content Type // Repeater // Checkbox // Default // Checked // NOK

### ISSUE THREAD

**Issue by steiha** [bolt/bolt#7508]
Can not have a checkbox in repeater set which is checked by default.

Details
-------

 - Relevant Bolt Version: 3.5.3
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache

Reproduction
------------

contenttypes.yml
```
        repeater:
            type: repeater
            group: repeater
            fields:
                enabled:
                    type: checkbox
                    default: 1

```

### Bug summary

Can not have a checkbox in repeater set which is checked by default.

### Steps to reproduce

- add a repeater set to a content type
- add a field of type checkbox to the repeater set
- add default: 1

### Expected result

Expected to have the checkbox checked by default.

### Actual result

Checkbox is not checked.
