### ISSUE TITLE
Maid seems to screw up the charset.

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#753]
Test run:  

``` YAML
config.yml: 
    locale: de_DE
    database:
        driver: mysql
#################
contenttypes.yml: 
        body:
            type: markdown
            height: 300px
            label: Seiteninhalt
        content:
            type: html
            height: 300px
            label: Seiteninhalt
```

``` Shell
root@asdf:~# locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

``` Twig
            {{ record.body }}
            {{ record.content }}
```

Test result:

![output](https://f.cloud.github.com/assets/1579335/1726509/dcf475fe-6290-11e3-8de2-4cf108ebf10a.png)

Test backtracked:

``` PHP
class \Bolt\Content {

    public function getDecodedValue($name) {
        ...

            switch ($fieldtype) {
                case 'markdown':

                    error_log(var_export("Raw, DB incoming string: " . $this->values[$name], true));

                    $value = $this->preParse($this->values[$name]);
                    error_log(var_export("Bolt_Content - preparsed: " . $value, true));

                    // Parse the field as Markdown, return HTML
                    $value = \Parsedown::instance()->parse($value);
                    error_log(var_export("\Parsedown - parsed: " . $value, true));


                    $maid = new \Maid\Maid(array('output-format' => 'html'));
                    $value = $maid->clean($value);
                    error_log(var_export("\Maid - cleaned: " . $value, true));

                    $value = new \Twig_Markup($value, 'UTF-8');
                    error_log(var_export("returned Twig-Markup: " . $value, true));

                    break;

        ...
    }
}
```

Backtrack Output: 

```
[Wed Dec 11 13:21:16 2013] [error]  'Raw, DB incoming string: # \xc3\x9cberschrift\r\n\r\nSeiteninhalt\r\n\r\n* Auflistung\r\n** Zweite Ebene\r\n\r\n[Typischer Link](http://www.google.de)'
[Wed Dec 11 13:21:16 2013] [error]  'Bolt_Content - preparsed: # \xc3\x9cberschrift\r\n\r\nSeiteninhalt\r\n\r\n* Auflistung\r\n** Zweite Ebene\r\n\r\n[Typischer Link](http://www.google.de)'
[Wed Dec 11 13:21:16 2013] [error]  '\\\\Parsedown - parsed: <h1>\xc3\x9cberschrift</h1>\n<p>Seiteninhalt</p>\n<ul>\n<li>Auflistung\n** Zweite Ebene</li>\n</ul>\n<p><a href="http://www.google.de">Typischer Link</a></p>'
[Wed Dec 11 13:21:16 2013] [error]  '\\\\Maid - cleaned: <h1>\xc3\x83\xc2\x9cberschrift</h1>\n<p>Seiteninhalt</p>\n<ul>\n<li>Auflistung\n** Zweite Ebene</li>\n</ul>\n<p>Typischer Link</p>'
[Wed Dec 11 13:21:16 2013] [error]  'returned Twig-Markup: <h1>\xc3\x83\xc2\x9cberschrift</h1>\n<p>Seiteninhalt</p>\n<ul>\n<li>Auflistung\n** Zweite Ebene</li>\n</ul>\n<p>Typischer Link</p>'
```

Ouch. Someone got a hint?
