### ISSUE TITLE
"default" property not respected in contentblocks

### ISSUE THREAD

**Issue by blaues0cke** [bolt/bolt#7539]
So I try to set a default for fields used in `contentblocks` but the `default` field is not respected. If I move the fields directly to the fields of the parent `contenttype` everything works as expected.

Contenttype to try with:

```
pages:
    name: Seiten
    slug: seiten
    singular_slug: seite
    singular_name: Seite
    fields:
        title:
            type: text
            class: large
            group: content
            label: Titel
            default: This is working
        checkbox_test:
            type: checkbox
            label: This is working
            default: 1
        slug:
            type: slug
            uses: title
        contentblocks:
            type: block
            label: Blöcke
            group: content
            fields:
                text_block:
                    label: Text
                    fields:
                        title:
                            type: text
                            label: Titel
                            default: this is NOT working
                        checkbox_test:
                            type: checkbox
                            label: This is NOT working
                            default: 1
        seo:
            type: seo
            group: SEO-Einstellungen
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ groups ]
    listing_records: 20
    recordsperpage: 20
    default_status: published
    record_template: page.twig
    listing_template: pages.twig
```

This will render the following page directly after pressing the "add new" button:

![image](https://user-images.githubusercontent.com/5159398/41973846-7e147fc8-7a16-11e8-8f69-df7272a96582.png)

Details
-------

 - Relevant Bolt Version: 3.5.4
 - Install type: Composer install
 - PHP version: 7.1
 - Used web server: Nginx

### Steps to reproduce

Add the content type above to your installation and hit the "create"/"new" button

### Expected result

`default` property should work for `fields` in `contenttype`, too.

### Actual result

`default` property does not work for `fields` in `contenttype`.
