### ISSUE TITLE
[BUG] Regression on select choices for Templatefields

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#7547]
This side effect seems to have been introduced via the fix in #7505 

Templatefields options don't match the same structure so the select choices need to be built in the same way that repeaters/blocks were changed.

Reproduction, config in theme.yml:

```
templatefields:
   index.twig:
       banner:
           label: Banners
           type: repeater
           fields:
               banner_title:
                   label: Title
                   type: text
               banner_position:
                   label: Position
                   type: select
                   values: { 'align-left':'Left', 'align-right':'Right' }
```

No select options showing in the editcontent screen.

credit to @mikenosko for the bug report.
