### ISSUE TITLE
setcontent changes date value in query

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#7551]
If you usee setcontent with a zero date - `'0000-00-00 00:00:00'` in a datettime field the query is modified to  `'-0001-11-30 00:00:00'`. This is weird, and it might be a bug.

-------

 - Relevant Bolt Version: 3.5.4
 - Install type: Composer install
 - PHP version: 7.2.7
 - Used web server: Nginx version nginx/1.14.0 (Ubuntu)
 - For UX/UI issues: -

Reproduction
------------

### Steps to reproduce
Content type:
```yml
events:
    name: Evenementen
    singular_name: Evenement
    slug: events
    singular_slug: event
    fields:
        title:
            type: text
            class: large
        eventtype:
            type: select
            label: Soort event
            values:
                normaal: normaal
                lezing: lezing
                discussiebijeenkomst: discussiebijeenkomst
        date:
            type: datetime
            group: Inschrijven
            variant: inline
        body:
            type: html
            height: 300px
```
Setcontent:
```twig
{% setcontent items = 'events' where {
   'eventtype' : type, 
   'date' : '0000-00-00 00:00:00' 
} printquery %}
```

### Actual result
Printed Query:
```sql
SELECT bolt_events.* 
FROM bolt_events 
WHERE (`bolt_events`.`eventtype` = 'lezing' 
AND `bolt_events`.`date` = '-0001-11-30 00:00:00' 
AND `bolt_events`.`status` = 'published') 
ORDER BY `title` LIMIT 9999
```
### Expected result
Expected Query:
```sql
SELECT bolt_events.* 
FROM bolt_events 
WHERE (`bolt_events`.`eventtype` = 'lezing' 
AND `bolt_events`.`date` = '0000-00-00 00:00:00' 
AND `bolt_events`.`status` = 'published') 
ORDER BY `title` LIMIT 9999
```
