### ISSUE TITLE
Search functionality breaks if there isn't at least one text field

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7575]
If you define a content type that doesn't have at least a single text input field, the front end functionality of your site will break.

Details
-------

 - Relevant Bolt Version: [ 3.5.5 | master ]
 - PHP version: [ 7.0 ]

Reproduction
------------

- Create a content type such as:
```
homepage:
    name: Homepage
    singular_name: Homepage
    singleton: true
    show_in_menu: Pages
    fields:
        images:
            type: repeater
            label: Images
            fields:
                image:
                    type: image
                    attrib: [ title ]
```

- Go to your front page and use the search box

### Specifics

- This is the error that you will see:
![image](https://user-images.githubusercontent.com/1833020/43370838-43a65bfc-933b-11e8-95f2-e731760d51cd.png)

- It appears the issue is that there isn't any text fields in the content type
- The error goes away if you add a text field to your content type
```
homepage:
    name: Homepage
    singular_name: Homepage
    singleton: true
    show_in_menu: Pages
    fields:
        name:
            type: text
            label: Title
            class: large
        images:
            type: repeater
            label: Images
            fields:
                image:
                    type: image
                    attrib: [ title ]
```
