### ISSUE TITLE
If first contentype field is not text, the reminding fields won't render  

### ISSUE THREAD

**Issue by willhertz** [bolt/bolt#7587]
Probably related with #7575 

When you create a contentype if the first field is not a text field the rest of the fields won't render in the backend (haven't tested frontend since can't even populate the fields).

There are no error messages

As soon as you place a text field as the first field all the fields render properly.

Details
-------
Bolt 3.5.3
Composer install
PHP 5.5.9-1ubuntu4.21
Apache/2.4.7 (Ubuntu)

**Comment by bobdenotter** [comment]
Hi, 

I've created a contenttype like this: 

```yaml
dummies:
    slug: dummies
    singular_slug: dummy
    fields:
        number:
            type: integer
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: [ title ]
        teaser:
            type: html
            height: 150px

```

For me, this works as expected: 

![screen shot 2018-08-08 at 16 26 04](https://user-images.githubusercontent.com/1833361/43843399-c6446be6-9b27-11e8-9d11-9f67d8654c78.png)

Can you give more info on how to reproduce this?
