### ISSUE TITLE
[RFC] Bootstrap col- and row- for Markup Editor

### ISSUE THREAD

**Issue by dhalucario** [bolt/bolt#7616]
I would love to have bootstrap column and row in the markup editor. It would make it alot easier to create "prettier" content, especially when people have something like a blog. It would give the editors a bit more playroom when they work with big spaces and blog posts wouldn't look all the same.

How can you help?
-------------------------------
I'm currently doing college so I have only time at the weekends, and even that is limited, but I would try getting a running version down, even if it takes some time.

**Comment by eduardomart** [comment]
You can do this with the `block` field type:
https://docs.bolt.cm/3.5/fields/block

Here's an example of it being used:
http://recordit.co/0LYTbypUGr

**Comment by SvanteRichter** [comment]
@eduardomart I think they are talking more about being able to add it in the editor itself rather than having a preconfigured block for it.

Personally I'm against this, it couples content to layout to much, and having it be "col-" or "row-" even more couples it to a certain framework.

**Comment by jadwigo** [comment]
I think this might be a job a Bolt extension that injects CKEditor add-ons into the back-end. These add-ons like https://ckeditor.com/cke4/addon/ckeditor-bootstrap-templates or https://ckeditor.com/cke4/addon/bootstrapTabs add a button or other options to CKEditor which add bootstrap specific options.

There's more options on https://ckeditor.com/cke4/addons/search/plugins/bootstrap

I think this should not be part of the Bolt core, for the reasons @SahAssar already stated.

**Comment by dhalucario** [comment]
It doesn't have to be bootstrap in first place. I wouldn't mind doing a recreation of the col/row system bootstrap uses. Or we use the minimum grid file bootstrap uses. I don't want it to be completely forced using bootstrap. 

Its more about giving the user a good bit more control about how something is placed. This isn't supposed to be a replacement for a complete page layout. I wouldn't mind using the plugins either but I think it would make bolt alot more attractive as a cms if its supported and built in.

**Comment by jadwigo** [comment]
If you are adding a col/row system in the html editor you also have to take the website theme into account - maybe that theme uses bootstrap and then it is logical to use one of the bootstrap add-ons for CKEditor. But if your theme does not use that the bootstrap grid anything you do with bootstrap in the html fields will probably look out of place. 

Bolt is built as a system that is independent from the framework used in the theme for the frontend. This is why we do not want to couple the layout to bootstrap, or any other framework.

If you couple the layout to any framework you need to take into account that the content will work on all possible devices (phones, tablets, desktops, televisions, screenreaders and more) and that means that you will simultaneously need to edit the theme templates to handle your content correctly, with the bootstrap content.

If you do not use a framework in your content, but use the bolt repeatable blocks / repeaters you can define the layout options in the theme, and your site will be more flexible. You still need to create templates to handle the layout options you want, but that is something you needed to do anyway.

The video @eduardomart linked shows how this can work: http://recordit.co/0LYTbypUGr

I did something something similar for one site - it has some contentblocks which each have their own template in the front-end that takes the `imagestyle` and `moviestyle` fields as parameters for the classes in the html. The contentypes.yml looks roughly like this:
```yml
# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro
__nodes:
    contentblock_defaults: &contentblock_defaults
        contentblocks:
            type: block
            label: Content Blocks
            info: "You can add as many content blocks as you wish"
            group: Blocks
            fields:
                sectionimage:
                    label: Section with image
                    fields:
                        heading:
                            type: text
                        image:
                            type: image
                            attrib: [title, alt]
                        imagestyle:
                            type: select
                            values:
                                left: Image left
                                right: Image right
                                centered: Image centered
                                background: Image in background
                        description:
                            type: html
                            height: 300px
                sectiontext:
                    label: Simple paragraph
                    fields:
                        heading:
                            type: text
                        content:
                            type: html
                            height: 300px
                sectionmovie:
                    label: Section with movie
                    fields:
                        heading:
                            type: text
                        movie:
                            type: video
                        moviestyle:
                            type: select
                            values:
                                left: Video left
                                right: Video right
                                centered: Video centered
                                background: Video in background
                        description:
                            type: html
                            height: 300px
                sectionmap:
                    label: Section with location map
                    fields:
                        heading:
                            type: text
                        content:
                            type: html
                            height: 300px
                        location:
                            type: geolocation

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        <<: *contentblock_defaults
    taxonomy: [ groups ]
    recordsperpage: 100
```

Alternatively it is possible to create a Bolt extension to add the bootstrap add-ons to the CKEditor.

But this is not something we will add to the Bolt core because it would mean more code we need to maintain, and it is not the best solution in our opinion.
