### ISSUE TITLE
switch/case statement doesn't work as expected

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7634]
Found some strangeness working with the `switch/case` statement

I have the following CT:
```
pages:
    name: Pages
    singular_name: Page
    show_in_menu: Pages
    fields:
        title:
            type: text
            class: large
            group: content
        contentblocks:
            type: block
            label: Content Blocks
            fields:
                header:
                    label: Header
                    group: TEXT
                    fields:
                        headertext:
                            label: Text
                            type: text
                        headernumber:
                            label: Type
                            type: select
                            values: {'h2': "H2", 'h3': "H3", 'h4': "H4", 'h5':"H5" }
                textblock:
                    label: Text Block
                    icon: "fa:align-left"
                    fields:
                        textblocktext:
                            label: Content
                            type: html
```

If I do the following, in my template, it all works as expected:
```
{% for group in record.contentblocks %}
        {% if group.block == "header" %}
            {{ group.headertext|markdown }}
        {% elseif group.block == "textblock" %}
            {{ group.textblocktext|raw }}
        {% endif %}
{% endfor %}
```

And if I do this:
```
{% switch group.block %}
            {% case "header" %}
                <{{ group.headernumber }}>{{ group.headertext|markdown }}</{{ group.headernumber }}>
            {% case "texblock" %}
                {{ group.textblocktext|raw }}
{% endswitch %}
```

The `header` field will be output but not the `texblock`

---

I don't know this qualifies as a *Bolt* bug or if it's maybe an actual *Twig* bug

***Using: Bolt 3.5.7***
