### ISSUE TITLE
"No results found" - select field inside repeater field

### ISSUE THREAD

**Issue by Jabolek** [bolt/bolt#7651]
Values for dynamic select field (based on `contenttype`) inside the repeater field (inside a template) doesn't populate values when editing the page.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.5.4-3.5.7
| Install type                   |  Composer install
| BC Break                     | yes
| PHP version                 | 7.2
| Web server                  | Nginx

Reproduction
------------
Add below configuration in `contenttypes.yml`:
```
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            label: "Title"
            type: text
        slug:
            type: slug
            uses: title
        template:
            type: templateselect
            filter: 'views/*.twig'
```
Add below configuration in `theme.yml`:

```
templatefields:
    /home.twig:
        relatedpages:
            type: repeater
            fields:
                name:
                    type: text
                link:
                    type: select
                    keys: slug
                    values: pages/title
```
Add a couple of pages to Bolt CMS.

### Bug summary

The issue doesn't exist in 3.5.3.

### Expected result

The select list should include all defined pages
### Actual result

The select list is empty
