### ISSUE TITLE
[BUG] Image field does not check extension

### ISSUE THREAD

**Issue by JarJak** [bolt/bolt#7721]
Description:
----
I have a field:

```
        image:
            label: Photo
            type: image
            extensions: [ gif, jpg, jpeg, png ]
```
But I am able to select any file (for example pdf file) from file browser to this field. Only the uploader excludes invalid file types.

Steps to reproduce:
----
1. Upload PDF file through another file field.
2. Try to set uploaded PDF as value of image field
3. Save

Expected result:
----
I would expect to not be able to select file other than types defined in field config
or an error on save.

Actual result:
----
Content saved without error, only the thumbnail displays an error.
