### ISSUE TITLE
[RFC] Mark an image field as required

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#7752]
It would be hard to add an image field as a required field?

```yaml
        image:
            type: image
            prefix: "<p>An image is required.</p>"
            required: true
```

How can you help?
-------------------------------

If someone can point me to correct files and the tasks to be done I can make a PR.
