### ISSUE TITLE
Bolt not generating thumbnail aliases if uploaded via the file management

### ISSUE THREAD

**Issue by Spomsoree** [bolt/bolt#7756]
I'm trying to generate consistent thumbnails. 
The whole aliases are working great, except if  I'm uploading directly via the file management. If i do so, I only get one thumbnail which can be found in the 54x40c directory.
54x40 isn't even my "default_thumbnail", I habe no idea why this happens.

As I said it's working great if I upload the images directly into a block.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | v3.6.0
| Install type                   |  composer install
| BC Break                     | no
| PHP version                 | 7.2
| Web server                  | Nginx
| For UX/UI issues        | Tested in Chrome

Reproduction
------------

Go to /bolt/files and upload a File.
See the thumbnails generated in: public/thumbs

You can also upload a file via a block:
```
example_block:
    label: Example-Block
    fields:
        image:
            type: image
            label: Image
```

### Bug summary

Different thumbnails generated depending on the location the image is uploaded.

### Specifics

My thumbnail aliases:
```
thumbnails:
    aliases:
        thumbnail:
            size: [250, 150]
            cropping: crop
```

Example-Block:
```
example_block:
    label: Example-Block
    fields:
        image:
            type: image
            label: Image
```

![image](https://user-images.githubusercontent.com/14187981/53962747-293f8900-40ec-11e9-853c-d0345e96d1fa.png)

Image 1.jpg and 3.jpg are uploaded via "domain.dev/bolt/files", 2.jpg is uploaded via the example block.

### Expected result

I'd expect the thumbnails to be generated consistently.

### Actual result

Image 2.jpg is generated as expected.
Image 1.jpg and 3.jpg should do the same.
