### ISSUE TITLE
Post-3.6.6 upgrade: js error in /bolt/files 

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#7765]
Flawlessly the site was upgraded from 3.4 to 3.6.6 recently. Ever since the backend shows a JS error in the files management section and doesn't allow uploading of files. When working on an entry of a content type, files can be uploaded properly - and they'll be put in YYYY-MM directory as defined in the default behavior. Enabling the debug log sadly didn't give me any clue. All that is logged when reloading the page is that the session cookie is renewed (`Generating authentication cookie — User ID: '1' Salt...`).

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.6
| Install type                   | Composer install 
| BC Break                     | what is that?
| PHP version                 | 7.0.33-0ubuntu0.16.04.3
| Web server                  | Apache, version 2.4.18-2ubuntu3.8
| For UX/UI issues        | Chrome, MacOS, v. 73.0.3683.86

AppCFG:
```yaml
database:
    driver: mysql
    databasename: xxx
    username: xxx
    password: xxx
sitename: A sample site
payoff: The amazing payoff goes here
theme: xxx
locale: de_DE
timezone: Europe/Berlin
maintenance_mode: false
maintenance_template: maintenance_default.twig
cron_hour: 3
favicon: ./favicon.ico
homepage: /
homepage_template: index.twig
add_jquery: false
recordsperpage: 10
caching:
    config: true
    templates: true
    request: false
    duration: 120
    authenticated: false
    thumbnails: true
    translations: true
changelog:
    enabled: false
thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    notfound_image: view/img/default_notfound.png
    error_image: view/img/default_error.png
    save_files: true
    allow_upscale: false
    exif_orientation: true
    only_aliases: false
htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dh, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]
accept_file_types: [ twig, gif, jpg, jpeg, png, pdf, epub, svg, json]
debug: false
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: 8181           
debug_error_use_symfony: false      
production_error_level: 8181 
debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG
strict_variables: false
wysiwyg:
    images: true            
    anchor: false            
    tables: false            
    fontcolor: true          
    align: false             
    subsuper: false          
    embed: false             
    underline: false         
    ruler: false             
    strike: false            
    blockquote: false        
    codesnippet: false       
    specialchar: false       
    ck:
        autoParagraph: true  
        disableNativeSpellChecker: true 
        allowNbsp: false
google_api_key: "xxx"
liveeditor: false
mailoptions:
    transport: mail
    spool: false
cookies_use_remoteaddr: false
cookies_use_browseragent: false
cookies_use_httphost: false
cookies_lifetime: 1209600
cookies_domain: ".xxx.com"
hash_strength: 10
enforce_ssl: true
```

![image](https://user-images.githubusercontent.com/1579335/55320263-f7b1a780-5476-11e9-8588-7eda641c1260.png)
