### ISSUE TITLE
DATABASE_URL as parameter in config.yml

### ISSUE THREAD

**Issue by patarapolw** [bolt/bolt#7788]
As Heroku Postgres uses [DATABASE_URL](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-with-pdo), and parameters needs to be parsed to `host`, `databasename`, `username`, `password`, and `driver`; it would be safer if I can set

```
database:
    url: "%env(DATABASE_URL)%"
```

Instead of, <https://github.com/rossriley/bolt-heroku/blob/bolt3/app/config/config.yml#L8>

This also doesn't work,

```
database:
    driver: postgres
    username: "%env(key:user:url:DATABASE_URL)%"
    password: "%env(key:pass:url:DATABASE_URL)%"
    databasename: "%env(key:path:url:DATABASE_URL)%"
    host: "%env(key:host:url:DATABASE_URL)%"
    port: "%env(key:port:url:DATABASE_URL)%"
```
