### ISSUE TITLE
Get records with specific taxonomy value

### ISSUE THREAD

**Issue by Spomsoree** [bolt/bolt#7806]
I'm trying to filter my records trough a taxonomy category, but It does not work how the documentation says it should.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.8
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.2
| Web server                  | Nginx

Reproduction
------------

My Taxonomy: (copied from the documentation: https://docs.bolt.cm/3.6/contenttypes/taxonomies)
```
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [news, events, movies, music, books, life, love, fun]
```

My contenttype: 
```
news:
    name: News
    singular_name: News
    slug: news
    default_status: published
    record_template: news-item.twig
    listing_template: news.json.twig
    listing_records: 10
    icon_many: 'fa:newspaper-o'
    icon_one: 'fa:newspaper-o'
    taxonomy: categories
    fields:
         ...
```

I'm now trying to filter the news via the categories. 

My news.json.twig: (I'll use it as a json-API later on)

```
{% set currentFilter = app.request.get('c') %}

{# List all categories linked to the a record #}
{{ dump(records|first.taxonomy.categories) }}

{# The applied filter #}
{{ dump(currentFilter) }}

{# The query #}
{% setcontent records = 'news' where { categories: currentFilter } %}

{# The result #}
{{ dump(records|length) }}
```

The output of this debugging code is the following:
![image](https://user-images.githubusercontent.com/14187981/63572954-64dbeb80-c584-11e9-98fa-8e070e679bc6.png)

The first line proves that at least one news item is linked to the music taxonomy, the second proves I'm using a category that is linked to a news item.

### Bug summary

If I'm calling **/news?c=music** it should give me all news items with the taxonomy music linked to it, as documented here: https://docs.bolt.cm/3.6/templating/content-fetching#using-taxonomies

### Specifics

There are no errors, but also not the expected output.

### Steps to reproduce

- Add the contenttypes & taxonomy to your bolt installation
- Create a News Item and link it to a category (in my example **music**)
- Go to the news page and apply the filter as in my code example

### Expected result

The created news item should be returned by the query.

### Actual result

No items are returned from the query.
