### ISSUE TITLE
localization: languageselect helper works only with homepage (select that loads in the menu)

### ISSUE THREAD

**Issue by tourdefran** [bolt/bolt#7901]
I have two localizations, default language is spanish, second language english

the select goes to "en/" only in homepage, in the other pages does nothing at all

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | Bolt 4.1.12
| Install type                   | Composer install
| BC Break                     | yes
| PHP version                 | PHP 7.3.11 (cli) (built: Jun  5 2020 23:50:40) ( NTS )
| Web server                  | Bolt built in server
| For UX/UI issues        | Chrome for Mac Version 88.0.4324.182 (Official Build) (x86_64)

Reproduction
------------

1- I'm in home http://127.0.0.1:8000/
2- click on select > English, goes to http://127.0.0.1:8000/en/ (correct)
3- now I click on bio (contenttype singleton) goes to http://127.0.0.1:8000/bio
4- click on select > English, nothing happens (error) expected to go to http://127.0.0.1:8000/en/bio
5- If I manually go to http://127.0.0.1:8000/en/bio the data is loaded correctly

UPDATE:
trying to approach a different solution now I have this related issue:

locales() in subpage doesn't work and brings the default language instead of secondary

http://127.0.0.1:8000/en/about => returns ES (wrong)
http://127.0.0.1:8000/en => returns EN (correct)
http://127.0.0.1:8000/ => returns ES (correct, default)

https://user-images.githubusercontent.com/2666701/108534449-eb2bd780-72b8-11eb-8f7a-2a013569901a.mov

contenttypes.yaml:
```
homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
            postfix: |
                The 'Homepage' can contain basic information about the website. This title will be
                shown on the homepage of the website, as the name implies. To change the
                <em><strong>name</strong></em> of the site, as is shown in the header, and the tab
                in the webbrowser, edit <code>sitename:</code> in the configuration file.
        imageMainHero:
            type: image
        carousel:
            type: imagelist
        slug:
            type: slug
            uses: title
            group: Meta
    viewless: false
    taxonomy: [ categories, tags, foobars ]
    locales: ['es', 'en']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"


imagenes:
    name: Imagenes
    singular_name: Imagen
    fields:
        titulo:
            type: text
            class: large
            group: content
            localize: true
            required: true
        epigrafe:
            type: textarea
            localize: true
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
        imagen:
            type: image
            label: Resolución normal para web
        imagenAlta:
            type: image
            label: En alta (se usa para la descarga)
        slug:
            type: slug
            uses: titulo
            group: Meta
    taxonomy: [ categories ]
    record_template: imagen.twig
    locales: ['es', 'en']    
    records_per_page: 5
    order: id
    icon_many: "fa:image"
    icon_one: "fa:image"

indice:
    name: Indice
    singular_name: Indice
    fields:
        title:
            type: text
            localize: true
            class: large
            group: content
            label: Title
        body:
            type: redactor
            localize: true
            height: 300px
        slug:
            type: slug
            uses: title
            group: Meta
    record_template: indice.twig
    default_status: published
    viewless: false
    locales: ['es', 'en']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"    

bio:
    name: Bio
    singular_name: Bio
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
        body:
            type: redactor
            localize: true
            height: 300px
        slug:
            type: slug
            uses: title
            group: Meta
    record_template: bio.twig
    default_status: published
    viewless: false
    locales: ['es', 'en']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"

about:
    name: About
    singular_name: About
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
        body:
            type: redactor
            localize: true
            height: 300px
        contact:
            type: redactor
            localize: true
            height: 300px
        slug:
            type: slug
            uses: title
            group: Meta
    record_template: about.twig
    default_status: published
    viewless: false
    locales: ['es', 'en']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"`
```
menu.yaml
```
main:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: Bio
    title: This is the <b>second<b> menu item.
    link: bio/
    class: bio
  - label: Index
    title: This is the <b>second<b> menu item.
    link: indice
    class: indice
  - label: About
    link: about
```
services.yaml
```
parameters:
    locale: 'es'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: es|en
    app.notifications.email_sender: anonymous@example.com
    bolt.table_prefix: bolt_
    bolt.backend_url: /bolt

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'
            $projectDir: '%kernel.project_dir%'
            $publicFolder: '%bolt.public_folder%'
            $tablePrefix: '%bolt.table_prefix%'
```
