### ISSUE TITLE
templateselect fieldtype filter not working

### ISSUE THREAD

**Issue by ghost** [bolt/bolt#7903]
The regex filter in templateselect fieldtypes does not seem to work. 
Partials with a _ prefix are not excluded from the select. 
I have the forms extension enabled. Don't know if that makes a difference.
```
template:
            type: templateselect
            filter: '/^[^_].*\.twig$/'
```

```
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        teaser:
            type: textarea
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
        image:
            type: image
            label: Highlighted image
        body:
            type: redactor
            height: 300px
        slug:
            type: slug
            uses: title
            group: Meta
        template:
            type: templateselect
            filter: '/^[^_].*\.twig$/'
    taxonomy: [ groups ]
    locales: ['en', 'nl_NL', 'nl_BE', 'fr']
    records_per_page: 5
    order: id
```

Only twig files are listed.

removing the locales key from the contenttype makes no difference to the field. issue persists.
