### ISSUE TITLE
Genarating Chinese and other Asian slugs

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#7911]
In Chinese, in a contenttype using
```
(...)
        slug:
            type: slug
            uses: title
```
hitting "generate slug from title" does not generate a slug. Wanted to mention it because having a slug is mandatory in Bolt 4/5. Not sure if this can be considered a Bolt bug, the actual issue comes from the Asian languages. I believe many Asian webdevs use English or numeric urls, so maybe Bolt can generate something numeric? 
After seeing this I chose to not make the slug localizable in my particular site  which is no big problem.
