### ISSUE TITLE
Relationships are not selected after upgrade to 1.4.0

### ISSUE THREAD

**Issue by ddpardo** [bolt/bolt#802]
After upgrading bolt to 1.4.0 I noticed that existing relationships are not selected anymore resulting in a list who displays '(none)'.

After some print(item) I found out that the item.selected value  always is false.

Below are some screenshots and the content types I used.

Mysql records with existing relationships:

![image](https://f.cloud.github.com/assets/2494889/1817358/7da30eb6-6f93-11e3-841b-902ed0492b85.png)

the id of the current video is 3

![image](https://f.cloud.github.com/assets/2494889/1817362/3eef98be-6f94-11e3-8745-d69015085b79.png)

![image](https://f.cloud.github.com/assets/2494889/1817374/9292b35a-6f96-11e3-990a-6fff23d94b74.png)

Here are my content types:

``` YAML
videos:
   name: Videos
   singular_name: video
   fields:
       title:
           type: text
       slug:
           type: slug
           uses: title
       description:
           type: html
           height: 150px
       video:
           type: video
   relations:
        speakers:
          multiple: true
          order: name
          label: Select a speaker
   taxonomy: [tags]
   record_template: video.twig
   listing_template: videos.twig
   listing_records: 5
   sort: datepublish DESC
```

``` YAML
speakers:
    name: Speakers
    singular_name: speaker
    fields:
     name:
        type: text
        class: large
        required: true
     website:
        type: text
        class: large
        pattern: url
    relations:
     videos:
        multiple: true
        order: title
        label: Select a video
```
