### ISSUE TITLE
permissions with 'owner' quirk.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#834]
This doesn't work as expected: 

``` yml
contenttypes:
    entries:
        edit: [ owner ]
        create: [ owner ]    
        change-ownership: [ owner ]     
```

The expected behaviour is that the 'owner' of a specific record would be allowed to edit their own records, but they aren't.

See: http://forum.pivotx.net/viewtopic.php?f=17&t=4432
