### ISSUE TITLE
routing.yml breaks sitemap.xml requests

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#841]
So, I have the following in my routing file:

``` yml
pages:
  path:               /{slug}
  defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'page' }
```

However, when I request `sitemap.xml`, Bolt says that `page/sitemapxml` was not found.

Perhaps extensions should be called early so that their `$app->match(...)` doesn't break?

`[1.4.4]`
