### ISSUE TITLE
Themes should be able to use an "option file".

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#854]
Like we have `config.yml` for Bolt itself and extensions, it should be possible for a theme to have a `.yml` file with theme-specific settings as well. 

A (short/incomplete) example could be

``` yml
# config file for Foo theme
logo: img/logo.png
slogan: This is the slogan on this theme

color: #F00
background_color: #E2E2E2

frontpage_listing_items: 5
archive_listing_items: 15

```

This file would be parsed by Bolt, and the Theme can be built to use these values like `{{ theme.logo }}`. If you're building a theme you can add as many of these options to your theme config as you want to have.
