### ISSUE TITLE
Database check ignoring field (and content-type definition)

### ISSUE THREAD

**Issue by mikerockett** [bolt/bolt#869]
Just noticed this. In my content type definitions, I have the following:

``` yml
funds:
    name: Funds
    slug: funds
    singular_name: Fund
    singular_slug: fund
    fields:
        name:
            label: Fund Name
            type: text
            class: large
            required: true
        slug:
            label: Permalink
            type: slug
            uses: name
        logo:
            label: Fund Logo
            type: image
        intro:
            type: textera
            height: 85px
            required: true
        information:
            label: Fund Information
            type: html
            height: 500px
            required: true
    record_template: fund.twig
    listing_template: funds.twig
    listing_records: 10
    sort: name ASC
    recordsperpage: 10
```

When I tried to create a new Fund, an error was thrown saying that the column `intro` does not exist in the table. When I checked the database schema manually, I confirmed this. So, I did a database check, and it said that everything was up to date. Weird.

So, I changed `intro` to `excerpt`, tried another update, and it didn't change anything, saying that it was already up to date.

What could be causing this?
