### ISSUE TITLE
Routing question

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#879]
I am about to replace my client's current site with a shiny new Bolt site, and I want to make redirects for the urls of the plm. 7 most important landing pages in the current site. 

Currently I use individual routing overrides, e.g.

```
contactbinding:
 path: /contact/adresgegevens
 defaults: { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'pagina', 'slug': 'contact' }
 recordslug: pagina/contact
```

It works, technically but I find that this also changes the links within the new site's menus, so this way we'll be stuck with "/contact/adresgegevens" forever. So I'm probably using the wrong method here.

What should I use to let all visitors go to the new "pagina/contact" url via the menu in the new site? (so I can delete the overrides after a couple of months).
