### ISSUE TITLE
No title in content listing

### ISSUE THREAD

**Issue by trigau** [bolt/bolt#933]
In order to set a sort of calendar, I created a contenttype that contains a date field and to relations (to "locations" and "people").

As you can see, this contenttype contains no text field. Moreover, it contains none of the fields names used by default to define title (ie : "title", "name", "caption", "subject"). So content listing for this contenttype shows no title and it is impossible to order it, as far as it doesn't display dates nor relations. Actually, it displays an almost empty line for each record.

So the issues I see are :
1) hardcoded default titles seem to be useless when you create contentypes with local names
2) using only text fields to define title seems useless if you use no text field

So I suggest some new features :
1) let the user define the title just like when he defines the slug. Something like :

```
    fields:
        title:
            type: title
            uses: [field1, field2]
```

2) extend the way "uses" works in order to allow the use of relations or dates. Something like :

```
    fields:
        title:
            type: title
            uses: [date1, relation1.name, relation2.location]
```
