### ISSUE TITLE
Relations ordering not working

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#942]
I'm having some trouble getting the ordering working with a relation.

```yaml
news:
    fields:
        ...
    relations:
        pages:
            multiple: true
            label: Select page
            order: -id
```

I get the relations on my page with the recommended code from the documentation:

```twig
{% set relatedrecords = record.related() %}
{% if relatedrecords is not empty %}
    <p>Related content:</p>
    <ul>
    {% for related in relatedrecords %}
        <li><a href="{{ related.link }}">{{ related.title }}</a></li>
    {%  endfor %}
    </ul>
{% endif %}
```

However I've noticed if I change `order: -id` to `order: id` the order stays the same. I even tried changing it to something like: `order: datepublish` and still nothing changed. I cleared the cache each time as well just to make sure that wasn't having an effect.
