### ISSUE TITLE
Contenttype patterns do not prevent form submission

### ISSUE THREAD

**Issue by diggersworld** [bolt/bolt#989]
I've been trying to add a constraint on an input field for a `contenttype`:

```yaml
email:
    type: text
    prefix: "<p>Please supply a valid email address.</p>"
    required: false
    pattern: email
```

The only effect this has on the input field is the red highlight if entered incorrectly. I still have the ability to save an invalid email address. From what I've read the idea here is to utilise the HTML pattern matching producing a field like this:

```html
<input type="email" name="email">
```

On submit HTML5 should run it's validation and tell me that I've entered incorrect data (in browsers that support it). However this isn't happening, and I'm using Chrome which does support HTML5 input patterns.

I find the same results with `url` and also regex patterns.
