### ISSUE TITLE
("Some mandatory parameters are missing ("contenttypeslug") to generate a URL for route "contentlink"."

### ISSUE THREAD

**Issue by glasspear** [bolt/bolt#998]
I have the following contenttype, which seems to be correct but when I add a 'location' (which says it saves correctly, and shows up in the DB) it causes the overview page to throw this  error:

"Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("contenttypeslug") to generate a URL for route "contentlink".") in "_listing-base.twig" at line 109."

contenttype in question -

``` yml
locations:
    name: Locations
    signular_name: Location
    fields:
        name:
            type: text
        address:
            type: geolocation
        crossstreet:
            type: text
        day:
            type: select
            values: [ Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
        time:
            type: text
        season:
            type: select
            values: [ Year-Round, Winter, Summer]
    sort: name
    recordsperpage: 100
    default_status: publish
    searchable: false
```

What am I doing wrong? Any insights would be appreciated.
